(function() {var l=void 0,m=!0,p=null,t=!1;function A(){return function(){}}
function W(){function b(){return function(c){try{c||(c=e.event),g="blur"==c.type||"focusout"==c.type?t:d?e.document[d]?t:m:m}catch(b){}}}function c(){try{var c=p,g=p,n={hidden:"visibilitychange",sc:"mozvisibilitychange",yc:"webkitvisibilitychange",tc:"msvisibilitychange",uc:"ovisibilitychange"};for(c in n)if(n.hasOwnProperty(c)&&c in document){g=n[c];break}g&&(d=c,i(e.document,g,b()))}catch(j){}}var g=m,e=window.parent,d,i=function(){function c(b,g,d){c=b.addEventListener?function(c,b,g){c.addEventListener(b,
g,t)}:b.attachEvent?function(c,b,g){c.attachEvent("on"+b,g)}:function(c,b,g){c["on"+b]=g};c(b,g,d)}return function(b,g,d){c(b,g,d)}}();try{i(e,"blur",b()),i(e,"focus",b()),i(e.document,"click",b()),i(e.document,"mousedown",b()),i(e.document,"mouseup",b()),c()}catch(n){}this.Ua=function(){return g}}function X(){return new W}"use strict";window.a=window.a||{};window.a.c=window.a.c||{};
window.a.c.v=function(){this.hc=function(){return function(){this.technique=this.Ya=this.audioVolume=this.error=this.viewabilityState=this.focus=this.$=this.objRight=this.objLeft=this.objBottom=this.objTop=this.clientHeight=this.clientWidth=this.id="";this.b=function(b){this.id=b.id;this.clientWidth=b.clientWidth;this.clientHeight=b.clientHeight;this.objTop=b.objTop;this.objBottom=b.objBottom;this.objLeft=b.objLeft;this.objRight=b.objRight;var c;c=b.percentViewable;if("unmeasurable"===b.beaconViewabilityState)c=
0;else if(b.technique&&"beacon"===b.technique)if("viewable"===b.beaconViewabilityState||"viewable"===b.viewabilityState){c=b.beacons;var g=0;if("viewable"==b.viewabilityState)for(var e=1;e<c.length;e++)if(c[e])g=100;else{g=50;break}c=g}else c=0;this.$=c;this.focus=b.focus;this.viewabilityState=b.viewabilityState;this.error=b.error;this.audioVolume=isNaN(b.volume)?p:b.volume;this.Ya="fullScreen"==b.displayState||"fullScreenInteractive"==b.displayState;this.technique=b.technique;return this}}}();this.J=
function(){return function(){this.l=this.m=this.z=this.Ea=this.G=this.Oa=this.la=this.f=this.ma=this.na=this.N=this.L=this.Va=this.ib=this.Ia=this.Pa=this.ua=this.Qa=this.ya=this.w=this.e=this.F=this.va=this.M=this.O=this.Ha=this.Ga=this.jb=this.kb=this.Fa=this.q=this.p=this.A=this.o=this.B=this.t=this.I=this.H="";this.Da=0;this.K=this.lb=this.Na=this.Hb=this.Ra=this.ja=this.ia=this.X=this.wa=this.j=this.u=this.i="";this.hb=function(b,c){""===this.i&&(this.i={});this.i[b]=c}}}();this.k={ec:1,Ub:2,
Kb:4,Sb:8,Mb:16,xb:32,wb:64,vb:128};this.Ta=function(b){switch(b){case "Can not find $ovv":return this.k.Ub;case "ExternalInterface not available":return this.k.Kb;case "Object not found":return this.k.Sb;case "Failed to determine viewport":return this.k.Mb;case "Ad in iFrame":return this.k.xb;case "adID does not exist":return this.k.wb;case "Wrong settings":return this.k.vb}return this.k.ec};this.r=function(){function b(){this.vit=this.dvp_vaisfcs=this.dvp_tch=this.dvp_isfcs=this.tstype=this.vjsver=
this.dvp_olc=this.dvp_vidNmms=this.dvp_openVVBuildVersion=this.dvp_openVVVersion=this.dvp_vidMinorVersion=this.avmax=this.avmin=this.isavmms=this.admutems=this.adexpms=this.adskippblems=this.narme=this.napr=this.strp=""}b.prototype.b=function(c){this.strp=c.o;this.napr=c.A;this.narme=c.p;this.adskippblems=c.q;this.adexpms=c.L;this.admutems=c.N;this.isavmms=c.z;this.avmin=c.m;this.avmax=c.l;this.dvp_vidMinorVersion=c.I;this.dvp_openVVVersion=c.t;this.dvp_openVVBuildVersion=c.B;this.dvp_vidNmms=c.dvp_vidNmms=
c.i&&c.i.dvp_vidNmms?c.i.dvp_vidNmms:"";this.dvp_olc=c.u;this.vjsver=c.H;this.tstype=c.F;this.dvp_isfcs=c.X;this.dvp_tch=c.ia;this.dvp_vaisfcs=c.ja;this.vit=c.K;return this};return b}();this.cb=function(b){return function(){b.prototype.constructor.call(this);this.b=function(c,g){b.prototype.b.call(this,c);this[g+"b0"]=c.Q;this[g+"b1"]=c.R;this[g+"b2"]=c.S;this[g+"b3"]=c.T;this[g+"b4"]=c.U;this[g+"b5"]=c.V;this[g+"napt"]=c.Z;this[g+"vpend"]=c.gc;this["is"+g+"ms"]=c.Ib;this[g+"ad"]=c.Ka;return this}}}(this.r);
this.bb=function(b){return function(){b.prototype.constructor.call(this);this.vct=this.dvp_ismms=this.isgmmims=this.isumms=this.isbmms=this.isbxdmms=this.isbxdms=this.isvidinsmems=this.isfmms=this.ismms=this.advisonl=this.adhgt=this.adwdth=this.adtovpy=this.adtovpx=this.vphgt=this.vpwdth="";this.b=function(c){b.prototype.b.call(this,c);this.vpwdth=c.kb;this.vphgt=c.jb;this.adtovpx=c.Ga;this.adtovpy=c.Ha;this.adwdth=c.O;this.adhgt=c.M;this.advisonl=c.va;this.ismms=c.e;this.isfmms=c.w;this.isvidinsmems=
c.Fa;this.isbxdms=c.na;this.isbxdmms=c.ma;this.isbmms=c.f;this.isumms=c.G;this.isgmmims=c.j;this.dvp_ismms=c.Na;this.vct=c.lb;return this}}}(this.r);this.xa=function(b){return function(){b.prototype.constructor.call(this);this.adhgt=this.adwdth=this.isvidinsmems=this.isfnmms=this.isnmms="";this.b=function(c){b.prototype.b.call(this,c);this.isnmms=c.ya;this.isfnmms=c.Qa;this.isvidinsmems=c.Fa;this.adwdth=c.O;this.adhgt=c.M;return this}}}(this.r);this.Bb=function(b){return function(){b.prototype.constructor.call(this);
this.isucms="";this.b=function(c){b.prototype.b.call(this,c);this.isucms=c.ib;return this}}}(this.r);this.Ab=function(b){return function(){b.prototype.constructor.call(this);this.isadskippedms="";this.b=function(c){b.prototype.b.call(this,c);this.isadskippedms=c.Ia;return this}}}(this.r);this.error=function(b){return function(){b.prototype.constructor.call(this);this.ishems="";this.b=function(c){b.prototype.b.call(this,c);this.ishems=c.Va;return this}}}(this.r);this.Lb=function(){return function(){this.vit=
this.dvp_openVVBuildVersion=this.dvp_openVVVersion=this.isbmms=this.isbxdmms=this.isbxdms=this.ismms=this.dvp_vidMinorVersion=this.vjsver="";this.b=function(b){this.vjsver=b.H;this.dvp_vidMinorVersion=b.I;this.ismms=b.e;this.isbxdms=b.na;this.isbxdmms=b.ma;this.isbmms=b.f;this.dvp_openVVVersion=b.t;this.dvp_openVVBuildVersion=b.B;this.vit=b.K;return this}}}();this.Wa=function(){return function(){this.dvp_ismms=this.dvp_isiabvms=this.dvp_ffovv=this.isumms=this.isuiabvms=this.isfmms=this.ismms=this.isfiabvms=
this.isiabvms="";this.b=function(b){this.isiabvms=b.ua;this.isfiabvms=b.Pa;this.ismms=b.e;this.isfmms=b.w;this.isuiabvms=b.Ea;this.isumms=b.G;this.dvp_ffovv=b.Ra;this.dvp_ismms=b.Na;this.dvp_isiabvms=b.Hb;return this}}}();this.Ma=function(){return function(){this.isgmpims=this.isgmmims=this.isumms=this.isbmms=this.isfmms=this.ismms=this.isfbvms=this.isbvms="";this.b=function(b){this.isbvms=b.la;this.isfbvms=b.Oa;this.ismms=b.e;this.isfmms=b.w;this.isbmms=b.f;this.isumms=b.G;this.isgmmims=b.j;this.isgmpims=
b.wa;return this}}}();this.Qb=function(b){var c="";switch(b){case "AdVideoFirstQuartile":c="q1";break;case "AdVideoMidpoint":c="q2";break;case "AdVideoThirdQuartile":c="q3";break;case "AdVideoComplete":c="q4"}return c};this.tb={nc:0,nb:1,qb:2,lc:4,oc:8,pc:16,ic:32,mb:64,mc:128,pb:256};this.ub={qc:0,sb:1,ob:2}};window.a=window.a||{};window.a.c=window.a.c||{};window.a.c.g=window.a.c.g||{};
window.a.c.g.xc=function(b){this.aa=p;this.h={};this.Y=b;this.Ca=function(c){this.Y=c};this.pa=function(c,b,e){if(this.Y){e&&(this.h[c]=b);var d,c="<tr class='cellData1'><td>"+c+"</td>";for(d in b)b.hasOwnProperty(d)&&"function"!==typeof b[d]&&(e=isNaN(b[d])?"":b[d],c=this.aa===p||b[d]!==this.aa[d]?c+'<td class="cellData0 ">'+e+"</td>":c+"<td>"+e+"</td>");var c=c+"</tr>",i;for(i in this.h){c=c+"<tr class='cellData1'><td>"+i+"</td>";for(d in this.h[i])this.h[i].hasOwnProperty(d)&&"function"!==typeof this.h[i][d]&&
(e=isNaN(this.h[i][d])?"":this.h[i][d],c=c+"<td>"+e+"</td>");c+="</tr>"}d="<div class='bottomLeft'><table class='dvTable'><tr><th>Impression ID</th><th>0%     </th><th>1%-24% </th><th>25%-49%</th><th>50%-74%</th><th>75%-99%</th><th>100%   </th><th>N/A</th></tr>{TR_TD}<tfoot class='tfoot'><td colspan=14 height=15></td></tfoot></table></div>".replace("{TR_TD}",c);i=window.top.document.getElementById("dvBucketLogger");i||(i=window.top.document.createElement("div"),i.id="dvBucketLogger",window.top.document.body.insertBefore(i,
p));i.innerHTML=d;this.aa=b}};this.qa=function(c,b){if(this.Y){var e;e="";for(var d in c)c.hasOwnProperty(d)&&"function"!==typeof c[d]&&(e=e+"<tr class='cellData1'><td>"+d+" </td><td>"+c[d]+"</td></tr>");e=("<div class='bottomRight'><table class = 'dvTable'> <caption>"+b+"</caption><tr> <th>Param name</th><th>Value</th> </tr>{TR_TD}<tfoot class='tfoot'><td colspan=14 height=15></td></tfoot></table > </div>").replace("{TR_TD}",e);d=window.top.document.getElementById("eventCallLog");d||(d=window.top.document.createElement("div"),
d.id="eventCallLog",window.top.document.body.insertBefore(d,p));d.innerHTML=e}};this.P=function(c){if(this.Y){var b=document.getElementById("log");b&&(b.innerHTML=c+"<br>"+b.innerHTML)}}};window.a=window.a||{};
window.a.Eb=function(){var b={W:6,ra:25},b=b||{W:6,ra:25},c=Array(b.W),g=l,e=l;this.cc=function(d,g){var e;0>d?e=0:100<d?e=b.W-1:(e=Math.floor(d/b.ra),0<d%b.ra?e++:0<d&&e++);isNaN(c[e])&&(c[e]=0);c[e]+=g};this.Pb=function(){return e};this.bc=function(c,b){isNaN(e)&&(e=0);0<c&&(e+=b)};this.Sa=function(){var b={};b.Q=c[0]?c[0]:"";b.R=c[1]?c[1]:"";b.S=c[2]?c[2]:"";b.T=c[3]?c[3]:"";b.U=c[4]?c[4]:"";b.V=c[5]?c[5]:"";b.Z=g?g:"";return b};this.clear=function(){c=Array(b.W);g=e=l};this.dc=function(c){isNaN(g)&&
(g=0);g+=c}};window.a=window.a||{};
window.a.yb=function(){this.Nb=function(){for(var b=window.parent.document.documentElement.clientHeight?window.parent.document.documentElement:window.parent.document.body,c=window;c.parent!=c.top;)c=c.parent;for(var g=c.parent.document.getElementsByTagName("iframe"),e=g.length,d=0;d<e;d++)if(g[d].contentWindow===c){b=g[d];break}return b};this.Ob=function(){var b=window,c;try{var g;for(g=0;10>g;g++)b=b.parent,c=b.document.documentElement.clientHeight?b.document.documentElement:b.document.body}catch(e){}return c}};
window.a=window.a||{};window.a.c=window.a.c||{};window.a.c.g=window.a.c.g||{};
window.a.c.g.console=function(b){this.aa=p;this.h={};this.n=b;this.s={Za:1,ab:2,$a:4};this.Ca=function(c){this.n=c};this.pa=function(c,b){if(this.n&&(this.n&this.s.Za)===this.s.Za){var e="",d;for(d in b)b.hasOwnProperty(d)&&"function"!==typeof b[d]&&(e=e+" |"+d+":"+(isNaN(b[d])?"":b[d]));console.log("Buckets for "+c+", "+e)}};this.qa=function(c,b){if(this.n&&(this.n&this.s.ab)===this.s.ab){var e=b+" call: ",d;for(d in c)c.hasOwnProperty(d)&&"function"!==typeof c[d]&&(e=e+" | "+d+":"+c[d]);console.log("Event data: "+
e)}};this.P=function(c){this.n&&(this.n&this.s.$a)===this.s.$a&&console.log("log entry: "+c)}};window.a.c.Zb={kc:0,ka:1};
window.a.c.D=function(){function b(){function b(c,e){c.G=e;n?(c.w=e,c.e=0,c.va=t):c.e=e}this.ka={C:function(b){b.e=c();b.G=b.e;b=(new h.bb).b(b);e("VideoImpressionViewabilityMeasured");i("VideoImpressionViewabilityMeasured");g(b)},fa:function(b){var C=c();b.ua=C;b.Ea=C;b.e||this.C(b);b=(new h.Wa).b(b);g(b);d("Impression viewed",b);e("VideoImpressionViewableIAB");i("VideoImpressionViewableIAB")},ea:function(b){b.ya=c();b=(new h.xa).b(b);g(b);e("VideoImpressionViewabilityNotMeasured")},da:function(b){var d=
c();b.f||(b.f=d,e("BillableMeasuredImpression"));b.la=d;e("BillableViewedImpression");x||(b.j||(b.j=d,e("GroupMMeasuredImpression")),b.wa=d,e("GroupMPassedImpression"));b=(new h.Ma).b(b);g(b)},ca:function(b){b.e=c();b.f=b.e;e("BillableMeasuredImpression");x||(b.j=b.e,e("GroupMMeasuredImpression"))},ha:A(),ba:A(),ga:function(b,c){var e=(new h.cb).b(b,c);g(e);d(b.eventName,e,b)}};this.rb={C:function(o){var d=c();b(o,d);e("VideoImpressionViewabilityMeasured");i("VideoImpressionViewabilityMeasured");
o=(new h.bb).b(o);g(o)},fa:function(o){var v=c();!o.e&&!o.w&&(b(o,v),e("VideoImpressionViewabilityMeasured"),i("VideoImpressionViewabilityMeasured"));n?o.Pa=v:(e("VideoImpressionViewableIAB"),i("VideoImpressionViewableIAB"),o.ua=v);o.Ea=v;d("Impression viewed",j);var j=(new h.Wa).b(o);g(j)},ea:function(b){n?b.Qa=c():b.ya=c();b=(new h.xa).b(b);g(b);e("VideoImpressionViewabilityNotMeasured")},da:function(b){var d=c();n?(b.Oa=d,b.f||(b.f=0,e("BillableMeasuredImpression"))):(b.f||(b.f=d,e("BillableMeasuredImpression")),
b.j||(b.j=d,e("GroupMMeasuredImpression")),b.la=d,b.wa=d,e("BillableViewedImpression"),e("GroupMPassedImpression"));b=(new h.Ma).b(b);g(b)},ca:function(b){b.e=n?0:c();b.f=b.e;e("BillableMeasuredImpression");n||(b.j=b.e,e("GroupMMeasuredImpression"))},ha:function(b){b.e=0;b.na=0;b.ma=0;b=(new h.Lb).b(b);g(b)},ba:function(b){b.f=0},ga:function(b,c){n&&(b.Z=0,b.Q=0,b.R=0,b.S=0,b.T=0,b.U=0,b.V=0,b.Ka=0);var e=(new h.cb).b(b,c);g(e);d(b.eventName,e,b)}}}function c(){return $dv.tags[r].getTimeDiff()}function g(b){if($dv.tags[r].gb!==
m){var c={},e;for(e in b)""!==b[e]&&(b[e]!==p&&b[e]!==l)&&(c[e]=b[e]);$dv.registerEventCall(r,c,0)}}function e(b){$dv&&(r&&b)&&$dv.pubSub.publish(b,r)}function d(b,c,e){e&&j.pa(r,e);j.qa(c,b)}function i(b){var c=window.$ovv||parent.$ovv;if(q&&c){var e=$dv.tags[$uid].adID||$dv.tags[$uid].adid,c=c.dvjscb[e];a:{for(var d=parent.document.getElementsByTagName("embed"),f=0;f<d.length;f++)if(d[f][e]){e=d[f];break a}d=parent.document.getElementsByTagName("object");for(f=0;f<d.length;f++)if(d[f][e]){e=d[f];
break a}e=l}if(e&&c)e[c](b)}}var n,x,y,r,j,h,k,u,q,D=window.a.c.Zb;this.Rb=function(c){y=c.ac;r=c.uid;j=c.g;h=c.v;q=c.Ja;u=new b;n=c.Xa;x=c.La;switch(y){case D.ka:k=u.ka;break;default:k=u.rb}};this.C=function(b){k.C(b)};this.ba=function(b){k.ba(b)};this.fa=function(b){k.fa(b)};this.ea=function(b){k.ea(b)};this.ha=function(b){k.ha(b)};this.Xb=function(b){b.ib=c();b=(new h.Bb).b(b);g(b);d("Ad user close",b)};this.Wb=function(b){var e=c();b.q||(b.q=e);b.Ia=e;b=(new h.Ab).b(b);g(b);d("Ad skipped",b)};
this.Yb=function(b){b.Va=c();b=(new h.error).b(b);g(b);j.qa(b,"Error")};this.ga=function(b,c){k.ga(b,c)};this.ca=function(b){k.ca(b)};this.da=function(b){k.da(b)};this.Vb=function(b){b.Fa=c();e("VideoImpressionServed")}};window.a=window.a||{};window.a.c=window.a.c||{};
window.a.c.eb=function(b,c){function g(b,c){if($dv.tags[f.uid].gb!==m){var e={},d;for(d in c)""!==c[d]&&(c[d]!==p&&c[d]!==l)&&(e[d]=c[d]);$dv.registerEventCall(b,e,0)}}function e(b){var b=(b||"").toString().toLowerCase(),c=B.tb;switch(b){case "geometry":case "css_invisibility":case "dom_obscuring":return c.nb;case "beacon":return $dv.CommonData.BrowserId===$dv.Enums.BrowserId.jc?c.qb:c.mb;case "iphone_override":return c.pb}}function d(b){var c;switch(f.F){case $dv.Enums.TrafficScenario.CrossDomain:c=
v.Ob();break;case $dv.Enums.TrafficScenario.SameDomain:c=v.Nb();break;case $dv.Enums.TrafficScenario.OnPage:b&&(f.O=b.objRight-b.objLeft,f.M=b.objBottom-b.objTop)}c&&(f.O=c.clientWidth,f.M=c.clientHeight)}function i(b,c){d(c);f.lb=e(c.technique);f.kb=c.clientWidth;f.jb=c.clientHeight;f.Ga=c.objLeft;f.Ha=c.objTop;f.va=50<=f.o;Z(f);w.C(f);O=m;i=A()}function n(b,c){c&&(f.A=c,f.p|=B.Ta(c));d();w.ea(f);O=m;n=A()}function x(b){try{f.A=b+(b.message?"; error.message: "+b.message:""),f.p|=B.Ta(b),D<C&&(D++,
w.Yb(f))}catch(c){$dv.registerEventCall($uid||-1,{napr:"Error trying to send error event. "+c,narme:1,ishems:1},0)}}function y(b,c){f.Ra=c;S=m;w.fa(f);y=A()}function r(b){return b.Ya?100:P(b)==t?0:b.$}function j(b){Array.prototype.indexOf||(Array.prototype.indexOf=function(b,c){var f=this.length>>>0,e=Number(c)||0,e=0>e?Math.ceil(e):Math.floor(e);for(0>e&&(e+=f);e<f;e++)if(e in this&&this[e]===b)return e;return-1});b=$.indexOf(b);-1<b&&0==F[b]&&(F[b]=1,g(f.uid,{dvp_ovve:F.join("")}))}function h(b){$dv&&
(f.uid&&b)&&$dv.pubSub.publish(b,f.uid)}function k(b,c,e){e.subscribe(b,c,function(b,c){try{window!=l&&window!=p&&window.dv_config&&window.dv_config.debug?E.Ca(window.dv_config.debug):E.Ca(0);parent&&parent.DVViewableDetect&&parent.DVViewableDetect(c.eventName,c.ovvArgs);var d=(new B.hc).b(c.ovvArgs.ovvData),g=e.interval||200;T=2E3/g;d.wc=$dv.CommonData.Scenario;var u=c.eventName;E.P("Received event: "+u);j(u);switch(u){case "OVVLog":try{I++;var h=d.technique,k=d.focus;J[h]=J[h]?J[h]+1:1;K[k]=K[k]?
K[k]+1:1;var D=U.Ua();L[D]=L[D]?L[D]+1:1}catch(fa){}var v=$dv.tags[f.uid].getTimeDiff();if(!V||Q)E.P("Ignore interval data.");else{var C,h=m;d===p||d.error||d.$===p?h=t:"unmeasurable"===d.viewabilityState&&(G++,h=t);h||f.hb("dvp_vidNap",d.$);C=h;var z="not_ready"!=d.viewabilityState,h=p;if(C){if(z){if(f.o===p||""===f.o)f.o=r(d);h=r(d);o.cc(h,g);E.P("setBucket: "+h+"%");f.Da+=g;d.audioVolume!==p&&0<=d.audioVolume&&(o.bc(d.audioVolume,g),f.z=f.z||v,d.audioVolume=Math.ceil(100*d.audioVolume),""===f.m||
""===f.l?(f.m=d.audioVolume,f.l=d.audioVolume):(f.m=Math.min(f.m,d.audioVolume),f.l=Math.max(f.l,d.audioVolume)));R=50<=h?++R:0;!S&&R>=T&&y(d,0);aa(z,h,d,g)}}else(0==G||1<G)&&o.dc(g);!O&&z&&(C?i(v,d):(0==G||1<G)&&n(v,d.error));E.pa(f.uid,o.Sa())}break;case "OVVImpression":y(d,1);break;case "OVVImpressionUnmeasurable":var F=$dv.tags[f.uid].getTimeDiff();f.hb("dvp_vidNmms",F);n(F,d.xa);break;case "AdImpression":V=m;w.Vb(f);break;case "AdVideoFirstQuartile":case "AdVideoMidpoint":case "AdVideoThirdQuartile":case "AdVideoComplete":var H=
o.Sa(),Y=o.Pb();o.clear();var s=B.Qb(u);f[s+"Buckets"]=H;f[s+"AudibleDuration"]=Y;f[s+"ViewPercentageAtEnd"]=r(d);f[s+"EndedMs"]=$dv.tags[f.uid].getTimeDiff();try{if($dv&&(2==$dv.CommonData.BrowserId||3==$dv.CommonData.BrowserId))f.ia=JSON.stringify(J),f.X=JSON.stringify(K),f.ja=JSON.stringify(L);f.u=f.u?f.u+" "+I:I}catch(P){}I=0;w.ga({uid:f.uid,H:f.H,I:f.I,t:f.t,B:f.B,F:f.F,o:f.o,p:f.p,q:f.q,L:f.L,N:f.N,gc:f[s+"ViewPercentageAtEnd"],Ib:f[s+"EndedMs"],A:f.A,Z:f[s+"Buckets"].Z,Q:f[s+"Buckets"].Q,R:f[s+
"Buckets"].R,S:f[s+"Buckets"].S,T:f[s+"Buckets"].T,U:f[s+"Buckets"].U,V:f[s+"Buckets"].V,Ka:f[s+"AudibleDuration"],z:f.z,l:f.l,m:f.m,u:f.u,ia:f.ia,X:f.X,i:f.i,ja:f.ja,K:f.K},s);break;case "AdExpandedChange":f.L=$dv.tags[f.uid].getTimeDiff();break;case "AdSkippableStateChange":f.q=$dv.tags[f.uid].getTimeDiff();break;case "AdSkipped":w.Wb(f);break;case "AdUserClose":w.Xb(f);break;case "AdVolumeChange":0==d.audioVolume&&(f.N=$dv.tags[f.uid].getTimeDiff());break;case "AdPaused":Q=m;break;case "AdPlaying":Q=
t;break;case "AdStopped":$dv.tags[f.uid].gb=m}ba(u,d,g)}catch(M){try{x(M)}catch(N){q.debug&&console.log("ovv event error: "+N)}}},m)}function u(b){"undefined"!=typeof $dv.tags[b].AVO&&"undefined"!=typeof $dv.tags[b].AVO.fcs&&(M=$dv.tags[$uid].AVO.fcs);P=M?U.Ua:function(b){return b.focus}}var q=b.fb,D=0,C=q?q.rc||10:10,o=b.Fb,v=b.zb,B=b.v,f=new B.J,E=b.g,w=b.$b,V=t,Q=t,O=t,G=0,I=0,J={},K={},L={},R=0,S=t,T=10,M=t,U=b.Db,P,H,z,N=t,$="AdImpression AdStarted OVVLog AdVideoFirstQuartile AdVideoMidpoint AdVideoThirdQuartile AdVideoComplete AdStopped".split(" "),
F=[0,0,0,0,0,0,0,0];this.start=function(){try{w.Rb({v:B,uid:$uid,Xa:q.irtf,ac:q.rpv,La:q.La,Ja:q.Ja,g:E});f.H=34;f.I=0;f.uid=q?q.uid||$uid:$uid;f.F=$dv.CommonData.Scenario;u(f.uid);var b=p;try{if(b=window.$ovv||parent.$ovv||window.$dvvideo||parent.$dvvideo,!b||!(b.subscribe&&"function"===typeof b.subscribe))b=p}catch(c){}z=b;if(!z)throw"Can not find $ovv";f.t=z.releaseVersion||z.version;var e=f.t,e=(e||"").toString().toLowerCase(),d=B.ub;f.K="html5"===e?d.ob:d.sb;f.B=z.buildVersion;H=q.adID||$dv.tags[f.uid].adID||
$dv.tags[f.uid].adid;if(!H)throw"adID does not exist";q.irtf&&(f.irtf=q.irtf,N=m,ca(f),w.ha(f));k(q.fc,H,z);da()}catch(g){x(g)}};var aa=b.d&&b.d.ta&&"function"===typeof b.d.ta?b.d.ta:A(),Z=b.d&&b.d.Aa&&"function"===typeof b.d.Aa?b.d.Aa:A(),ca=b.d&&b.d.za&&"function"===typeof b.d.za?b.d.za:A(),ba=b.d&&b.d.sa&&"function"===typeof b.d.sa?b.d.sa:A(),da=b.d&&b.d.Ba&&"function"===typeof b.d.Ba?b.d.Ba:A();c&&(c.Jb=B,c.J=f,c.D=w,c.fireEvent=g,c.Tb=x,c.vc=h,c.Xa=function(){return N})};
window.a.c.oa=window.a.c.oa||{};
window.a.c.oa=function(b){function c(b){var c=0;"object"===typeof b.fullyViewedConsecutiveQuartiles?c=1:"number"===typeof b.adDurationPercent&&(c=2);return c}function g(){k.D.da(k.J);g=A()}function e(b){for(var c in b)if(d&i[b[c]])return m;return t}this.Cb=window.a.c.eb;var d=0,i={q1:1,q2:2,q3:4,q4:8},n=0,x=t,y=0,r=0,j=b.fb.videoBillable,h=m,k={Jb:p,J:p,fireEvent:p};b.d=b.d||{};b.d.ta=function(b,c,d,i){if(2==r){if(b&&c>=j.adView&&j.hasVolume&&0<d.audioVolume||b&&c>=j.adView&&j.hasVolume&&-1==d.audioVolume||
b&&c>=j.adView&&j.hasVolume&&d.audioVolume==p||b&&c>=j.adView&&j.hasVolume==t)y+=i;x&&y>=n*j.adDurationPercent&&g()}else if(1==r)if(e(j.fullyViewedConsecutiveQuartiles)){if(b&&(t==c>=j.adView||j.hasVolume&&0===d.audioVolume))h=t}else e(["q1","q2","q3","q4"])&&h&&g()};b.d.Aa=function(b){0!=c(j)&&k.D.ca(b)};b.d.za=function(b){0!=c(j)&&k.D.ba(b)};b.d.sa=function(b,c){switch(b){case "AdImpression":d=1;break;case "AdVideoFirstQuartile":d=2;break;case "AdVideoMidpoint":d=4;n=2*k.J.Da;x=m;break;case "AdVideoThirdQuartile":d=
8;break;case "AdVideoComplete":d=0;break;case "AdVolumeChange":j.hasVolume&&0===c.audioVolume&&(h=t)}};b.d.Ba=function(){"number"===typeof j.adView&&("object"===typeof j.fullyViewedConsecutiveQuartiles&&0<j.fullyViewedConsecutiveQuartiles.length||"number"===typeof j.adDurationPercent)&&"boolean"==typeof j.hasVolume&&"boolean"==typeof j.isAutoInitiated||k.Tb("Wrong settings");r=c(j)};this.Cb(b,k)};
try{videoCallback(function(b){b.fc="OVVLog OVVImpression OVVImpressionUnmeasurable AdSkippableStateChange AdSkipped AdUserClose AdStarted AdImpression AdVideoStart AdStopped AdVideoFirstQuartile AdVideoMidpoint AdVideoThirdQuartile AdVideoComplete AdExpandedChange AdPaused AdPlaying AdVolumeChange".split(" ");var c=window.a.c.eb;if(window.Gb||$dv.tags[$uid].videoBillable||b.videoBillable)c=window.a.c.oa,b.videoBillable=window.Gb||$dv.tags[$uid].videoBillable||b.videoBillable;b.rpv=$dv.tags[$uid].AVO?
$dv.tags[$uid].AVO.rpv:l;var g=window!=l&&window!=p&&window.dv_config&&window.dv_config.g?window.dv_config.g:new window.a.c.g.console(b?b.debug:0);(new c({fb:b,Db:new X,Fb:new window.a.Eb,zb:new window.a.yb,v:new window.a.c.v,g:g,$b:new window.a.c.D})).start()})}catch(ea){$dv.registerEventCall($uid||-1,{napr:"Error while staring video tag. "+ea,narme:1,ishems:1},0)};})();
