(function(){
var isIE = window.navigator.userAgent.indexOf("MSIE ") > 0;
var ifr = "<"+"iframe id=\"cto_iframe_b7b4fcf359\" frameBorder=\"0\" allowtransparency=\"true\" hspace=\"0\" marginwidth=\"0\" marginheight=\"0\" scrolling=\"no\" vspace=\"0\" width=\"728px\" height=\"90px\"\n";
if(isIE && document.domain !== window.location.hostname) {
ifr += " src=\"javascript:'<script>window.onload=function(){document.write(\\\'<script>document.domain = &quot;"+document.domain + "&quot;;<\\\\/script>\\\');document.close();};</script>'\"";
}
ifr += "><"+"/iframe>\n";
document.write(ifr);
var ifc = "\n";
ifc += "<"+"!DOCTYPE html>\n";
ifc += "<"+"html>\n";
ifc += "  <"+"head>\n";
ifc += "    <"+"meta name=\"format-detection\" content=\"telephone=no\"><"+"meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n";
ifc += "  <"+"/head>\n";
ifc += "  <"+"body><"+"div id=\'cto_banner_content\'><"+"style>\n";
ifc += "#cto_products .cto_product .imgholder{ text-align : center; background : #ffffff; float : left; margin-right : 7px; width : 71px; height : 71px;\n";
ifc += "} #cto_products .cto_product .imgholder img{ border : none; max-width : 71px; max-height : 71px; *width : expression(this.width >= this.height ? \"71px\" : \"auto\"); *height : expression(this.width <"+" this.height ? \"71px\" : \"auto\");\n";
ifc += "} #cto_products .cto_product .title{ overflow : hidden; color : #016090; font-size : 14px; height : 18px; line-height : 16px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product .desc{ overflow : hidden; color : #646464; font-size : 12px; height : 30px; line-height : 14px;\n";
ifc += "} #cto_products .cto_product .priceDesc{ color : #FF9900; font-size : 16px; height : 24px; line-height : 20px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product .priceDesc .origPrice{ color : #999; font-size : 13px; height : 18px; line-height : 16px; font-weight : normal;\n";
ifc += "} #cto_products .cto_product .details{ float : left; width : 162px;\n";
ifc += "} #cto_products .cto_product *{ *cursor : pointer;\n";
ifc += "} #cto_products .cto_product a{ color : black; text-decoration : none;\n";
ifc += "} #cto_bannerContent{ width : 728px; height : 90px; background : #ffffff; position : relative; font-family : Arial,sans-serif; font-size : 0; overflow : hidden;\n";
ifc += "} #cto_products{ height : 73px; width : 728px; overflow : hidden;\n";
ifc += "} #cto_products .cto_product{ width : 240px; height : 71px; float : left; text-align : left; overflow : hidden; vertical-align : top; zoom : 1; position : relative; *zoom : 1; *display : inline; margin : 1px 1px 1px 1px;\n";
ifc += "} #cto_products .cto_product:hover{ background : #eeeeee;\n";
ifc += "} #cto_bannerContent .footer{ height : 17px; line-height : 16px; position : relative; text-align : left;\n";
ifc += "} #cto_bannerContent .adUrl{ font-size : 11px; color : #808080; text-decoration : none; cursor : pointer; *cursor : pointer; zoom : 1; vertical-align : top; margin-right : 4px; display : inline-block; *display : inline; margin-left : 4px; line-height : 17px;\n";
ifc += "} #cto_bannerContent .adUrl:hover{ text-decoration : underline;\n";
ifc += "} #cto_bannerContent .legal{ text-overflow : ellipsis; white-space : nowrap; overflow : hidden; font-size : 11px; color : #808080; display : inline-block; *display : inline; height : 16px; width : 242.66666666666666px;\n";
ifc += "} #cto_bannerContent .legalover{ position : absolute; left : 1px; box-sizing : border-box; font-size : 11px; color : #808080; text-decoration : none; display : block; zoom : 1; padding : 4px; background : #eee; opacity : 0.95; filter : alpha(opacity=95); visibility : hidden; line-height : 12px; width : 728px; bottom : 1px;\n";
ifc += "} <"+"/style>\n";
ifc += "<"+"div id=\"cto_bannerContent\">\n";
ifc += "<"+"div id=\"cto_products\">\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=9YOInHxzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOGw3aG8rMS9VN1F6Qkg0dDJmSzlpTndvMldkTCtxajZQSDcyb0ptemhNUzkvR01uWklMb1dMVGpEZHUxYW1Ra3dGVk5UTXB3dDc1K0ljZUR4ZDZMQU9FSno3VWtVMmxYQ016R0xteE90V1dpT2pUbDZubURsajdpSXptZ29Ramx3OERoaDM4SDg5Mmhlc1AyVWFhWHUrZz18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fround-handle-tote-hat-attack%2Fvp%2Fv%3D1%2F1538225602.htm%3Fextid%3DDP_Criteo_US_MV_1538225602%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1538225602&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fhatta%2Fhatta3004711611%2Fhatta3004711611_q1_1-0._QL90_UX336_.jpg&w=400&s=Dtkz0gHvveFo-4gMIx8b85MN\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Hat Attack Round Handle Tote<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A structured Hat Attack tote in chunky woven straw. 3 tassels with metallic trim hang from the top handles. Unlined interior. Fabric: Basket weave. Weight: 27oz / 0.77kg. Imported, China. Measurements Height: 11.75in / 30cm Length: 16.25in / 41cm Depth: 6in / 15cm Handle drop: 6in / 15cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=s5GFy3xzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOGpQM2RKZVk0RFJyc1d5K3lpckdSRjlaRmJmcVphZEZSS0VpYThDbXB5WmNCNzVLYUdWOXZ0QWlNcEM5dkNuTU1SK0VIZzdJNnJQbW5lTkl5ejRpeThKOGJLa2NMQVpHQ3NTQW1JMEEveEtOWWwwWGZlQmJyYkFNZEZRbW5SL1ZPQT09fA%3D%3D&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fdance-dress-free-people%2Fvp%2Fv%3D1%2F1593354211.htm%3Fextid%3DDP_Criteo_US_MV_1593354211%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1593354211&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ffreep%2Ffreep4299413203%2Ffreep4299413203_q1_1-0._QL90_UX336_.jpg&w=400&s=2cnKuP07DmshLmziG_v0ba8Y\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Free People Dance With Me Dress<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A ruched elastic center seam shapes the cutout bodice on this swingy jersey Free People dress. The wide neckline and fitted cap sleeves offer a ballet-inspired feel. Full, paneled skirt. Unlined. Fabric: Jersey. 55% cotton/37% polyester/8% spandex. Wash cold. Imported, China. Measurements Length: 47.25in / 120cm, from shoulder Measurements from size S. Available sizes: L,M,S,XS<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=Hmhj63xzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOGt2QzhvaENJUGN1L2NSY2hoMXg1enJJWVoxS25BVlYrWjFDKzdvYVVQaEVpT1RtYnU3WFhTMkJQVXlSQ3owNjFiM1B6UFMzMUxVZTY0YzIzcUJSdnNLNEFORVN4RDVQMm5aR2ExSTFjZ29MQ2Z6YVZNQ29uMGJMQStyV1hKRWJUTWplUkZkZDRsN1J5RHIxZW9hZjNrTT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fsimonia-blouse-diane-von-furstenberg%2Fvp%2Fv%3D1%2F1592128989.htm%3Fextid%3DDP_Criteo_US_MV_1592128989%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1592128989&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fdiavf%2Fdiavf4383787591%2Fdiavf4383787591_q1_1-0._QL90_UX336_.jpg&w=400&s=PNWJ1UvAuh1iQUCFwpCvLXaC\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Diane von Furstenberg Simonia Blouse<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">An airy silk DVF blouse in a floral print. Ties close the keyhole, and frayed ruffles trim the front. Sheer sleeves with flared cuffs. Lined. Fabric: Crinkled silk chiffon. Shell: 100% silk. Lining: 100% polyester. Dry clean. Imported, China. Measurements Length: 23.5in / 60cm, from shoulder Measurements from size 4. Available sizes: 10<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=bMaTXHxzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOGcwNDB3MGZ0TzBYZU9OWUNFeHEzZi9KRTBYOEJrRnpNcS9SZ1RDcFc2aXJFYmxpYXBnM1NnZjVPZEhsLzdQNnFEVGtDRjdPTSsrMkh4ZThZUzNsYWt0YlY0S25BbTBQdEozcUZpSkg4RUdVU1diUytQUjBtVkhvblprcXFYME1YcjU0UjVJaUwzSVU2QWlmSkc4enJuTT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fkanken-backpack-fjallraven%2Fvp%2Fv%3D1%2F1531461443.htm%3Fextid%3DDP_Criteo_US_MV_1531461443%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1531461443&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ffjall%2Ffjall3004157661%2Ffjall3004157661_q1_1-1._QL90_UX336_.jpg&w=400&s=WORGwhKRs_lY1eL4k-Atx2aj\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Fjallraven Kanken Backpack<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A sturdy Fj&#228;llr&#228;ven backpack, detailed with a front logo patch and zip pocket. Patch side pockets add versatility. A two-way zip secures the single-pocket interior. Adjustable shoulder straps. Fabric: Rigid technical weave. Weight: 11oz / 0.31kg. Imported, China. Measurements Height: 13.75in / 35cm Length: 11in / 28cm Depth: 4.75in / 12cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=lMrk0nxzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOHNEYTE3UjhlWTU2QXVWV0lHb2xYNHFTUWVlVko5TktadzRQN2k5UmVBYk9FMVQxZUs3UTdWWWRZdGZmSDcxZTJJM2JlRVlmSFM1Z3UwNjZaNnM5Y2hVYXZ2dFplUWp3RndZUlRjK1FVVlpQYWZ0VzRjeXM5QlVPK3BsS3BzOERYL3htRmx5QnJoUFE0V0tjUWJheTVNST18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fmini-kanken-backpack-fjallraven%2Fvp%2Fv%3D1%2F1581696096.htm%3Fextid%3DDP_Criteo_US_MV_1581696096%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1581696096&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ffjall%2Ffjall3001615937%2Ffjall3001615937_q1_1-1._QL90_UX336_.jpg&w=400&s=rc6iPrNlyU5hm-JZHRlhxumO\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Fjallraven Kanken Mini Backpack<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A sturdy Fj&#228;llr&#228;ven backpack, detailed with a reflective logo patch and front zip pocket. Patch side pockets offer easy access to essentials, and a 2-way, wraparound zip secures the top. A removable foam panel adds extra protection to the deep, interior patch pocket. Double handles and adjustable shoulder straps. Weight: 8oz / 0.22kg. Imported, Vietnam. MEASUREMENTS Height: 11in / 28cm Length: 8in / 20.5cm Depth: 3in / 7.5cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=A5jEwXxzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOGtmdWxHN0dFSDFGSGtoenNEQVhFOWVHRmFqZVRTbFdnNVJPeS93N2xINkRSK0FodDhRaDkwUU4wZ3Q0M1hhL29acEdQMkJrYmRyUFdRcFZudUpxRjRINkh6RGNlSlI4ak1FaldkeGRHRHBzN01OQjlXa0lHcWJnUFZyUUU0M3FlUVcwZFlnZ1NUamtWMWJTdzdjRFZLUT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fsolitaire-ring-shashi%2Fvp%2Fv%3D1%2F1537441022.htm%3Fextid%3DDP_Criteo_US_MV_1537441022%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1537441022&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fshash%2Fshash4056114583%2Fshash4056114583_q1_1-0._QL90_UX336_.jpg&w=400&s=ZSSBbrATJZgNSJY-phWUJA6C\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Shashi Solitaire Ring<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A bezel-set cubic zirconia brings a refined look to this thin, gold-vermeil Shashi ring. 18k gold vermeil. Made in the USA. Size &amp; Fit. Available sizes: 7,8<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=lXuZV3xzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOGhkb25DajBQOHBzUG91UWFDRUpWWFE2d2VJMHBLM0EzUFRjWEdUaUJHRTFrR0IwVXlQa2xKSW9TS0RvemRadDJpOEUySXpxSGx2QVpLenFBYzk3U1lTSjQyczJQSUJXaWVoYk9wZHFjUFVhZHhBbEVrMWZUQ1B5dUJPWlhnR251eTNuYmhoN0VicEI5Q3NQTXdqMTVYZz18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Funlined-saddle-bag-rebecca-minkoff%2Fvp%2Fv%3D1%2F1528874870.htm%3Fextid%3DDP_Criteo_US_MV_1528874870%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1528874870&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Frmink%2Frmink4398010943%2Frmink4398010943_q1_1-1._QL90_UX336_.jpg&w=400&s=U_QMsCeDQEW0ujP1DeDqdZVm\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Rebecca Minkoff Unlined Saddle Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A rounded Rebecca Minkoff cross-body bag in full-grain leather. Polished studs accent the magnetic top flap, which covers a slim front pocket and an unlined interior compartment. Optional, adjustable shoulder strap. Leather: Cowhide. Weight: 26oz / 0.74kg. Imported, China. Measurements Height: 6.25in / 16cm Length: 9in / 23cm Depth: 3.25in / 8cm Strap drop: 22.5in / 57cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=lwMAT3xzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOGtqSHptTm41alNNM2xOaFowY0diS3ZBMWI4Tjg2Qys3VnNSMWs5bmlOeU5aV0sxb09ROXJXNGJuaWtEVHVMajFvMmxFcjB0UzBvRHpyejBzeUNHY2JtWnBDc1hzMTJlMnM3anFBWjh6Wklsb2p1dDd0NkdMbkZ1MGhCR2tmbENLTGwzOWVjVmZrNHhZakRnRXFndU1oQT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fmicro-crossbody-bag-elizabeth-james%2Fvp%2Fv%3D1%2F1525464394.htm%3Fextid%3DDP_Criteo_US_MV_1525464394%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1525464394&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Felija%2Felija4208212867%2Felija4208212867_q1_1-0._QL90_UX336_.jpg&w=400&s=5mnVf083s7xYsEbJkG0BlsEw\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Elizabeth and James Micro Cross Body Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A petite, pebbled-leather Elizabeth and James cross-body bag provides easy access to daily essentials with 2 exterior pockets. The zip top opens to a lined interior with 1 card pocket. Adjustable strap. Dust bag included. Leather: Lambskin. Weight: 12oz / 0.34kg. Imported, China. Measurements Height: 6in / 15cm Length: 8.25in / 21cm Depth: 1.5in / 4cm Strap drop: 21.25in / 54cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=LvK0z3xzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOGtqSHptTm41alNNM2xOaFowY0diS3VEN1QrRTR5MUhHSXY4WU1mTUg0Mmd2ZEZTUmVWb0hpSzdpdFVJbE9USnowNkt6SVE2bzh6R2x4UFRkVEFaV2hQdUNUZkx5QUlZajlkenY0Qi9aam52MFRyMG9PQzVUQzFSWFBLZkRTTm9IYkxKUFhTTFNnamNEOU9mN1ZoVXgxYz18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fkanken-mini-backpack-fjallraven%2Fvp%2Fv%3D1%2F1502980647.htm%3Fextid%3DDP_Criteo_US_MV_1502980647%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1502980647&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ffjall%2Ffjall3005811279%2Ffjall3005811279_q1_1-0._QL90_UX336_.jpg&w=400&s=EPb7WSeSOvrA7tqUF902BkBD\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Fjallraven Kanken Mini Backpack<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A sturdy Fj&#228;llr&#228;ven backpack, detailed with a reflective logo patch and front zip pocket. Patch side pockets offer easy access to essentials, and a 2-way, wraparound zip secures the top. A removable foam panel adds extra protection to the back. Double handles and adjustable shoulder straps. Fabric: Nylon weave. Weight: 8oz / 0.23kg. Imported, Vietnam. Measurements Height: 11in / 28cm Length: 8in / 20.5cm Depth: 3in / 7.5cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=HxF3bXxzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOHNEYTE3UjhlWTU2QXVWV0lHb2xYNHJjVlZSNldUZ0d6Q2tNbHZaYzFOV092ZzNMTjcyYmJDVHhYSFlQZGVObkJoVzNrM21DUWNONlJjRm9ZVzA5RkIwdmFaeTd3bnp1QWVOc05hc1ZyTDMxRkwyOEJrbXBXeEhqdEU5MWUvU0xKOXE1ZVQ3bzl1UEl5VHFRUUl4aytPRT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fnokki-crossbody-bag-opening-ceremony%2Fvp%2Fv%3D1%2F1568803294.htm%3Fextid%3DDP_Criteo_US_MV_1568803294%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1568803294&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fopcer%2Fopcer4088511625%2Fopcer4088511625_q1_1-0._QL90_UX336_.jpg&w=400&s=9q6emkuykrzwS0Z8Yc5z51pR\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Opening Ceremony Nokki Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A slim, structured Opening Ceremony bag in smooth leather. A hand-shaped lock secures the top flap, which opens to a lined, 2-pocket interior. Optional shoulder strap. Dust bag included. Leather: Calfskin. Weight: 21oz / 0.6kg. Imported, China. Measurements Height: 7.75in / 20cm Length: 10.75in / 27cm Depth: 1.75in / 4.5cm Strap drop: 17.75in / 45cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"/div>\n";
ifc += "<"+"!-- PRIVACY[BOTTOM:RIGHT] -->\n";
ifc += " <"+"div class=\"footer\" id=\"footer\"> \n";
ifc += "                            <"+"div class=\'privacy\'>\n";
ifc += "                                <"+"a href=\'http://info.criteo.com/pac/privacy/informations?infonorm=2&amp;partner=14830&amp;campaignid=79935&amp;zoneid=370523&amp;bannerid=4082408&amp;displayid=b7b4fcf359\' target=\'_blank\'><"+"/a>\n";
ifc += "                            <"+"/div> <"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&amp;cpp=x7xeM3xzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMVl0MHduN1JJUjVrOGt5S0xlQVVsOG1HZHloZkpCQ2JHcHNVUERNcnNqajBFYi82aWlnam1tMHNHc05UK2srU2ZjSE1qeUhsdWpRUEhsejhpSHFGSHpmSVoxM05hZnJuclRheUZXRjBORzdJcm4zMFlTNldUTkRmMXVtNTNkS3JJVUtjV1E0a0lDbE52MWxBWUo0c3RpQT09fA%3D%3D&amp;maxdest=http%3A%2F%2Fwww.shopbop.com%2F%3Fextid%3DDP_Criteo_US_MV_%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" id=\"adUrl\" class=\"adUrl\" >Advertisement | shopbop.com<"+"/a> <"+"span id=\"legal\" class=\"legal\" onmouseover=\"javascript:display_hide(\'legalover\');\"><"+"/span> <"+"/div> <"+"div id=\"legalover\" class=\"legalover\" onmouseout=\"javascript:display_hide(\'legalover\');\"><"+"/div>\n";
ifc += " <"+"/div>\n";
ifc += "<"+"style>#cto_banner_content .privacy {\n";
ifc += "                    width:77px;\n";
ifc += "                    float:right;\n";
ifc += "                    text-align:right;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a {\n";
ifc += "                    display:inline-block;\n";
ifc += "                    width:19px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_small.png);\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a:hover {\n";
ifc += "                    width:77px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_big.png);\n";
ifc += "                }<"+"/style>\n";
ifc += "<"+"script type=\'text/javascript\'>(function() { var arrayEquals = function (a, b) {\n";
ifc += "                if(a.length != b.length) return false;\n";
ifc += "                a = a.sort();\n";
ifc += "                b = b.sort();\n";
ifc += "                for(var i = 0; i <"+" a.length; ++i) {\n";
ifc += "                    if (a[i] != b[i]) return false;\n";
ifc += "                }\n";
ifc += "                return true;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var arrayIterate = function (a, fct) {\n";
ifc += "                var len = a.length;\n";
ifc += "                for(var i = 0; i <"+" len; ++i) {\n";
ifc += "                    fct(a[i], i); \n";
ifc += "                }\n";
ifc += "             };\n";
ifc += "   \n";
ifc += "            var arrayWhere = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    if(fct(elt, index)) b.push(elt);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "             };\n";
ifc += "      \n";
ifc += "            var arrayMap = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    b[index] = fct(elt, index);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var multilineEllipsis = function (div) {\n";
ifc += "                var t = div.textContent || div.innerText;\n";
ifc += "                var d = document.createElement(\'div\');\n";
ifc += "                var i = 0;    \n";
ifc += "                d.style.width = div.offsetWidth + \'px\';\n";
ifc += "                d.style.visibility = \"hidden\";\n";
ifc += "                div.appendChild(d);\n";
ifc += "\n";
ifc += "                while(d.offsetHeight <"+"= div.offsetHeight && i <"+" t.length) {\n";
ifc += "                    d.textContent = d.innerText = t.substr(0, i) + \'...\';\n";
ifc += "                    ++i;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                div.removeChild(d);\n";
ifc += "                if(i != t.length) div.textContent = div.innerText = t.substr(0, i-2) + \'...\';\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            (function() {\n";
ifc += "                var c = document.getElementById(\'cto_banner_content\');\n";
ifc += "                var isMultilineEllipsis = function(elt) { return elt.getAttribute(\'data-ellipsis\') == \'multiline\'; };\n";
ifc += "                arrayIterate(arrayWhere(c.getElementsByTagName(\'*\'), isMultilineEllipsis), multilineEllipsis);\n";
ifc += "            })(); })();<"+"/script>\n";
ifc += "<"+"script type=\"text/javascript\">\n";
ifc += "var legal = document.getElementById(\"legal\");\n";
ifc += "if(legal.innerText == \"\"){legal.style.display=\"none\";}\n";
ifc += "else {document.getElementById(\"adUrl\").style.maxWidth=\"65px\";} function display_hide(id) { var legalLength = legal.innerHTML.length; var element = document.getElementById(id); if(element===null) return false; if((element.style.visibility==\"hidden\") && (legalLength > 10)){ element.style.visibility=\"visible\"; } else { element.style.visibility=\"hidden\"; } return true;\n";
ifc += "} (function() { var getElts = function(className, domElem) { var desc = []; if (document.getElementsByClassName) { desc = domElem.getElementsByClassName(className); } else { var elem = domElem.getElementsByTagName(\'*\'); for (var x = 0; x <"+" elem.length; x++) { if ((\' \' + elem[x].className + \' \').indexOf(\' \' + className + \' \') > -1) desc.push(elem[x]); } } return desc; }; var truncate = function(div, maxCharacter) { var t = div.textContent || div.innerText || \"\"; var trimmed = t.replace(\'\\n\', \'\').replace(/^ +| +$/g, \'\'); if(trimmed.length > maxCharacter) div.textContent = div.innerText = trimmed.substr(0, maxCharacter-3) + \'...\'; }; var products = getElts(\"cto_product\", document); for(var x = 0; x <"+" products.length; ++x) { var price = getElts(\"priceDesc\", products[x])[0]; var priceType = getElts(\"priceType\", price)[0]; var priceNumber = getElts(\"price\", price)[0]; var priceOrig = getElts(\"origPrice\", price)[0]; var priceTypeText = priceType.textContent || priceType.innerText || \"\"; if (priceNumber.innerHTML == \"\" || priceNumber.innerHTML.length > 14) { price.removeChild(priceOrig); price.removeChild(priceType); price.removeChild(priceNumber); } else if (priceTypeText.indexOf(\"__\") == 0) { var altprice = priceTypeText.replace(/_/g, \"\"); priceType.innerHTML = altprice; price.removeChild(priceOrig); } else if (priceTypeText == \"rrp\") { price.removeChild(priceType); } }\n";
ifc += "})(); <"+"/script><"+"/div><"+"div style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"iframe id=\'ifb7b4fcf359\' name=\'ifb7b4fcf359\' width=\'1px\' height=\'1px\'><"+"/iframe>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div id=\'beacon_b7b4fcf359\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"img width=\"0\" height=\"0\" src=\"http://shopbop.sp1.convertro.com/view/vt/v1/shopbop/1/cvo.gif?cvosrc=retargeting.criteo.Shop%20Bop%20US%20MV&cvo_placement=&cvo_creative=&cvo_cid=79935\"/>\n";
ifc += "<"+"img width=\"0\" height=\"0\" src=\"http://cat.ny.us.criteo.com/delivery/lg.php?cppv=1&cpp=U5z2i3xzNDN0SElNQ3M0dkJuMk0yQ1NSTGZmYXNHdlViYzFQdG5KZ096N2J5aElmaVRHNjZlK0hZbWdtSE5DK1RyK2Fka1B4WjZHNkJncHN6eGJpSWJwQ3hjb0xSNEcwdlVWM0w1WjF6T2hUU0JETDFhTnBHcFhKUmZxWkFsSTc5bkxqMUVpM3Vyamw3RW1IZFJUcEYwN3JPY01tcVh1NWc2OUt3bXdPL0c5d2hZRTZoQm9GVnZjQlJkSGVGdlEvTzVXY1ptdk40TjF5eitsUGpUaVExeUxuZDRBWXBEek5JR3RQdnBDMTB3TXZLd0RIdTFwZTNwUUxjVWVHdVoybjlwVXhUSVVQM3MyTFYyRUJRWENoSTMrZ1hjYktkRloycjZzNWxIai9EK2xqalBxcz18\"/>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/body>\n";
ifc += "<"+"/html>\n";

var fillIframe = function(ifrd) {
    var getDocument = function(iframe) {
        var result_document = iframe.contentWindow || iframe.contentDocument;
        if (result_document && result_document.document)
            result_document = result_document.document;
        return result_document;
    };
    var c = getDocument(ifrd);
    if (c) {
        c.open();
        c.write(ifc);
        c.close();
    }
};


var maxRetryAttempts = 100;
var loaded = false;
var pollIframe = function() {
    var ifrd = document.getElementById('cto_iframe_b7b4fcf359');
    if (ifrd && isIE) {
         ifrd.onload = function() {
            if(!loaded) {
                loaded = true;
                fillIframe(ifrd);
            }
        };
    } else if (ifrd) {
        loaded = true;
        fillIframe(ifrd);
    } else if (maxRetryAttempts-- > 0) {
        setTimeout(pollIframe, 10);
    }
};pollIframe();})();
