var OA_output = new Array(); 
OA_output['zone_728x90'] = '';
OA_output['zone_728x90'] += "<"+"a href=\'http://f.blogads.com/delivery/ck.php?oaparams=2__bannerid=8114__zoneid=1__cb=092a7abc60__oadest=http%3A%2F%2Fwww1.play.it%2Faudio%2Fthe-php-perez-hilton-podcast%2F%3Futm_source%3DPerezHilton%26utm_medium%3Ddisplay%26utm_campaign%3DPerezHilton_Display_72890\' target=\'_blank\'><"+"img src=\'http://f.blogads.com/delivery/ai.php?filename=perez-728x90-3.jpg&contenttype=jpeg\' width=\'728\' height=\'90\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_092a7abc60\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=8114&amp;campaignid=6312&amp;zoneid=1&amp;loc=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=092a7abc60\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_728x90_bottom'] = '';
OA_output['zone_728x90_bottom'] += "<"+"script type=\"text/javascript\">\n";
OA_output['zone_728x90_bottom'] += "if ((typeof (ph_ad_page) !== \'undefined\' && ph_ad_page == \'no\') ||\n";
OA_output['zone_728x90_bottom'] += "location.href.search(/ph_ad_page=no/i) !== -1) {\n";
OA_output['zone_728x90_bottom'] += "document.write(\'<"+"div id=\"537339401_INSERT_SLOT_ID_HERE\" style=\"width:728px;height:90px;margin:0;padding:0\"><"+"/div>\');\n";
OA_output['zone_728x90_bottom'] += "var OX_ads = OX_ads || [];\n";
OA_output['zone_728x90_bottom'] += "OX_ads.push({\n";
OA_output['zone_728x90_bottom'] += "slot_id: \"537339401_INSERT_SLOT_ID_HERE\",\n";
OA_output['zone_728x90_bottom'] += "auid: \"537339401\"\n";
OA_output['zone_728x90_bottom'] += "});\n";
OA_output['zone_728x90_bottom'] += "if (window.location != window.parent.location) {\n";
OA_output['zone_728x90_bottom'] += "document.write(\'<"+"scr\' + \'ipt src=\"//ox-d.blogads.servedbyopenx.com/w/1.0/jstag\"><"+"\\/scr\' + \'ipt>\');\n";
OA_output['zone_728x90_bottom'] += "}\n";
OA_output['zone_728x90_bottom'] += "else if (typeof (ph_ox_dblogads_servedbyopenx_com) == \"undefined\") {\n";
OA_output['zone_728x90_bottom'] += "$(document).ready(function () {\n";
OA_output['zone_728x90_bottom'] += "setTimeout(\"$.getScript(\'//ox-d.blogads.servedbyopenx.com/w/1.0/jstag\');\", ph_third_party_delay);\n";
OA_output['zone_728x90_bottom'] += "});\n";
OA_output['zone_728x90_bottom'] += "window.ph_ox_dblogads_servedbyopenx_com = true;\n";
OA_output['zone_728x90_bottom'] += "}\n";
OA_output['zone_728x90_bottom'] += "}\n";
OA_output['zone_728x90_bottom'] += "<"+"/script><"+"div id=\'beacon_4eae92c129\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=7784&amp;campaignid=6119&amp;zoneid=202&amp;loc=1&amp;referer=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=4eae92c129\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_160x600'] = '';
OA_output['zone_160x600'] += "<"+"a href=\'http://f.blogads.com/delivery/ck.php?oaparams=2__bannerid=8116__zoneid=10__cb=5730d0b6a8__oadest=http%3A%2F%2Fwww1.play.it%2Faudio%2Fthe-php-perez-hilton-podcast%2F%3Futm_source%3DPerezHilton%26utm_medium%3Ddisplay%26utm_campaign%3DPerezHilton_Display_160\' target=\'_blank\'><"+"img src=\'http://f.blogads.com/delivery/ai.php?filename=perez-160x600-3.jpg&contenttype=jpeg\' width=\'160\' height=\'600\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_5730d0b6a8\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=8116&amp;campaignid=6314&amp;zoneid=10&amp;loc=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=5730d0b6a8\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_300x250_top'] = '';
OA_output['zone_300x250_top'] += "<"+"script type=\"text/javascript\">\n";
OA_output['zone_300x250_top'] += "if ((typeof (ph_ad_page) !== \'undefined\' &&\n";
OA_output['zone_300x250_top'] += "ph_ad_page == \'no\' &&\n";
OA_output['zone_300x250_top'] += "typeof (ph_third_party_delay) !== \'undefined\') ||\n";
OA_output['zone_300x250_top'] += "(location.href.search(/ph_ad_page\\=no/i) !== -1)) {\n";
OA_output['zone_300x250_top'] += "document.write(\'<"+"div id=\"OpenX_SSP_Homepage_300x250_ATF\" style=\"width: 300px; height: 250px;\"><"+"/div>\');\n";
OA_output['zone_300x250_top'] += "(function () {\n";
OA_output['zone_300x250_top'] += "var div_id = \'OpenX_SSP_Homepage_300x250_ATF\';\n";
OA_output['zone_300x250_top'] += "var url = \'http://i.perezhilton.com/included_ads/remnant_ad_codes/OpenX_SSP_Homepage_300x250_ATF.html?v=4\';\n";
OA_output['zone_300x250_top'] += "var html = \'<"+"iframe width=\"300\" height=\"250\" frameborder=\"0\" scrolling=\"no\" src=\"\' + url + \'\"><"+"/iframe>\';\n";
OA_output['zone_300x250_top'] += "if (typeof (ph_third_party_delay) !== \'undefined\' && typeof (jQuery) !== \"undefined\") {\n";
OA_output['zone_300x250_top'] += "$(document).ready(function () {\n";
OA_output['zone_300x250_top'] += "setTimeout(\"document.getElementById(\'\" + div_id + \"\').innerHTML = \'\" + html + \"\'\", window.ph_third_party_delay);\n";
OA_output['zone_300x250_top'] += "});\n";
OA_output['zone_300x250_top'] += "} else {\n";
OA_output['zone_300x250_top'] += "document.getElementById(div_id).innerHTML = html;\n";
OA_output['zone_300x250_top'] += "}\n";
OA_output['zone_300x250_top'] += "}).call(this);\n";
OA_output['zone_300x250_top'] += "}\n";
OA_output['zone_300x250_top'] += "<"+"/script><"+"div id=\'beacon_a29207410e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=7780&amp;campaignid=6114&amp;zoneid=139&amp;loc=1&amp;referer=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=a29207410e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_300x250_mid'] = '';
OA_output['zone_300x250_mid'] += "<"+"script type=\"text/javascript\">\n";
OA_output['zone_300x250_mid'] += "if ((typeof (ph_ad_page) !== \'undefined\' && ph_ad_page == \'no\') ||\n";
OA_output['zone_300x250_mid'] += "location.href.search(/ph_ad_page=no/i) !== -1) {\n";
OA_output['zone_300x250_mid'] += "document.write(\'<"+"div id=\"537339396_INSERT_SLOT_ID_HERE\" style=\"width:300px;height:250px;margin:0;padding:0\"><"+"/div>\');\n";
OA_output['zone_300x250_mid'] += "var OX_ads = OX_ads || [];\n";
OA_output['zone_300x250_mid'] += "OX_ads.push({\n";
OA_output['zone_300x250_mid'] += "slot_id: \"537339396_INSERT_SLOT_ID_HERE\",\n";
OA_output['zone_300x250_mid'] += "auid: \"537339396\"\n";
OA_output['zone_300x250_mid'] += "});\n";
OA_output['zone_300x250_mid'] += "if (window.location != window.parent.location) {\n";
OA_output['zone_300x250_mid'] += "document.write(\'<"+"scr\' + \'ipt src=\"//ox-d.blogads.servedbyopenx.com/w/1.0/jstag\"><"+"\\/scr\' + \'ipt>\');\n";
OA_output['zone_300x250_mid'] += "}\n";
OA_output['zone_300x250_mid'] += "else if (typeof (ph_ox_dblogads_servedbyopenx_com) == \"undefined\") {\n";
OA_output['zone_300x250_mid'] += "$(document).ready(function () {\n";
OA_output['zone_300x250_mid'] += "setTimeout(\"$.getScript(\'//ox-d.blogads.servedbyopenx.com/w/1.0/jstag\');\", ph_third_party_delay);\n";
OA_output['zone_300x250_mid'] += "});\n";
OA_output['zone_300x250_mid'] += "window.ph_ox_dblogads_servedbyopenx_com = true;\n";
OA_output['zone_300x250_mid'] += "}\n";
OA_output['zone_300x250_mid'] += "}\n";
OA_output['zone_300x250_mid'] += "<"+"/script><"+"div id=\'beacon_4d2ef99afb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=7782&amp;campaignid=6117&amp;zoneid=140&amp;loc=1&amp;referer=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=4d2ef99afb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_300x250_btw'] = '';
OA_output['zone_300x250_btw'] += "<"+"a href=\'http://f.blogads.com/delivery/ck.php?oaparams=2__bannerid=8115__zoneid=2__cb=7e54ebd522__oadest=http%3A%2F%2Fwww1.play.it%2Faudio%2Fthe-php-perez-hilton-podcast%2F%3Futm_source%3DPerezHilton%26utm_medium%3Ddisplay%26utm_campaign%3DPerezHilton_Display_300250\' target=\'_blank\'><"+"img src=\'http://f.blogads.com/delivery/ai.php?filename=perez-300x250-2.jpg&contenttype=jpeg\' width=\'300\' height=\'250\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_7e54ebd522\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=8115&amp;campaignid=6313&amp;zoneid=2&amp;loc=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=7e54ebd522\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_skin'] = '';

OA_output['zone_award_unit'] = '';

OA_output['zone_728x90_back'] = '';
OA_output['zone_728x90_back'] += "<"+"a href=\'http://f.blogads.com/delivery/ck.php?oaparams=2__bannerid=8114__zoneid=11__cb=a73af4969b__oadest=http%3A%2F%2Fwww1.play.it%2Faudio%2Fthe-php-perez-hilton-podcast%2F%3Futm_source%3DPerezHilton%26utm_medium%3Ddisplay%26utm_campaign%3DPerezHilton_Display_72890\' target=\'_blank\'><"+"img src=\'http://f.blogads.com/delivery/ai.php?filename=perez-728x90-3.jpg&contenttype=jpeg\' width=\'728\' height=\'90\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_a73af4969b\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=8114&amp;campaignid=6312&amp;zoneid=11&amp;loc=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=a73af4969b\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_300x250_top_back'] = '';

OA_output['zone_300x250_mid_back'] = '';

OA_output['zone_300x250_btw_back'] = '';
OA_output['zone_300x250_btw_back'] += "<"+"a href=\'http://f.blogads.com/delivery/ck.php?oaparams=2__bannerid=8115__zoneid=12__cb=7ebbf93e7d__oadest=http%3A%2F%2Fwww1.play.it%2Faudio%2Fthe-php-perez-hilton-podcast%2F%3Futm_source%3DPerezHilton%26utm_medium%3Ddisplay%26utm_campaign%3DPerezHilton_Display_300250\' target=\'_blank\'><"+"img src=\'http://f.blogads.com/delivery/ai.php?filename=perez-300x250-2.jpg&contenttype=jpeg\' width=\'300\' height=\'250\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_7ebbf93e7d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=8115&amp;campaignid=6313&amp;zoneid=12&amp;loc=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=7ebbf93e7d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_300x250_below_2nd'] = '';

OA_output['zone_300x250_below_3rd'] = '';
OA_output['zone_300x250_below_3rd'] += "<"+"img src=\"http://i.perezhilton.com/images/blank.gif\" /><"+"div id=\'beacon_86a50a3a1d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=6128&amp;campaignid=4969&amp;zoneid=186&amp;loc=1&amp;referer=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=86a50a3a1d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_300x250_below_5th'] = '';
OA_output['zone_300x250_below_5th'] += "<"+"!-- GOOGLE ADSENSE BELOW FIFTH POST - VERSION 4.0 -->\n";
OA_output['zone_300x250_below_5th'] += "<"+"style type=\"text/css\">\n";
OA_output['zone_300x250_below_5th'] += "#google_btw_posts_2 {\n";
OA_output['zone_300x250_below_5th'] += "display: none;\n";
OA_output['zone_300x250_below_5th'] += "}\n";
OA_output['zone_300x250_below_5th'] += "#below_fifth_post_300x250 {\n";
OA_output['zone_300x250_below_5th'] += "width: 470px !important;\n";
OA_output['zone_300x250_below_5th'] += "padding: 0 0 0 0 !important;\n";
OA_output['zone_300x250_below_5th'] += "}\n";
OA_output['zone_300x250_below_5th'] += ".google_adsense_image_ad_btw_posts {\n";
OA_output['zone_300x250_below_5th'] += "margin: 0 6px !important;\n";
OA_output['zone_300x250_below_5th'] += "width: 468px !important;\n";
OA_output['zone_300x250_below_5th'] += "}\n";
OA_output['zone_300x250_below_5th'] += "<"+"/style>\n";
OA_output['zone_300x250_below_5th'] += "<"+"script type=\"text/javascript\">\n";
OA_output['zone_300x250_below_5th'] += "function google_ad_request_done(google_ads) {\n";
OA_output['zone_300x250_below_5th'] += "if(typeof(google_ads.length) == \'undefined\' || google_ads.length == 0 || ph_ad_page == \'yes\')\n";
OA_output['zone_300x250_below_5th'] += "return;\n";
OA_output['zone_300x250_below_5th'] += "var box = \'\';\n";
OA_output['zone_300x250_below_5th'] += "if(google_ads[0].type == \"flash\") {\n";
OA_output['zone_300x250_below_5th'] += "box += \'<"+"div class=\"title\"><"+"a href=\\\"\' + google_info.feedback_url + \'\\\" target=\"_blank\">Advertising<"+"/a><"+"/div><"+"div class=\"ad\">\' + \'<"+"object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\"\' + \' codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0\" WIDTH=\"\' + google_ads[0].image_width + \'\" HEIGHT=\"\' + google_ads[0].image_height + \'\"> <"+"PARAM NAME=\"movie\" VALUE=\"\' + google_ads[0].image_url + \'\">\' + \'<"+"PARAM NAME=\"quality\" VALUE=\"high\">\' + \'<"+"PARAM NAME=\"AllowScriptAccess\" VALUE=\"never\">\' + \'<"+"EMBED src=\"\' + google_ads[0].image_url + \'\" WIDTH=\"\' + google_ads[0].image_width + \'\" HEIGHT=\"\' + google_ads[0].image_height + \'\" TYPE=\"application/x-shockwave-flash\"\' + \' AllowScriptAccess=\"never\" \' + \' PLUGINSPAGE=\"http://www.macromedia.com/go/getflashplayer\"><"+"/EMBED><"+"/OBJECT><"+"/div>\';\n";
OA_output['zone_300x250_below_5th'] += "$(\"#google_btw_posts_2\").addClass(\"google_adsense_image_ad_btw_posts\");\n";
OA_output['zone_300x250_below_5th'] += "} else if(google_ads[0].type == \"image\") {\n";
OA_output['zone_300x250_below_5th'] += "box += \'<"+"div class=\"title\"><"+"a href=\\\"\' + google_info.feedback_url + \'\\\" target=\"_blank\">Advertising<"+"/a><"+"/div><"+"div class=\"ad\"><"+"a href=\"\' + google_ads[0].url + \'\" target=\"_top\" title=\"go to \' + google_ads[0].visible_url + \'\" onmouseout=\"window.status=\\\'\\\'\" onmouseover=\"window.status=\\\'go to \' + google_ads[0].visible_url + \'\\\';return true\"><"+"img border=\"0\" src=\"\' + google_ads[0].image_url + \'\"width=\"\' + google_ads[0].image_width + \'\"height=\"\' + google_ads[0].image_height + \'\"><"+"/a><"+"/div>\';\n";
OA_output['zone_300x250_below_5th'] += "$(\"#google_btw_posts_2\").addClass(\"google_adsense_image_ad_btw_posts\");\n";
OA_output['zone_300x250_below_5th'] += "} else if(google_ads[0].type == \"html\") {\n";
OA_output['zone_300x250_below_5th'] += "box += \'<"+"div class=\"title\"><"+"a href=\\\"\' + google_info.feedback_url + \'\\\" target=\"_blank\">Advertising<"+"/a><"+"/div><"+"div class=\"ad\">\' + google_ads[0].snippet + \'<"+"/div>\';\n";
OA_output['zone_300x250_below_5th'] += "$(\"#google_btw_posts_2\").addClass(\"google_adsense_image_ad_btw_posts\");\n";
OA_output['zone_300x250_below_5th'] += "} else {\n";
OA_output['zone_300x250_below_5th'] += "var box_header = \'<"+"div class=\"title\"><"+"a href=\"\' + google_info.feedback_url + \'\">Advertising<"+"/a><"+"/div>\';\n";
OA_output['zone_300x250_below_5th'] += "var box_footer = \'<"+"div class=\"clear\"><"+"/div><"+"/div>\';\n";
OA_output['zone_300x250_below_5th'] += "var box_item = \'<"+"div class=\"ad\">\' +\n";
OA_output['zone_300x250_below_5th'] += "\'<"+"div class=\"title\"><"+"a href=\"%%url%%\" target=\"_blank\">%%line1%%<"+"/a><"+"/div>\' +\n";
OA_output['zone_300x250_below_5th'] += "\'<"+"div class=\"content\">%%line2%%<"+"br/>%%line3%%<"+"/div>\' +\n";
OA_output['zone_300x250_below_5th'] += "\'<"+"div class=\"url\"><"+"a href=\"%%url%%\" target=\"_blank\">%%visibleurl%%<"+"/a><"+"/div>\' +\n";
OA_output['zone_300x250_below_5th'] += "\'<"+"/div>\';\n";
OA_output['zone_300x250_below_5th'] += "var i;\n";
OA_output['zone_300x250_below_5th'] += "for(i = 0; i <"+" google_ads.length; ++i) {\n";
OA_output['zone_300x250_below_5th'] += "if(i > 1) break;\n";
OA_output['zone_300x250_below_5th'] += "if(typeof(google_ads[i]) == \'undefined\') continue;\n";
OA_output['zone_300x250_below_5th'] += "box += box_item;\n";
OA_output['zone_300x250_below_5th'] += "box = box.replace(/%%line1%%/g, google_ads[i].line1);\n";
OA_output['zone_300x250_below_5th'] += "box = box.replace(/%%line2%%/g, google_ads[i].line2);\n";
OA_output['zone_300x250_below_5th'] += "box = box.replace(/%%line3%%/g, google_ads[i].line3);\n";
OA_output['zone_300x250_below_5th'] += "box = box.replace(/%%url%%/g, google_ads[i].url);\n";
OA_output['zone_300x250_below_5th'] += "box = box.replace(/%%visibleurl%%/g, google_ads[i].visible_url);\n";
OA_output['zone_300x250_below_5th'] += "}\n";
OA_output['zone_300x250_below_5th'] += "if(box !== \'\') {\n";
OA_output['zone_300x250_below_5th'] += "box = box_header + box + box_footer;\n";
OA_output['zone_300x250_below_5th'] += "$(\"#google_btw_posts_2\").addClass(\"google_adsense_btw_posts\");\n";
OA_output['zone_300x250_below_5th'] += "}\n";
OA_output['zone_300x250_below_5th'] += "}\n";
OA_output['zone_300x250_below_5th'] += "$(\"#google_btw_posts_2\").html(box);\n";
OA_output['zone_300x250_below_5th'] += "$(\"#google_btw_posts_2\").show();\n";
OA_output['zone_300x250_below_5th'] += "google_adnum += google_ads.length;\n";
OA_output['zone_300x250_below_5th'] += "return;\n";
OA_output['zone_300x250_below_5th'] += "}\n";
OA_output['zone_300x250_below_5th'] += "if (ph_ad_page == \'no\') {\n";
OA_output['zone_300x250_below_5th'] += "google_ad_client = \"ca-pub-0791556918823650\";\n";
OA_output['zone_300x250_below_5th'] += "google_ad_output = \'js\';\n";
OA_output['zone_300x250_below_5th'] += "google_max_num_ads = \'6\';\n";
OA_output['zone_300x250_below_5th'] += "google_adnum = 0;\n";
OA_output['zone_300x250_below_5th'] += "google_ad_type = \"text_flash_image\";\n";
OA_output['zone_300x250_below_5th'] += "google_image_size = \"468x60\";\n";
OA_output['zone_300x250_below_5th'] += "google_ad_channel = \"9173922126\";\n";
OA_output['zone_300x250_below_5th'] += "document.write(\'<"+"div id=\"google_btw_posts_2\"><"+"/div>\');\n";
OA_output['zone_300x250_below_5th'] += "document.write(\'<"+"scr\' + \'ipt type=\"text/javascript\" src=\"http://pagead2.googlesyndication.com/pagead/show_ads.js\"><"+"/scr\' + \'ipt>\');\n";
OA_output['zone_300x250_below_5th'] += "}\n";
OA_output['zone_300x250_below_5th'] += "<"+"/script>\n";
OA_output['zone_300x250_below_5th'] += "<"+"!-- /GOOGLE ADSENSE BELOW FIFTH POST - VERSION 4.0 --><"+"div id=\'beacon_3341379eb9\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://f.blogads.com/delivery/lg.php?bannerid=4379&amp;campaignid=3080&amp;zoneid=187&amp;loc=1&amp;referer=http%3A%2F%2Fperezhilton.com%2Fcategory%2Flamar-odom%2F&amp;cb=3341379eb9\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['zone_300x250_below_6th'] = '';

OA_output['zone_300x250_top_2'] = '';

