(function(){
var isIE = window.navigator.userAgent.indexOf("MSIE ") > 0;
var ifr = document.createElement('iframe');
ifr.setAttribute('id', 'cto_iframe_939d6294bc');
ifr.setAttribute('frameBorder', 0);
ifr.setAttribute('allowtransparency', true);
ifr.setAttribute('hspace', 0);
ifr.setAttribute('marginwidth', 0);
ifr.setAttribute('marginheight', 0);
ifr.setAttribute('scrolling', 'no');
ifr.setAttribute('vspace', 0);
ifr.setAttribute('width', '300px');
ifr.setAttribute('height', '250px');

var container = document.getElementById('dfp-tag-rightrail-position-2');
if (container) { container.appendChild(ifr); }
var ifc = "\n";
ifc += "<"+"!DOCTYPE html>\n";
ifc += "<"+"html>\n";
ifc += "  <"+"head>\n";
ifc += "    <"+"meta name=\"format-detection\" content=\"telephone=no\"><"+"meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n";
ifc += "  <"+"/head>\n";
ifc += "  <"+"body><"+"div id=\'cto_banner_content\'><"+"style>\n";
ifc += "#cto_products .cto_product .imgholder{ text-align : center; background : #ffffff; float : left; margin-right : 7px; width : 74px; height : 74px;\n";
ifc += "} #cto_products .cto_product .imgholder img{ border : none; max-width : 74px; max-height : 74px; *width : expression(this.width >= this.height ? \"74px\" : \"auto\"); *height : expression(this.width <"+" this.height ? \"74px\" : \"auto\");\n";
ifc += "} #cto_products .cto_product .title{ overflow : hidden; color : #016090; font-size : 14px; height : 18px; line-height : 16px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product .desc{ overflow : hidden; color : #646464; font-size : 12px; height : 30px; line-height : 14px;\n";
ifc += "} #cto_products .cto_product .priceDesc{ color : #FF9900; font-size : 16px; height : 24px; line-height : 20px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product .priceDesc .origPrice{ color : #999; font-size : 13px; height : 18px; line-height : 16px; font-weight : normal;\n";
ifc += "} #cto_products .cto_product:hover{ background : #eeeeee;\n";
ifc += "} #cto_products .cto_product .details{ float : left; width : 217px;\n";
ifc += "} #cto_products .cto_product *{ *cursor : pointer;\n";
ifc += "} #cto_products .cto_product a{ color : black; text-decoration : none;\n";
ifc += "} #cto_bannerContent{ width : 300px; height : 250px; background : #ffffff; position : relative; font-family : Arial,sans-serif; font-size : 0; overflow : hidden;\n";
ifc += "} #cto_products{ height : 233px; width : 300px; overflow : hidden;\n";
ifc += "} #cto_products .cto_product{ width : 298px; height : 74px; float : left; text-align : left; overflow : hidden; vertical-align : top; zoom : 1; position : relative; *zoom : 1; *display : inline; margin : 1px 1px 3px 1px;\n";
ifc += "} #cto_bannerContent .footer{ height : 17px; line-height : 16px; position : relative; text-align : left;\n";
ifc += "} #cto_bannerContent .adUrl{ font-size : 11px; color : #808080; text-decoration : none; cursor : pointer; *cursor : pointer; zoom : 1; vertical-align : top; margin-right : 4px; display : inline-block; *display : inline; margin-left : 4px; line-height : 17px;\n";
ifc += "} #cto_bannerContent .adUrl:hover{ text-decoration : underline;\n";
ifc += "} #cto_bannerContent .legal{ text-overflow : ellipsis; white-space : nowrap; overflow : hidden; font-size : 11px; color : #808080; display : inline-block; *display : inline; height : 16px; width : 100px;\n";
ifc += "} #cto_bannerContent .legalover{ position : absolute; left : 1px; box-sizing : border-box; font-size : 11px; color : #808080; text-decoration : none; display : block; zoom : 1; padding : 4px; background : #eee; opacity : 0.95; filter : alpha(opacity=95); visibility : hidden; line-height : 12px; width : 300px; bottom : 1px;\n";
ifc += "} <"+"/style>\n";
ifc += "<"+"div id=\"cto_bannerContent\">\n";
ifc += "<"+"div id=\"cto_products\">\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=CzObBHx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHRXblg1K25HdUlUMXhYalArUHM4a2JEdkZETjZLTkdvYUVYOEZQczRJRStmUFlDR1M4TDdJNldibUJVOHdYVmRwSTVrbmtaak5UTkJ1OEt5bWlRV2d3d3dEMnRGSTNLWGlpeXA2ZU5mbGJTdHdPTjVHd1REL1RGVXBPeFhvYnN0OGkvMm01OXEvSE16a3E3d2FsWVd4Yz18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fselma-medium-messenger-michael-kors%2Fvp%2Fv%3D1%2F1515437630.htm%3Fextid%3DDP_Criteo_US_MV_1515437630%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1515437630&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fmmkor%2Fmmkor2048510519%2Fmmkor2048510519_q1_1-0._QL90_UX336_.jpg&w=400&s=TW0Ga_DwZp3eKil4eN9H91sn\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">MICHAEL Michael Kors Selma Medium Messenger Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">Sturdy saffiano leather and gold-tone hardware bring professional polish to this MICHAEL Michael Kors satchel. The inset top zip opens to a logo-lined interior with 1 pocket and a spring-lock keychain. Optional, adjustable shoulder strap. Dust bag included. Leather: Cowhide. Weight: 22oz / 0.62kg. Imported, Philippines. Measurements Height: 6.75in / 17cm Length: 9in / 23cm Depth: 4in / 10cm Strap drop: 22in / 56cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=nWEPRHx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcGlxWjhIM3UzNU0wc3NXd0VLazB6ZW1lQ2k5aTh1eVFPMkZaTUJrRHIwKzQxNXpkK0NPVngxTGNjakFLK3NCNCttQk1GR0c3Wm8wSGM5ZzdIZmJvMkowS09hbW9RK0FPeUNYWWcyMUlabHdDOWpaTFRsV0hjc0hLOWczYTFJaW5RUT09fA%3D%3D&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fwillow-dress-mlm-label%2Fvp%2Fv%3D1%2F1518185711.htm%3Fextid%3DDP_Criteo_US_MV_1518185711%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1518185711&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fprod%2Fproducts%2Fmlmla%2Fmlmla3007812560%2Fmlmla3007812560_q1_1-0._QL90_UX336_.jpg&w=400&s=GbZbgjFg_ipuM0rXlVsh0cd8\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">MLM LABEL Willow Dress<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">An MLM LABEL mini dress in a flirty, off-shoulder profile. Elastic gathers the top. Short sleeves. Unlined. Fabric: Lightweight weave. 100% cotton. Hand wash. Imported, Indonesia. Measurements Length: 24in / 61cm, from shoulder Measurements from size XS. Available sizes: L,M,S,XS<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=0yC3LHx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHN0bk4xcHFwSENFb013S0lrSmpsT3QyejJSaDdqdEhic2dTZjdrUnRIN0c4NWFDS0xYOHBGSUtXL1ZjNHU4THhsUkVOK09WWW1kMmpGZ1I4VitsSEdnTEd6U2gyOW1WZWdnQnpnajA0LzNJdTRxOWtVdTd6bVdlTHBQOVF3YTlTTXkzWDhOWmUzRU9KaEZ0VnI0UWY1WT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fselma-medium-messenger-michael-kors%2Fvp%2Fv%3D1%2F1549915017.htm%3Fextid%3DDP_Criteo_US_MV_1549915017%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1549915017&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fmmkor%2Fmmkor2006412867%2Fmmkor2006412867_q1_1-0._QL90_UX336_.jpg&w=400&s=YNnwx0IiaEUWyQezLSHgDxdA\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">MICHAEL Michael Kors Selma Medium Messenger Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">Sturdy saffiano leather and gold-tone hardware bring professional polish to this MICHAEL Michael Kors satchel. The inset top zip opens to a logo-lined interior with 1 pocket and a spring-lock keychain. Optional, adjustable shoulder strap. Dust bag included. Leather: Cowhide. Weight: 19oz / 0.54kg. Imported, China. Measurements Height: 6.75in / 17cm Length: 9in / 23cm Depth: 4in / 10cm Strap drop: 22in / 56cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=KndY%2Bnx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHN0bk4xcHFwSENFb013S0lrSmpsT3NCQi9NbDlqMHg5RXk5UjRiaGM5Z3J0dmRxWnVLOEZ2NUtXaHhMQTQvbW9wWFZRSjVuYW9yRktBaGZHSEQwQ1ZubzJNdTFJSHRzZVNac1k1L3ZGa0FXNXlvanVBUy92OUNCN0VIS2FnSStiUDhMVlFLdm0xa2ZkVytzU2lkL3U4TT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fmetropolis-mini-crossbody-bag-furla%2Fvp%2Fv%3D1%2F1587648439.htm%3Fextid%3DDP_Criteo_US_MV_1587648439%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1587648439&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ffurla%2Ffurla3022792044%2Ffurla3022792044_q1_1-0._QL90_UX336_.jpg&w=400&s=hDBBZ5CnS0wMWq6gkYdckF1d\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Furla Metropolis Mini Cross Body Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A mini Furla cross-body bag in luxe pebbled leather. The polished push-lock includes an optional key for added security. Rolled handle at the fold-over top. Lined interior with 1 notch pocket. Chain shoulder strap. Dust bag included. Leather: Cowhide. Made in Italy. Measurements Height: 5in / 13cm Length: 6.75in / 17cm Depth: 2.75in / 7cm Strap drop: 22.5in / 57cm Handle drop: 2in / 5cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=HGW3S3x0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHVOM3luMVNrSm9FSW5yUlA3WkFnVUN2dXE5dGRneW43V2NPSTQzZ1RRMkNUVVI3Wnh4NndrdTJZM0xXSkdGSUxVUmdmRnJTZlFlVit6OEI5Q2FPd085Wjgya3N3UVh3YzhQQjhvRzFGTXhrOCtIUFNoOXIxT2JCRXdNd1N3NGpnRldiemZ4VVNCOHUxaDZaMmIwRlZTWT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fkanken-backpack-fjallraven%2Fvp%2Fv%3D1%2F1542314646.htm%3Fextid%3DDP_Criteo_US_MV_1542314646%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1542314646&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ffjall%2Ffjall3001355990%2Ffjall3001355990_q1_1-0._QL90_UX336_.jpg&w=400&s=CobbVh2KHNm8ZCvNpU3Arau0\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Fjallraven Kanken Backpack<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A sturdy Fj&#228;llr&#228;ven backpack, detailed with a reflective logo patch and front zip pocket. Patch side pockets offer easy access to essentials, and a 2-way, wraparound zip secures the top. A removable foam panel adds extra protection to the deep, interior patch pocket. Double handles and adjustable shoulder straps. Weight: 8oz / 0.22kg. Imported, Vietnam. MEASUREMENTS Height: 14in / 35.5cm Length: 11in / 28cm Depth: 5in / 12.5cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=NK5a%2BHx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHN0bk4xcHFwSENFb013S0lrSmpsT3VnRlU3eGY0TTZZZkIveUJ6U3doVWtrK0ZCSXA4bWkrL2RtS3MycGR6UUNPRnVta2tqNm9mdEpEQWlzaHZPNEFwS2VBRFJBdlM5L295a2tHb2JjdDBXenhscHZzZnhEbEZJOUNXcVF4VCtKbkpDbGhIQ2ErRTFxbmxVdktIZzdjST18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fmini-love-crossbody-bag-rebecca%2Fvp%2Fv%3D1%2F1533787680.htm%3Fextid%3DDP_Criteo_US_MV_1533787680%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1533787680&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Frmink%2Frmink4316312867%2Frmink4316312867_q1_1-1._QL90_UX336_.jpg&w=400&s=5nXg3MY3YATktTVq0Ib2H3_y\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Rebecca Minkoff Mini Love Cross Body Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A miniature Rebecca Minkoff cross-body bag styled in quilted leather. A slim pocket trims the back, and a turn lock opens the front. Lined, single-pocket interior. Optional shoulder strap. Leather: Cowhide. Weight: 25oz / 0.71kg. Imported, China. Measurements Height: 4.25in / 11cm Length: 6.75in / 17cm Depth: 2.25in / 6cm Strap drop: 22in / 56cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=m5XWyHx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHN0bk4xcHFwSENFb013S0lrSmpsT3UxQk01Z3J0OCtEN0tFV0FRVWlsVVBiOVZaWE5oOVJEYnUrcmJIR0h6RmNkM0JWSW5US0hBTXl6eEs1WGtYQXA0aHhUVEc5ekJTSTd6TElodXF1a3ZFcnZZSURwYkszN053NENkMmRCUmVWQjh0OGt2eDVVRHI1Qk1INkdLNHZiWT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fmicro-crossbody-bag-elizabeth-james%2Fvp%2Fv%3D1%2F1525464394.htm%3Fextid%3DDP_Criteo_US_MV_1525464394%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1525464394&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Felija%2Felija4208212867%2Felija4208212867_q1_1-0._QL90_UX336_.jpg&w=400&s=5mnVf083s7xYsEbJkG0BlsEw\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Elizabeth and James Micro Cross Body Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A petite, pebbled-leather Elizabeth and James cross-body bag provides easy access to daily essentials with 2 exterior pockets. The zip top opens to a lined interior with 1 card pocket. Adjustable strap. Dust bag included. Leather: Lambskin. Weight: 12oz / 0.34kg. Imported, China. Measurements Height: 6in / 15cm Length: 8.25in / 21cm Depth: 1.5in / 4cm Strap drop: 21.25in / 54cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=j%2F4mT3x0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHN0bk4xcHFwSENFb013S0lrSmpsT3Z4WDFKQWhRM3ppS0M3Rm9McTZtUW9MMjYrK0NPVTR2SE9TQTM2dENLLzFtYXVnQjZ2Q3VCOWVWN1RPQnVCSGw5TkwzdlNOcWdBZlY0bll3SDRWZlBrWk1LbnhDUUhrMjQ0VjdhRXFERERvdDFoajBESHN0elBFY3F4UUNvUVZKdz18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fkanken-mini-backpack-fjallraven%2Fvp%2Fv%3D1%2F1502980647.htm%3Fextid%3DDP_Criteo_US_MV_1502980647%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1502980647&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ffjall%2Ffjall3005811279%2Ffjall3005811279_q1_1-0._QL90_UX336_.jpg&w=400&s=EPb7WSeSOvrA7tqUF902BkBD\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Fjallraven Kanken Mini Backpack<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A sturdy Fj&#228;llr&#228;ven backpack, detailed with a reflective logo patch and front zip pocket. Patch side pockets offer easy access to essentials, and a 2-way, wraparound zip secures the top. A removable foam panel adds extra protection to the back. Double handles and adjustable shoulder straps. Fabric: Nylon weave. Weight: 8oz / 0.23kg. Imported, Vietnam. Measurements Height: 11in / 28cm Length: 8in / 20.5cm Depth: 3in / 7.5cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=9qXK5Hx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHJMYnhUbm5xS2ZPN0xBY1FaMVhXQisrNkptdkpLQUtkanBrc095UWE3Q1BwYVVpVmN4V3I2QWRtdHptTktrc2lKcVJZQ0U3MXkrTXcrZmdnQVVvNnJOQ1VkcVB2QjAyclkvYU9INWJPZzRPSlIxYnI2SEs3V05UbUFxK3NvdE5NR21FTVVtMmZiWnN0Z29XeHZVVlVwND18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fvivienne-ring-set-gorjana%2Fvp%2Fv%3D1%2F1565635813.htm%3Fextid%3DDP_Criteo_US_MV_1565635813%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1565635813&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fgorja%2Fgorja4149214583%2Fgorja4149214583_q3_1-0._QL90_UX336_.jpg&w=400&s=-qix68729opjtzExj9rCelj0\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Gorjana Vivienne Ring Set<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A stackable set of 3 Gorjana rings, each with a triangular cubic zirconia insets. 18k gold plate. Imported, China. Size &amp; Fit. Available sizes: 6,7<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=puE%2BHXx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcHN0bk4xcHFwSENFb013S0lrSmpsT3RJQVcrQjdlS1d6d0Zmb3ZtWVhka2JDS2xIdm9qZXY4b2Y3WWtSNFpOTzQxd1NiMUk4T25CWXNxTmdmc2pva2JYbndCc2VJdTUzQUsvOTEzZ3ZKdFEzdkk0QXd5QW1aV0JXcnU5Z0VBNjdMQXI0Ym1NSEdwMndzVTZlS3FkUHJFRT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fmini-mac-crossbody-bag-rose%2Fvp%2Fv%3D1%2F1586432234.htm%3Fextid%3DDP_Criteo_US_MV_1586432234%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1586432234&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Frmink%2Frmink4281812867%2Frmink4281812867_q1_1-0._QL90_UX336_.jpg&w=400&s=JFfyNuZcCxX9_JeB7Ix0vmj0\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Rebecca Minkoff Mini Mac Cross Body Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A classic leather Rebecca Minkoff bag updated with rose-gold tone hardware. A polished buckle secures the flap front pocket, and the zip top opens to a lined, single-pocket interior. Leather: Cowhide. Weight: 23oz / 0.65kg. Imported, China. Measurements Height: 6in / 15cm Length: 9in / 23cm Depth: 2in / 5cm Strap drop: 22in / 56cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"/div>\n";
ifc += "<"+"!-- PRIVACY[BOTTOM:RIGHT] -->\n";
ifc += " <"+"div class=\"footer\" id=\"footer\"> \n";
ifc += "                            <"+"div class=\'privacy\'>\n";
ifc += "                                <"+"a href=\'http://info.criteo.com/pac/privacy/informations?infonorm=2&amp;partner=14830&amp;campaignid=79935&amp;zoneid=352166&amp;bannerid=4082408&amp;displayid=939d6294bc\' target=\'_blank\'><"+"/a>\n";
ifc += "                            <"+"/div> <"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&amp;cpp=zXap3Xx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWnNiRXdIZWhValVoMTV1dUVBeTgxcGh1OGttOWZVOTBvdmJuWjFYbnpvVmdHOGlNMEVXT3ZCYnBjTksxelU1TnV1MGNpbHZXazJNNlMyZnJyQnRDcTRWczh6S3dUMEFEeUdXZkpMVFIvcmw2dVBNYm0yaTdtZWJXZzR5Um5mTkpwOTFVTDRQdTcvQUgwSWI2RWxnaWJmUT09fA%3D%3D&amp;maxdest=http%3A%2F%2Fwww.shopbop.com%2F%3Fextid%3DDP_Criteo_US_MV_%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" id=\"adUrl\" class=\"adUrl\" >Advertisement | shopbop.com<"+"/a> <"+"span id=\"legal\" class=\"legal\" onmouseover=\"javascript:display_hide(\'legalover\');\"><"+"/span> <"+"/div> <"+"div id=\"legalover\" class=\"legalover\" onmouseout=\"javascript:display_hide(\'legalover\');\"><"+"/div>\n";
ifc += " <"+"/div>\n";
ifc += "<"+"style>#cto_banner_content .privacy {\n";
ifc += "                    width:77px;\n";
ifc += "                    float:right;\n";
ifc += "                    text-align:right;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a {\n";
ifc += "                    display:inline-block;\n";
ifc += "                    width:19px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_small.png);\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a:hover {\n";
ifc += "                    width:77px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_big.png);\n";
ifc += "                }<"+"/style>\n";
ifc += "<"+"script type=\'text/javascript\'>(function() { var arrayEquals = function (a, b) {\n";
ifc += "                if(a.length != b.length) return false;\n";
ifc += "                a = a.sort();\n";
ifc += "                b = b.sort();\n";
ifc += "                for(var i = 0; i <"+" a.length; ++i) {\n";
ifc += "                    if (a[i] != b[i]) return false;\n";
ifc += "                }\n";
ifc += "                return true;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var arrayIterate = function (a, fct) {\n";
ifc += "                var len = a.length;\n";
ifc += "                for(var i = 0; i <"+" len; ++i) {\n";
ifc += "                    fct(a[i], i); \n";
ifc += "                }\n";
ifc += "             };\n";
ifc += "   \n";
ifc += "            var arrayWhere = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    if(fct(elt, index)) b.push(elt);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "             };\n";
ifc += "      \n";
ifc += "            var arrayMap = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    b[index] = fct(elt, index);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var multilineEllipsis = function (div) {\n";
ifc += "                var t = div.textContent || div.innerText;\n";
ifc += "                var d = document.createElement(\'div\');\n";
ifc += "                var i = 0;    \n";
ifc += "                d.style.width = div.offsetWidth + \'px\';\n";
ifc += "                d.style.visibility = \"hidden\";\n";
ifc += "                div.appendChild(d);\n";
ifc += "\n";
ifc += "                while(d.offsetHeight <"+"= div.offsetHeight && i <"+" t.length) {\n";
ifc += "                    d.textContent = d.innerText = t.substr(0, i) + \'...\';\n";
ifc += "                    ++i;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                div.removeChild(d);\n";
ifc += "                if(i != t.length) div.textContent = div.innerText = t.substr(0, i-2) + \'...\';\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            (function() {\n";
ifc += "                var c = document.getElementById(\'cto_banner_content\');\n";
ifc += "                var isMultilineEllipsis = function(elt) { return elt.getAttribute(\'data-ellipsis\') == \'multiline\'; };\n";
ifc += "                arrayIterate(arrayWhere(c.getElementsByTagName(\'*\'), isMultilineEllipsis), multilineEllipsis);\n";
ifc += "            })(); })();<"+"/script>\n";
ifc += "<"+"script type=\"text/javascript\">\n";
ifc += "var legal = document.getElementById(\"legal\");\n";
ifc += "if(legal.innerText == \"\"){legal.style.display=\"none\";}\n";
ifc += "else {document.getElementById(\"adUrl\").style.maxWidth=\"65px\";} function display_hide(id) { var legalLength = legal.innerHTML.length; var element = document.getElementById(id); if(element===null) return false; if((element.style.visibility==\"hidden\") && (legalLength > 10)){ element.style.visibility=\"visible\"; } else { element.style.visibility=\"hidden\"; } return true;\n";
ifc += "} (function() { var getElts = function(className, domElem) { var desc = []; if (document.getElementsByClassName) { desc = domElem.getElementsByClassName(className); } else { var elem = domElem.getElementsByTagName(\'*\'); for (var x = 0; x <"+" elem.length; x++) { if ((\' \' + elem[x].className + \' \').indexOf(\' \' + className + \' \') > -1) desc.push(elem[x]); } } return desc; }; var truncate = function(div, maxCharacter) { var t = div.textContent || div.innerText || \"\"; var trimmed = t.replace(\'\\n\', \'\').replace(/^ +| +$/g, \'\'); if(trimmed.length > maxCharacter) div.textContent = div.innerText = trimmed.substr(0, maxCharacter-3) + \'...\'; }; var products = getElts(\"cto_product\", document); for(var x = 0; x <"+" products.length; ++x) { var price = getElts(\"priceDesc\", products[x])[0]; var priceType = getElts(\"priceType\", price)[0]; var priceNumber = getElts(\"price\", price)[0]; var priceOrig = getElts(\"origPrice\", price)[0]; var priceTypeText = priceType.textContent || priceType.innerText || \"\"; if (priceNumber.innerHTML == \"\" || priceNumber.innerHTML.length > 14) { price.removeChild(priceOrig); price.removeChild(priceType); price.removeChild(priceNumber); } else if (priceTypeText.indexOf(\"__\") == 0) { var altprice = priceTypeText.replace(/_/g, \"\"); priceType.innerHTML = altprice; price.removeChild(priceOrig); } else if (priceTypeText == \"rrp\") { price.removeChild(priceType); } }\n";
ifc += "})(); <"+"/script><"+"/div><"+"div style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"iframe id=\'if939d6294bc\' name=\'if939d6294bc\' width=\'1px\' height=\'1px\'><"+"/iframe>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div id=\'beacon_939d6294bc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"img width=\"0\" height=\"0\" src=\"http://shopbop.sp1.convertro.com/view/vt/v1/shopbop/1/cvo.gif?cvosrc=retargeting.criteo.Shop%20Bop%20US%20MV&cvo_placement=&cvo_creative=&cvo_cid=79935\"/>\n";
ifc += "<"+"img width=\"0\" height=\"0\" src=\"http://cat.ny.us.criteo.com/delivery/lg.php?cppv=1&cpp=L0FiInx0enJLUzhMa3JIaC9HSzBSaHUrbENyVmptWHhDVzV0Z1F2MzBEaTQ1Tnc0eUN3d0ZHbGV4dzNlVFhUU1lxdTNnSEdlTjJHZ1FlcmRYQ1l3ME13bE1jZ0ZaVE9uTk1jV2w0SG5SZW83TU9tK005VTlnYVFxK29Bd0x2b2Vkck5mWkozSmNTOVQwWnZvTEhPRFhQTUEwVnNQTjdQWkZ2TG5DYjBWV3Y1UUdlOGdnZTZZempBb0Z1U1ZaRFg5ZS9yQm14ZkJqUytjUlV0VUo5N0hZbEpQWTJYaU1reEhHK2tWMUM5WStibXkwQ2RwMnhOc3ZVdFlWZjIyREkzbEJ1NzNNSTYxbFJzaHdkcTk4ZllZOFJWTWQreDZrb2FyaXkxZWRINWszang1K1lOZz18\"/>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/body>\n";
ifc += "<"+"/html>\n";

var fillIframe = function(ifrd) {
    var getDocument = function(iframe) {
        var result_document = iframe.contentWindow || iframe.contentDocument;
        if (result_document && result_document.document)
            result_document = result_document.document;
        return result_document;
    };
    var c = getDocument(ifrd);
    if (c) {
        c.open();
        c.write(ifc);
        c.close();
    }
};


var maxRetryAttempts = 100;
var loaded = false;
var pollIframe = function() {
    var ifrd = document.getElementById('cto_iframe_939d6294bc');
    if (ifrd && isIE) {
         ifrd.onload = function() {
            if(!loaded) {
                loaded = true;
                fillIframe(ifrd);
            }
        };
    } else if (ifrd) {
        loaded = true;
        fillIframe(ifrd);
    } else if (maxRetryAttempts-- > 0) {
        setTimeout(pollIframe, 10);
    }
};pollIframe();})();
