(function(){
var isIE = window.navigator.userAgent.indexOf("MSIE ") > 0;
var ifr = document.createElement('iframe');
ifr.setAttribute('id', 'cto_iframe_1cff9b3b5a');
ifr.setAttribute('frameBorder', 0);
ifr.setAttribute('allowtransparency', true);
ifr.setAttribute('hspace', 0);
ifr.setAttribute('marginwidth', 0);
ifr.setAttribute('marginheight', 0);
ifr.setAttribute('scrolling', 'no');
ifr.setAttribute('vspace', 0);
ifr.setAttribute('width', '970px');
ifr.setAttribute('height', '90px');

var container = document.getElementById('dfp-tag-horizontal-position-1');
if (container) { container.appendChild(ifr); }
var ifc = "\n";
ifc += "<"+"!DOCTYPE html>\n";
ifc += "<"+"html>\n";
ifc += "  <"+"head>\n";
ifc += "    <"+"meta name=\"format-detection\" content=\"telephone=no\"><"+"meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n";
ifc += "  <"+"/head>\n";
ifc += "  <"+"body><"+"div id=\'cto_banner_content\'><"+"style>\n";
ifc += "#cto_products .cto_product .imgholder{ text-align : center; background : #ffffff; float : left; margin-right : 7px; width : 71px; height : 71px;\n";
ifc += "} #cto_products .cto_product .imgholder img{ border : none; max-width : 71px; max-height : 71px; *width : expression(this.width >= this.height ? \"71px\" : \"auto\"); *height : expression(this.width <"+" this.height ? \"71px\" : \"auto\");\n";
ifc += "} #cto_products .cto_product .title{ overflow : hidden; color : #016090; font-size : 14px; height : 18px; line-height : 16px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product .desc{ overflow : hidden; color : #646464; font-size : 12px; height : 30px; line-height : 14px;\n";
ifc += "} #cto_products .cto_product .priceDesc{ color : #FF9900; font-size : 16px; height : 24px; line-height : 20px; font-weight : bold;\n";
ifc += "} #cto_products .cto_product .priceDesc .origPrice{ color : #999; font-size : 13px; height : 18px; line-height : 16px; font-weight : normal;\n";
ifc += "} #cto_products .cto_product .details{ float : left; width : 243px;\n";
ifc += "} #cto_products .cto_product *{ *cursor : pointer;\n";
ifc += "} #cto_products .cto_product a{ color : black; text-decoration : none;\n";
ifc += "} #cto_bannerContent{ width : 970px; height : 90px; background : #ffffff; position : relative; font-family : Arial,sans-serif; font-size : 0; overflow : hidden;\n";
ifc += "} #cto_products{ height : 73px; width : 970px; overflow : hidden;\n";
ifc += "} #cto_products .cto_product{ width : 321px; height : 71px; float : left; text-align : left; overflow : hidden; vertical-align : top; zoom : 1; position : relative; *zoom : 1; *display : inline; margin : 1px 1px 1px 1px;\n";
ifc += "} #cto_products .cto_product:hover{ background : #eeeeee;\n";
ifc += "} #cto_bannerContent .footer{ height : 17px; line-height : 16px; position : relative; text-align : left;\n";
ifc += "} #cto_bannerContent .adUrl{ font-size : 11px; color : #808080; text-decoration : none; cursor : pointer; *cursor : pointer; zoom : 1; vertical-align : top; margin-right : 4px; display : inline-block; *display : inline; margin-left : 4px; line-height : 17px;\n";
ifc += "} #cto_bannerContent .adUrl:hover{ text-decoration : underline;\n";
ifc += "} #cto_bannerContent .legal{ text-overflow : ellipsis; white-space : nowrap; overflow : hidden; font-size : 11px; color : #808080; display : inline-block; *display : inline; height : 16px; width : 323.3333333333333px;\n";
ifc += "} #cto_bannerContent .legalover{ position : absolute; left : 1px; box-sizing : border-box; font-size : 11px; color : #808080; text-decoration : none; display : block; zoom : 1; padding : 4px; background : #eee; opacity : 0.95; filter : alpha(opacity=95); visibility : hidden; line-height : 12px; width : 970px; bottom : 1px;\n";
ifc += "} <"+"/style>\n";
ifc += "<"+"div id=\"cto_bannerContent\">\n";
ifc += "<"+"div id=\"cto_products\">\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=E0s11nxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTGJwNXA2SVV5emVIQ2FnaWVvdURFeUJZekhOOWhseThnN3VUNmZvSVh4MC84Q2JwU2IzRUNyN2ZXazdkZWdKWWw3dWp4Vzhpdm5oUUZoSVF2ekloa2hvU3ZHcHF6NmYrdTZRTmxTa3hxWkdpSWtTR1E5cXdwMnhwcW84djM4YXhDdUFyV1pMbE56cmJPaWpYTC9vSjBsYz18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fclassic-mini-pocket-t-by%2Fvp%2Fv%3D1%2F845524441847683.htm%3Fextid%3DDP_Criteo_US_MV_845524441847683%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-845524441847683&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ftwang%2Ftwang2002512867%2Ftwang2002512867_q1_1-1._QL90_UX336_.jpg&w=400&s=NpAIB3T9rIEur4LDPX1-jXst\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">T by Alexander Wang Classic T Shirt with Pocket<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">This scoop-neck tee features a patch bust pocket and short sleeves. Semi-sheer. Fabric: Jersey. 100% rayon. Hand wash. Imported, Vietnam. Measurements Length: 26in / 66cm, from shoulder Measurements from size S. Available sizes: L,M,S,XS<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=WCaTRXxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFhUVCsyVWE1YTFCb0MvK2Frc1FJMXN1ajhGZEFoa3prSHFocFR2cTdKampoKzMyc0RVRTdJN0daNzlGcU4zMWwwbVdsMU8wTmNDdGdvOFRGMDhDZzd5aHVvZ1VMK2RpVDNNTm9ZT0lkT0NYNHFDTkJDb1hMT1RKSHFNSDFjV1BrbFpXSTdDcWxmY3k3MnlTT3dCR2tPND18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fembroidered-saddle-bag-one-by%2Fvp%2Fv%3D1%2F1540258666.htm%3Fextid%3DDP_Criteo_US_MV_1540258666%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1540258666&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Foneby%2Foneby2060012867%2Foneby2060012867_q1_1-0._QL90_UX336_.jpg&w=400&s=IgsxFuaKSONBj8GHtfJ8wGp3\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">ONE by Type Alpha Embroidered Saddle Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">Description Type Alpha is a creative, New York-based sourcing agency that is part of Shopbop&#8217;s ONE by collection. ONE by is home to exceptional pieces from established and emerging designers. Beads and tassels bring bohemian flair to this faux-suede cross-body bag. A snap secures the top flap, and the self-lined interior has 2 pockets. Zip closure. Adjustable shoulder strap. Dust bag included. Fabric: Faux suede. Weight: 12oz / 0.34kg. Imported, India. Measurements Height: 9in / 23cm Length: 8in<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=pn%2F9I3xuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFkzNzJVcGZKRm9NeTlOTW5BcnVWRk1KdUVtNkplS0lnRmhSQ3BrVGR1bGs0RVBCRUc5bzNvOUdUeExMQXhrZmxOUWpyU0Zxa2YrWU9jakFFa3l2WU9oMUpKTy9ybnZucTdRZGkyTG1GQTYyY1NMd1dhR0tpbFAwejNPOThHWElhbmNUd2h5UmpudE1GZSszZStvTWxuMD18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fkanken-backpack-fjallraven%2Fvp%2Fv%3D1%2F1531461443.htm%3Fextid%3DDP_Criteo_US_MV_1531461443%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1531461443&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Ffjall%2Ffjall3004157661%2Ffjall3004157661_q1_1-1._QL90_UX336_.jpg&w=400&s=WORGwhKRs_lY1eL4k-Atx2aj\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Fjallraven Kanken Backpack<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A sturdy Fj&#228;llr&#228;ven backpack, detailed with a front logo patch and zip pocket. Patch side pockets add versatility. A two-way zip secures the single-pocket interior. Adjustable shoulder straps. Fabric: Rigid technical weave. Weight: 11oz / 0.31kg. Imported, China. Measurements Height: 13.75in / 35cm Length: 11in / 28cm Depth: 4.75in / 12cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=NusA6nxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFhUVCsyVWE1YTFCb0MvK2Frc1FJMXZEQ0NCY3RIMkREdkQzdk91Vy9abWxQMENHcEhUM1B0Umtqb21hbU1NMmFhSUZqTG1sdnZ6ZXVGSmF0WENuOXBQcklTV1BTVXpUNTd4L0FsVWl4Tml1RGo4OVlFSEZDR0NsNWdXTkUyUGYrdXYwMWRndEhUTTJRS2hYWXV6ZWp2UT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fselma-medium-messenger-michael-kors%2Fvp%2Fv%3D1%2F1549915017.htm%3Fextid%3DDP_Criteo_US_MV_1549915017%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1549915017&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fmmkor%2Fmmkor2006412867%2Fmmkor2006412867_q1_1-0._QL90_UX336_.jpg&w=400&s=YNnwx0IiaEUWyQezLSHgDxdA\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">MICHAEL Michael Kors Selma Medium Messenger Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">Sturdy saffiano leather and gold-tone hardware bring professional polish to this MICHAEL Michael Kors satchel. The inset top zip opens to a logo-lined interior with 1 pocket and a spring-lock keychain. Optional, adjustable shoulder strap. Dust bag included. Leather: Cowhide. Weight: 19oz / 0.54kg. Imported, China. Measurements Height: 6.75in / 17cm Length: 9in / 23cm Depth: 4in / 10cm Strap drop: 22in / 56cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=PqomGnxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFhUVCsyVWE1YTFCb0MvK2Frc1FJMXRRZnprOTNpVkhXdXpDRnVSbVZ4Y0d3ZU1qYWwwNlQ1Z1h1c0dLelg5VVBiM01rQTduOGllNUQzdTNpekZnaXM2dGVvU1NUTThZNzRVbGx0eHJ5bFdFTmpad0NSR3Y5cFRVT20wMzMvdXJITStRclBlcnE5MmY0VTk4bzJiMm02az18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Favery-crossbody-bag-rebecca-minkoff%2Fvp%2Fv%3D1%2F1523514423.htm%3Fextid%3DDP_Criteo_US_MV_1523514423%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1523514423&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Frmink%2Frmink4317012867%2Frmink4317012867_q1_1-0._QL90_UX336_.jpg&w=400&s=IXpZGIG8WRP_BOU2RpYUQwMj\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Rebecca Minkoff Avery Cross Body Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">Saffiano leather constructs this chic Rebecca Minkoff bag. Slim tassels accent the front zip pockets. Metal feet protect the bottom. Optional chain shoulder strap. Lined, single-pocket interior. Leather: Cowhide. Weight: 19oz / 0.54kg. Imported, China. Measurements Height: 6.75in / 17cm Length: 9in / 23cm Depth: 2in / 5cm Strap drop: 21.75in / 55cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=NVC6anxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFhUVCsyVWE1YTFCb0MvK2Frc1FJMXQ0SjVmdEhJTW5BV2ovaVpBS0NaTTd3aGZwRDRUNngyNjUxZUs3dHBrckpTNXRFWUlqQmhqN1VmMk9hekhXLzJCR3JFYm1RZGRrMVBtSzI3U3BTaTh6Qmg4ZlF0a3VoaDhtVWtTbXdZcnBPTnY0ektLdEdqS0k4a25STDkxSkpLaz18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fquilted-mini-affair-bag-rebecca%2Fvp%2Fv%3D1%2F1591199379.htm%3Fextid%3DDP_Criteo_US_MV_1591199379%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1591199379&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Frmink%2Frmink4174012867%2Frmink4174012867_q1_1-0._QL90_UX336_.jpg&w=400&s=JiKyi-n8zW4gXEqlcH2igFGv\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Rebecca Minkoff Quilted Mini Affair Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">Rich quilted leather puts a luxurious finish on this petite, classic Rebecca Minkoff bag. Interwoven leather traces the polished gold-tone chain strap, which can be worn long or doubled, and the flap top opens to a logo-lined interior with a single pocket. Leather: Cowhide. Weight: 16oz / 0.45kg. Imported, China. Measurements Height: 6in / 15cm Length: 9in / 23cm Depth: 2in / 5cm Strap drop: 22in / 56cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=0FbDpXxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFhUVCsyVWE1YTFCb0MvK2Frc1FJMXMyRWVIYWFMVlZYa2t2NEMydVVLTGl2MzMwZE91R3pjVVJjT2Y3RndqNzBZZ0lST1BJUW5LYm95b1Q5THNEd053d3RGOHpvc0wxSW15c3RmbmdPRkhlTDdINDJKT21VL2N2NkFXUFVFRVdVUTB4dEhZRTNJR1U3ZU5uWHVQVzRKZz18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fmicro-crossbody-bag-elizabeth-james%2Fvp%2Fv%3D1%2F1525464394.htm%3Fextid%3DDP_Criteo_US_MV_1525464394%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1525464394&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Felija%2Felija4208212867%2Felija4208212867_q1_1-0._QL90_UX336_.jpg&w=400&s=5mnVf083s7xYsEbJkG0BlsEw\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Elizabeth and James Micro Cross Body Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A petite, pebbled-leather Elizabeth and James cross-body bag provides easy access to daily essentials with 2 exterior pockets. The zip top opens to a lined interior with 1 card pocket. Adjustable strap. Dust bag included. Leather: Lambskin. Weight: 12oz / 0.34kg. Imported, China. Measurements Height: 6in / 15cm Length: 8.25in / 21cm Depth: 1.5in / 4cm Strap drop: 21.25in / 54cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=z7lQvHxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTGJwNXA2SVV5emVIQ2FnaWVvdURFeUEvUDMvSjRkbk1rc1c4NUNzcEEwMnBRRjlSMlNiRW4wRW90ZmV6MUtxaGtxdmtveGpDNkNESmtLMC93bFJDWlpSRWtIU1dQOWVkT0NtMyt5b0RkcFJINHZqYkdUTEE2RGgvdGZMUHliRFhINGhTaXhjaVFvZ1FXdHJUNVE0Rm43WT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fsimonia-blouse-diane-von-furstenberg%2Fvp%2Fv%3D1%2F1592128989.htm%3Fextid%3DDP_Criteo_US_MV_1592128989%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1592128989&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fdiavf%2Fdiavf4383787591%2Fdiavf4383787591_q1_1-0._QL90_UX336_.jpg&w=400&s=PNWJ1UvAuh1iQUCFwpCvLXaC\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Diane von Furstenberg Simonia Blouse<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">An airy silk DVF blouse in a floral print. Ties close the keyhole, and frayed ruffles trim the front. Sheer sleeves with flared cuffs. Lined. Fabric: Crinkled silk chiffon. Shell: 100% silk. Lining: 100% polyester. Dry clean. Imported, China. Measurements Length: 23.5in / 60cm, from shoulder Measurements from size 4. Available sizes: 10<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=hdE7WHxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFhUVCsyVWE1YTFCb0MvK2Frc1FJMXZjemZaci9KSG9VcEU5TU55Rng5SVJlVFhCWSt0TzdGQXBiTTlzVS81TmVEamw4cTJnQ0xXeDZlZ0IvS0lqcjdXSGhUbDY5WjZ4dVBSb0VRTHFuRzRSM0Y0K2d4VThING1mMk11c1dqbHZlT1ZVRUtRWWpNazVYTUNXWXUzLzhJQT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fmab-mini-tote-rebecca-minkoff%2Fvp%2Fv%3D1%2F1530512737.htm%3Fextid%3DDP_Criteo_US_MV_1530512737%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1530512737&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Frmink%2Frmink4193512867%2Frmink4193512867_q1_1-0._QL90_UX336_.jpg&w=400&s=ZqqE4Ml_CM_alwtdyWF38Ctd\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Rebecca Minkoff MAB Mini Tote<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A scaled-down version of Rebecca Minkoff\'s signature MAB tote. A tassel pull closes the zip front pocket, and a magnetic snap secures the top. Lined, one-pocket interior. Gold-tone hardware. Rolled handles and detachable shoulder strap. Leather: Cowhide. Weight: 14oz / 0.4kg. Imported, China. Measurements Height: 7in / 18cm Length: 8in / 20.5cm Depth: 3in / 7.5cm Strap drop: 22in / 56cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"div class=\"cto_product\">\n";
ifc += "<"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&cpp=gU21VXxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFhUVCsyVWE1YTFCb0MvK2Frc1FJMXZzb2RmZmVEZmExN0UwVDVGN3NQWVNDRHZGOHdLbFF5WnRZK0dSSDQrNlE1dG10VTR1T2JLMzg4RHI3R2RDb1NMOUpQb2U0L2QvUEs5Sk5Sdnc0QXlKdEFjV0phbEJRaXc2QXFGNjNEdmdaWTUrNG1Ld3lldjJFQWJqN1Nzcis3RT18&maxdest=https%3A%2F%2Fwww.shopbop.com%2Fnano-envelope-bag-sophie-hulme%2Fvp%2Fv%3D1%2F1597677212.htm%3Fextid%3DDP_Criteo_US_MV_1597677212%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" >\n";
ifc += "<"+"div class=\"imgholder\">\n";
ifc += "<"+"img src=\"http://pix.ny.us.criteo.net/img/img?h=400&i=14830-1597677212&m=0&q=80&r=0&u=https%3A%2F%2Fimages-na.ssl-images-amazon.com%2Fimages%2FG%2F01%2FShopbop%2Fp%2Fpcs%2Fproducts%2Fsophi%2Fsophi3013412867%2Fsophi3013412867_q1_1-0._QL90_UX336_.jpg&w=400&s=fJnFyk_2eCgp9LI6aA-oAawM\">\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div class=\"details\">\n";
ifc += "<"+"div class=\"title\" data-ellipsis=\"multiline\">Sophie Hulme Nano Envelope Bag<"+"/div>\n";
ifc += "<"+"div class=\"desc\" data-ellipsis=\"multiline\">A scaled-down Sophie Hulme bag in smooth leather. A polished buckle secures the top flap. Unlined interior with 1 pocket. Optional, adjustable shoulder strap. Dust bag included. Leather: Cowhide. Weight: 8oz / 0.23kg. Made in Italy. Measurements Height: 4.25in / 11cm Length: 5.75in / 14.5cm Depth: 2.25in / 5.5cm Strap drop: 23.5in / 60cm. Available sizes: One Size<"+"/div>\n";
ifc += "<"+"div class=\"priceDesc\">\n";
ifc += "<"+"span class=\"priceType\">rrp<"+"/span>\n";
ifc += "<"+"del class=\"origPrice\"><"+"/del>\n";
ifc += "<"+"span class=\"price\"><"+"/span>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/a>\n";
ifc += "<"+"/div>\n";
ifc += "\n";
ifc += "<"+"/div>\n";
ifc += "<"+"!-- PRIVACY[BOTTOM:RIGHT] -->\n";
ifc += " <"+"div class=\"footer\" id=\"footer\"> \n";
ifc += "                            <"+"div class=\'privacy\'>\n";
ifc += "                                <"+"a href=\'http://info.criteo.com/pac/privacy/informations?infonorm=2&amp;partner=14830&amp;campaignid=79935&amp;zoneid=352168&amp;bannerid=4082408&amp;displayid=1cff9b3b5a\' target=\'_blank\'><"+"/a>\n";
ifc += "                            <"+"/div> <"+"a href=\"http://cat.ny.us.criteo.com/delivery/ck.php?cppv=1&amp;cpp=pwGMfXxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmpHWUU0KzA5b0FWZGN3eE4yQkFxTFc2M2k2ZmR5M2J0ZlU1WXViYm9hS3o3aDVoSzZoNEtSc0pUbDJxNVZmYWdiQzc2WloxMUpkZXIzVE1DUTB0Zm1uQ05sa0ZnZmdqMmoraStNSTNvVm9JRWw3dFJaamRjd2s4RElQTnJPcGxGN3dLalBzQ3l6elROOTNka1ovU0VIZz09fA%3D%3D&amp;maxdest=http%3A%2F%2Fwww.shopbop.com%2F%3Fextid%3DDP_Criteo_US_MV_%26currencyCode%3DUSD%26cvosrc%3Dretargeting.criteo.Shop%2520Bop%2520US%2520MV%26cvo_cid%3D79935\" target=\"_blank\" id=\"adUrl\" class=\"adUrl\" >Advertisement | shopbop.com<"+"/a> <"+"span id=\"legal\" class=\"legal\" onmouseover=\"javascript:display_hide(\'legalover\');\"><"+"/span> <"+"/div> <"+"div id=\"legalover\" class=\"legalover\" onmouseout=\"javascript:display_hide(\'legalover\');\"><"+"/div>\n";
ifc += " <"+"/div>\n";
ifc += "<"+"style>#cto_banner_content .privacy {\n";
ifc += "                    width:77px;\n";
ifc += "                    float:right;\n";
ifc += "                    text-align:right;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a {\n";
ifc += "                    display:inline-block;\n";
ifc += "                    width:19px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_small.png);\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                #cto_banner_content .privacy a:hover {\n";
ifc += "                    width:77px;\n";
ifc += "                    height:15px;\n";
ifc += "                    background-image:url(http://static.eu.criteo.net/flash/icon/nai_big.png);\n";
ifc += "                }<"+"/style>\n";
ifc += "<"+"script type=\'text/javascript\'>(function() { var arrayEquals = function (a, b) {\n";
ifc += "                if(a.length != b.length) return false;\n";
ifc += "                a = a.sort();\n";
ifc += "                b = b.sort();\n";
ifc += "                for(var i = 0; i <"+" a.length; ++i) {\n";
ifc += "                    if (a[i] != b[i]) return false;\n";
ifc += "                }\n";
ifc += "                return true;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var arrayIterate = function (a, fct) {\n";
ifc += "                var len = a.length;\n";
ifc += "                for(var i = 0; i <"+" len; ++i) {\n";
ifc += "                    fct(a[i], i); \n";
ifc += "                }\n";
ifc += "             };\n";
ifc += "   \n";
ifc += "            var arrayWhere = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    if(fct(elt, index)) b.push(elt);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "             };\n";
ifc += "      \n";
ifc += "            var arrayMap = function (a, fct) {\n";
ifc += "                b = [];\n";
ifc += "                arrayIterate(a, function(elt, index) {\n";
ifc += "                    b[index] = fct(elt, index);\n";
ifc += "                });\n";
ifc += "                return b;\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            var multilineEllipsis = function (div) {\n";
ifc += "                var t = div.textContent || div.innerText;\n";
ifc += "                var d = document.createElement(\'div\');\n";
ifc += "                var i = 0;    \n";
ifc += "                d.style.width = div.offsetWidth + \'px\';\n";
ifc += "                d.style.visibility = \"hidden\";\n";
ifc += "                div.appendChild(d);\n";
ifc += "\n";
ifc += "                while(d.offsetHeight <"+"= div.offsetHeight && i <"+" t.length) {\n";
ifc += "                    d.textContent = d.innerText = t.substr(0, i) + \'...\';\n";
ifc += "                    ++i;\n";
ifc += "                }\n";
ifc += "\n";
ifc += "                div.removeChild(d);\n";
ifc += "                if(i != t.length) div.textContent = div.innerText = t.substr(0, i-2) + \'...\';\n";
ifc += "            };\n";
ifc += "\n";
ifc += "            (function() {\n";
ifc += "                var c = document.getElementById(\'cto_banner_content\');\n";
ifc += "                var isMultilineEllipsis = function(elt) { return elt.getAttribute(\'data-ellipsis\') == \'multiline\'; };\n";
ifc += "                arrayIterate(arrayWhere(c.getElementsByTagName(\'*\'), isMultilineEllipsis), multilineEllipsis);\n";
ifc += "            })(); })();<"+"/script>\n";
ifc += "<"+"script type=\"text/javascript\">\n";
ifc += "var legal = document.getElementById(\"legal\");\n";
ifc += "if(legal.innerText == \"\"){legal.style.display=\"none\";}\n";
ifc += "else {document.getElementById(\"adUrl\").style.maxWidth=\"65px\";} function display_hide(id) { var legalLength = legal.innerHTML.length; var element = document.getElementById(id); if(element===null) return false; if((element.style.visibility==\"hidden\") && (legalLength > 10)){ element.style.visibility=\"visible\"; } else { element.style.visibility=\"hidden\"; } return true;\n";
ifc += "} (function() { var getElts = function(className, domElem) { var desc = []; if (document.getElementsByClassName) { desc = domElem.getElementsByClassName(className); } else { var elem = domElem.getElementsByTagName(\'*\'); for (var x = 0; x <"+" elem.length; x++) { if ((\' \' + elem[x].className + \' \').indexOf(\' \' + className + \' \') > -1) desc.push(elem[x]); } } return desc; }; var truncate = function(div, maxCharacter) { var t = div.textContent || div.innerText || \"\"; var trimmed = t.replace(\'\\n\', \'\').replace(/^ +| +$/g, \'\'); if(trimmed.length > maxCharacter) div.textContent = div.innerText = trimmed.substr(0, maxCharacter-3) + \'...\'; }; var products = getElts(\"cto_product\", document); for(var x = 0; x <"+" products.length; ++x) { var price = getElts(\"priceDesc\", products[x])[0]; var priceType = getElts(\"priceType\", price)[0]; var priceNumber = getElts(\"price\", price)[0]; var priceOrig = getElts(\"origPrice\", price)[0]; var priceTypeText = priceType.textContent || priceType.innerText || \"\"; if (priceNumber.innerHTML == \"\" || priceNumber.innerHTML.length > 14) { price.removeChild(priceOrig); price.removeChild(priceType); price.removeChild(priceNumber); } else if (priceTypeText.indexOf(\"__\") == 0) { var altprice = priceTypeText.replace(/_/g, \"\"); priceType.innerHTML = altprice; price.removeChild(priceOrig); } else if (priceTypeText == \"rrp\") { price.removeChild(priceType); } }\n";
ifc += "})(); <"+"/script><"+"/div><"+"div style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"iframe id=\'if1cff9b3b5a\' name=\'if1cff9b3b5a\' width=\'1px\' height=\'1px\'><"+"/iframe>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"div id=\'beacon_1cff9b3b5a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
ifc += "<"+"img width=\"0\" height=\"0\" src=\"http://shopbop.sp1.convertro.com/view/vt/v1/shopbop/1/cvo.gif?cvosrc=retargeting.criteo.Shop%20Bop%20US%20MV&cvo_placement=&cvo_creative=&cvo_cid=79935\"/>\n";
ifc += "<"+"img width=\"0\" height=\"0\" src=\"http://cat.ny.us.criteo.com/delivery/lg.php?cppv=1&cpp=f6BwGXxuQUsyR2M5MHRaTFZBaDFaMUU0cHMrMmtRRE4yVGtiVFNReDdPRjlZTWdlRTU2ZUlOc0daR3lhVS9rb2szbzY1ZFYyeDEyd1VDNlE1bk9TK0pXSmRGUVlMR2FONEorOXpSRjY2T2V6clpBR2F3blBuKzk2am1BV0NxTWxwMHQrNmhzaXpoTXVPbFh4VFRpLzlucnVjUUZWRVR0RUcrYVZOMnE0bGNMWW5hZVlkcCthY1RFa2xUTFEyRDl5YkNEZ2FmOTVYcmUrQ2VtMWJKc3Q5eHZIZ0R1L3RlaUdiU0tpcmVZWHQ2bHowNEtYUlRPMHhDU1p1NHF5cFhFVjA1S2ZZb1puWVQ0S1NUdXk1VlF6Zm9FUXVjaVNGbFF4WGJrM3Nob3p3RENWSGZjND18\"/>\n";
ifc += "<"+"/div>\n";
ifc += "<"+"/body>\n";
ifc += "<"+"/html>\n";

var fillIframe = function(ifrd) {
    var getDocument = function(iframe) {
        var result_document = iframe.contentWindow || iframe.contentDocument;
        if (result_document && result_document.document)
            result_document = result_document.document;
        return result_document;
    };
    var c = getDocument(ifrd);
    if (c) {
        c.open();
        c.write(ifc);
        c.close();
    }
};


var maxRetryAttempts = 100;
var loaded = false;
var pollIframe = function() {
    var ifrd = document.getElementById('cto_iframe_1cff9b3b5a');
    if (ifrd && isIE) {
         ifrd.onload = function() {
            if(!loaded) {
                loaded = true;
                fillIframe(ifrd);
            }
        };
    } else if (ifrd) {
        loaded = true;
        fillIframe(ifrd);
    } else if (maxRetryAttempts-- > 0) {
        setTimeout(pollIframe, 10);
    }
};pollIframe();})();
