var $jscomp={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return"jscomp_symbol_"+a+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();if(a[$jscomp.global.Symbol.iterator])return a[$jscomp.global.Symbol.iterator]();var c=0;return{next:function(){return c==a.length?{done:!0}:{done:!1,value:a[c++]}}}};
$jscomp.arrayFromIterator=function(a){for(var c,b=[];!(c=a.next()).done;)b.push(c.value);return b};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
$jscomp.inherits=function(a,c){function b(){}b.prototype=c.prototype;a.prototype=new b;a.prototype.constructor=a;for(var d in c)if($jscomp.global.Object.defineProperties){var e=$jscomp.global.Object.getOwnPropertyDescriptor(c,d);e&&$jscomp.global.Object.defineProperty(a,d,e)}else a[d]=c[d]};$jscomp.array=$jscomp.array||{};$jscomp.array.done_=function(){return{done:!0,value:void 0}};
$jscomp.array.arrayIterator_=function(a,c){a instanceof String&&(a=String(a));var b=0;$jscomp.initSymbol();$jscomp.initSymbolIterator();var d={},e=(d.next=function(){if(b<a.length){var d=b++;return{value:c(d,a[d]),done:!1}}e.next=$jscomp.array.done_;return $jscomp.array.done_()},d[Symbol.iterator]=function(){return e},d);return e};
$jscomp.array.findInternal_=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var g=a[e];if(c.call(b,g,e,a))return{i:e,v:g}}return{i:-1,v:void 0}};
$jscomp.array.from=function(a,c,b){c=void 0===c?function(a){return a}:c;var d=[];$jscomp.initSymbol();$jscomp.initSymbolIterator();if(a[Symbol.iterator]){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=a[Symbol.iterator]();for(var e;!(e=a.next()).done;)d.push(c.call(b,e.value))}else{e=a.length;for(var g=0;g<e;g++)d.push(c.call(b,a[g]))}return d};$jscomp.array.of=function(a){for(var c=[],b=0;b<arguments.length;++b)c[b-0]=arguments[b];return $jscomp.array.from(c)};
$jscomp.array.entries=function(){return $jscomp.array.arrayIterator_(this,function(a,c){return[a,c]})};$jscomp.array.entries$install=function(){Array.prototype.entries||(Array.prototype.entries=$jscomp.array.entries)};$jscomp.array.keys=function(){return $jscomp.array.arrayIterator_(this,function(a){return a})};$jscomp.array.keys$install=function(){Array.prototype.keys||(Array.prototype.keys=$jscomp.array.keys)};$jscomp.array.values=function(){return $jscomp.array.arrayIterator_(this,function(a,c){return c})};
$jscomp.array.values$install=function(){Array.prototype.values||(Array.prototype.values=$jscomp.array.values)};$jscomp.array.copyWithin=function(a,c,b){var d=this.length;a=Number(a);c=Number(c);b=Number(null!=b?b:d);if(a<c)for(b=Math.min(b,d);c<b;)c in this?this[a++]=this[c++]:(delete this[a++],c++);else for(b=Math.min(b,d+c-a),a+=b-c;b>c;)--b in this?this[--a]=this[b]:delete this[a];return this};$jscomp.array.copyWithin$install=function(){Array.prototype.copyWithin||(Array.prototype.copyWithin=$jscomp.array.copyWithin)};
$jscomp.array.fill=function(a,c,b){null!=b&&a.length||(b=this.length||0);b=Number(b);for(c=Number((void 0===c?0:c)||0);c<b;c++)this[c]=a;return this};$jscomp.array.fill$install=function(){Array.prototype.fill||(Array.prototype.fill=$jscomp.array.fill)};$jscomp.array.find=function(a,c){return $jscomp.array.findInternal_(this,a,c).v};$jscomp.array.find$install=function(){Array.prototype.find||(Array.prototype.find=$jscomp.array.find)};
$jscomp.array.findIndex=function(a,c){return $jscomp.array.findInternal_(this,a,c).i};$jscomp.array.findIndex$install=function(){Array.prototype.findIndex||(Array.prototype.findIndex=$jscomp.array.findIndex)};$jscomp.Map=function(a){a=void 0===a?[]:a;this.data_={};this.head_=$jscomp.Map.createHead_();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())c=c.value,this.set(c[0],c[1])}};
$jscomp.Map.checkBrowserConformance_=function(){var a=$jscomp.global.Map;if(!a||!a.prototype.entries||!Object.seal)return!1;try{var c=Object.seal({x:4}),b=new a($jscomp.makeIterator([[c,"s"]]));if("s"!=b.get(c)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var d=b.entries(),e=d.next();if(e.done||e.value[0]!=c||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(g){return!1}};
$jscomp.Map.createHead_=function(){var a={};return a.previous=a.next=a.head=a};$jscomp.Map.getId_=function(a){if(!(a instanceof Object))return String(a);$jscomp.Map.key_ in a||a instanceof Object&&Object.isExtensible&&Object.isExtensible(a)&&$jscomp.Map.defineProperty_(a,$jscomp.Map.key_,++$jscomp.Map.index_);return $jscomp.Map.key_ in a?a[$jscomp.Map.key_]:" "+a};
$jscomp.Map.prototype.set=function(a,c){var b=this.maybeGetEntry_(a),d=b.id,e=b.list,b=b.entry;e||(e=this.data_[d]=[]);b?b.value=c:(b={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:c},e.push(b),this.head_.previous.next=b,this.head_.previous=b,this.size++);return this};
$jscomp.Map.prototype["delete"]=function(a){var c=this.maybeGetEntry_(a);a=c.id;var b=c.list,d=c.index;return(c=c.entry)&&b?(b.splice(d,1),b.length||delete this.data_[a],c.previous.next=c.next,c.next.previous=c.previous,c.head=null,this.size--,!0):!1};$jscomp.Map.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=$jscomp.Map.createHead_();this.size=0};$jscomp.Map.prototype.has=function(a){return!!this.maybeGetEntry_(a).entry};
$jscomp.Map.prototype.get=function(a){return(a=this.maybeGetEntry_(a).entry)&&a.value};$jscomp.Map.prototype.maybeGetEntry_=function(a){var c=$jscomp.Map.getId_(a),b=this.data_[c];if(b)for(var d=0;d<b.length;d++){var e=b[d];if(a!==a&&e.key!==e.key||a===e.key)return{id:c,list:b,index:d,entry:e}}return{id:c,list:b,index:-1,entry:void 0}};$jscomp.Map.prototype.entries=function(){return this.iter_(function(a){return[a.key,a.value]})};$jscomp.Map.prototype.keys=function(){return this.iter_(function(a){return a.key})};
$jscomp.Map.prototype.values=function(){return this.iter_(function(a){return a.value})};$jscomp.Map.prototype.forEach=function(a,c){for(var b=$jscomp.makeIterator(this.entries()),d=b.next();!d.done;d=b.next())d=d.value,a.call(c,d[1],d[0],this)};
$jscomp.Map.prototype.iter_=function(a){var c=this,b=this.head_;$jscomp.initSymbol();$jscomp.initSymbolIterator();var d={};return d.next=function(){if(b){for(;b.head!=c.head_;)b=b.previous;for(;b.next!=b.head;)return b=b.next,{done:!1,value:a(b)};b=null}return{done:!0,value:void 0}},d[Symbol.iterator]=function(){return this},d};$jscomp.Map.index_=0;$jscomp.Map.defineProperty_=Object.defineProperty?function(a,c,b){Object.defineProperty(a,c,{value:String(b)})}:function(a,c,b){a[c]=String(b)};
$jscomp.Map.Entry_=function(){};$jscomp.Map.ASSUME_NO_NATIVE=!1;$jscomp.Map$install=function(){$jscomp.initSymbol();$jscomp.initSymbolIterator();!$jscomp.Map.ASSUME_NO_NATIVE&&$jscomp.Map.checkBrowserConformance_()?$jscomp.Map=$jscomp.global.Map:($jscomp.initSymbol(),$jscomp.initSymbolIterator(),$jscomp.Map.prototype[Symbol.iterator]=$jscomp.Map.prototype.entries,$jscomp.initSymbol(),$jscomp.Map.key_=Symbol("map-id-key"));$jscomp.Map$install=function(){}};$jscomp.math=$jscomp.math||{};
$jscomp.math.clz32=function(a){a=Number(a)>>>0;if(0===a)return 32;var c=0;0===(a&4294901760)&&(a<<=16,c+=16);0===(a&4278190080)&&(a<<=8,c+=8);0===(a&4026531840)&&(a<<=4,c+=4);0===(a&3221225472)&&(a<<=2,c+=2);0===(a&2147483648)&&c++;return c};$jscomp.math.imul=function(a,c){a=Number(a);c=Number(c);var b=a&65535,d=c&65535;return b*d+((a>>>16&65535)*d+b*(c>>>16&65535)<<16>>>0)|0};$jscomp.math.sign=function(a){a=Number(a);return 0===a||isNaN(a)?a:0<a?1:-1};
$jscomp.math.log10=function(a){return Math.log(a)/Math.LN10};$jscomp.math.log2=function(a){return Math.log(a)/Math.LN2};$jscomp.math.log1p=function(a){a=Number(a);if(.25>a&&-.25<a){for(var c=a,b=1,d=a,e=0,g=1;e!=d;)c*=a,g*=-1,d=(e=d)+g*c/++b;return d}return Math.log(1+a)};$jscomp.math.expm1=function(a){a=Number(a);if(.25>a&&-.25<a){for(var c=a,b=1,d=a,e=0;e!=d;)c*=a/++b,d=(e=d)+c;return d}return Math.exp(a)-1};$jscomp.math.cosh=function(a){a=Number(a);return(Math.exp(a)+Math.exp(-a))/2};
$jscomp.math.sinh=function(a){a=Number(a);return 0===a?a:(Math.exp(a)-Math.exp(-a))/2};$jscomp.math.tanh=function(a){a=Number(a);if(0===a)return a;var c=Math.exp(2*-Math.abs(a)),c=(1-c)/(1+c);return 0>a?-c:c};$jscomp.math.acosh=function(a){a=Number(a);return Math.log(a+Math.sqrt(a*a-1))};$jscomp.math.asinh=function(a){a=Number(a);if(0===a)return a;var c=Math.log(Math.abs(a)+Math.sqrt(a*a+1));return 0>a?-c:c};
$jscomp.math.atanh=function(a){a=Number(a);return($jscomp.math.log1p(a)-$jscomp.math.log1p(-a))/2};
$jscomp.math.hypot=function(a,c,b){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];a=Number(a);c=Number(c);for(var g=Math.max(Math.abs(a),Math.abs(c)),l=$jscomp.makeIterator(d),e=l.next();!e.done;e=l.next())g=Math.max(g,Math.abs(e.value));if(1E100<g||1E-100>g){a/=g;c/=g;l=a*a+c*c;d=$jscomp.makeIterator(d);for(e=d.next();!e.done;e=d.next())e=e.value,e=Number(e)/g,l+=e*e;return Math.sqrt(l)*g}g=a*a+c*c;d=$jscomp.makeIterator(d);for(e=d.next();!e.done;e=d.next())e=e.value,e=Number(e),g+=
e*e;return Math.sqrt(g)};$jscomp.math.trunc=function(a){a=Number(a);if(isNaN(a)||Infinity===a||-Infinity===a||0===a)return a;var c=Math.floor(Math.abs(a));return 0>a?-c:c};$jscomp.math.cbrt=function(a){if(0===a)return a;a=Number(a);var c=Math.pow(Math.abs(a),1/3);return 0>a?-c:c};$jscomp.number=$jscomp.number||{};$jscomp.number.isFinite=function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a};
$jscomp.number.isInteger=function(a){return $jscomp.number.isFinite(a)?a===Math.floor(a):!1};$jscomp.number.isNaN=function(a){return"number"===typeof a&&isNaN(a)};$jscomp.number.isSafeInteger=function(a){return $jscomp.number.isInteger(a)&&Math.abs(a)<=$jscomp.number.MAX_SAFE_INTEGER};$jscomp.number.EPSILON=Math.pow(2,-52);$jscomp.number.MAX_SAFE_INTEGER=9007199254740991;$jscomp.number.MIN_SAFE_INTEGER=-9007199254740991;$jscomp.object=$jscomp.object||{};
$jscomp.object.assign=function(a,c){for(var b=[],d=1;d<arguments.length;++d)b[d-1]=arguments[d];b=$jscomp.makeIterator(b);for(d=b.next();!d.done;d=b.next())if(d=d.value)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e]);return a};$jscomp.object.is=function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c};$jscomp.Set=function(a){a=void 0===a?[]:a;this.map_=new $jscomp.Map;if(a){a=$jscomp.makeIterator(a);for(var c=a.next();!c.done;c=a.next())this.add(c.value)}this.size=this.map_.size};
$jscomp.Set.checkBrowserConformance_=function(){var a=$jscomp.global.Set;if(!a||!a.prototype.entries||!Object.seal)return!1;var c=Object.seal({x:4}),a=new a($jscomp.makeIterator([c]));if(a.has(c)||1!=a.size||a.add(c)!=a||1!=a.size||a.add({x:4})!=a||2!=a.size)return!1;var a=a.entries(),b=a.next();if(b.done||b.value[0]!=c||b.value[1]!=c)return!1;b=a.next();return b.done||b.value[0]==c||4!=b.value[0].x||b.value[1]!=b.value[0]?!1:a.next().done};
$jscomp.Set.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};$jscomp.Set.prototype["delete"]=function(a){a=this.map_["delete"](a);this.size=this.map_.size;return a};$jscomp.Set.prototype.clear=function(){this.map_.clear();this.size=0};$jscomp.Set.prototype.has=function(a){return this.map_.has(a)};$jscomp.Set.prototype.entries=function(){return this.map_.entries()};$jscomp.Set.prototype.values=function(){return this.map_.values()};
$jscomp.Set.prototype.forEach=function(a,c){var b=this;this.map_.forEach(function(d){return a.call(c,d,d,b)})};$jscomp.Set.ASSUME_NO_NATIVE=!1;$jscomp.Set$install=function(){!$jscomp.Set.ASSUME_NO_NATIVE&&$jscomp.Set.checkBrowserConformance_()?$jscomp.Set=$jscomp.global.Set:($jscomp.Map$install(),$jscomp.initSymbol(),$jscomp.initSymbolIterator(),$jscomp.Set.prototype[Symbol.iterator]=$jscomp.Set.prototype.values);$jscomp.Set$install=function(){}};$jscomp.string=$jscomp.string||{};
$jscomp.string.noRegExp_=function(a,c){if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");};
$jscomp.string.fromCodePoint=function(a){for(var c=[],b=0;b<arguments.length;++b)c[b-0]=arguments[b];for(var b="",c=$jscomp.makeIterator(c),d=c.next();!d.done;d=c.next()){d=d.value;d=+d;if(0>d||1114111<d||d!==Math.floor(d))throw new RangeError("invalid_code_point "+d);65535>=d?b+=String.fromCharCode(d):(d-=65536,b+=String.fromCharCode(d>>>10&1023|55296),b+=String.fromCharCode(d&1023|56320))}return b};
$jscomp.string.repeat=function(a){var c=this.toString();if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var b="";a;)if(a&1&&(b+=c),a>>>=1)c+=c;return b};$jscomp.string.repeat$install=function(){String.prototype.repeat||(String.prototype.repeat=$jscomp.string.repeat)};
$jscomp.string.codePointAt=function(a){var c=this.toString(),b=c.length;a=Number(a)||0;if(0<=a&&a<b){a|=0;var d=c.charCodeAt(a);if(55296>d||56319<d||a+1===b)return d;a=c.charCodeAt(a+1);return 56320>a||57343<a?d:1024*(d-55296)+a+9216}};$jscomp.string.codePointAt$install=function(){String.prototype.codePointAt||(String.prototype.codePointAt=$jscomp.string.codePointAt)};
$jscomp.string.includes=function(a,c){c=void 0===c?0:c;$jscomp.string.noRegExp_(a,"includes");return-1!==this.toString().indexOf(a,c)};$jscomp.string.includes$install=function(){String.prototype.includes||(String.prototype.includes=$jscomp.string.includes)};
$jscomp.string.startsWith=function(a,c){c=void 0===c?0:c;$jscomp.string.noRegExp_(a,"startsWith");var b=this.toString();a+="";for(var d=b.length,e=a.length,g=Math.max(0,Math.min(c|0,b.length)),l=0;l<e&&g<d;)if(b[g++]!=a[l++])return!1;return l>=e};$jscomp.string.startsWith$install=function(){String.prototype.startsWith||(String.prototype.startsWith=$jscomp.string.startsWith)};
$jscomp.string.endsWith=function(a,c){$jscomp.string.noRegExp_(a,"endsWith");var b=this.toString();a+="";void 0===c&&(c=b.length);for(var d=Math.max(0,Math.min(c|0,b.length)),e=a.length;0<e&&0<d;)if(b[--d]!=a[--e])return!1;return 0>=e};$jscomp.string.endsWith$install=function(){String.prototype.endsWith||(String.prototype.endsWith=$jscomp.string.endsWith)};
var __ZDABCB=window.__ZDABCB||function(a){var c=[];a||(a=window);try{a=window.frameElement&&window.parent.document.body?window.parent:a}catch(f){}var b="https:"==a.location.protocol?"https:":"http:",d={adblock:null,easylist:null,easyprivacy:null,acceptableads:null,ghostery:null},e=!1,g=!1,l=function(){if(!a.__ZDGC){a.__ZDGC="xxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)});try{(new Image).src=b+"//cdn.nsstatic.com/tview/n/7hJiiEHoEeWRqiIAC39GJQ?g="+
encodeURIComponent(a.__ZDGC)+"&u="+encodeURIComponent(a.location.href)+"&or="+encodeURIComponent(a.document.referrer)}catch(c){try{(new Image).src=b+"//cdn.nsstatic.com/tview/n/7hJiiEHoEeWRqiIAC39GJQ?g="+encodeURIComponent(a.__ZDGC)+"&or=&u="+encodeURIComponent(a.location.href)}catch(d){}}}},n=function(c){if(!e&&d.adblock&&(c||null!==d.adblock&&null!==d.easylist&&null!==d.easyprivacy)){d.adblock||!d.easylist&&!d.easyprivacy||(d.adblock=1);var w="ab="+encodeURIComponent(d.adblock||0)+"&ez="+encodeURIComponent(d.easylist||
0)+"&ezp="+encodeURIComponent(d.easyprivacy||0)+"&aa="+encodeURIComponent(d.acceptableads||0)+"&gh="+encodeURIComponent(d.ghostery||0)+"&g="+encodeURIComponent(a.__ZDGC||"")+"&v="+encodeURIComponent("1.6")+"&u="+encodeURIComponent(a.location.href);try{var h=new Image;h.onerror=function(){(new Image).src=b+"//zdbb.net/n/d0miMsgbEeSUDxIxPSpF6g?"+w};h.src=b+"//zdbb.net/n/d0miMsgbEeSUDxIxPSpF6g?"+w}catch(q){}try{(new Image).src=b+"//cdn.nsstatic.com/tview/n/4hyF_kHoEeWRqiIAC39GJQ?"+w}catch(q){}a.ga=a.ga||
function(){(a.ga.q=a.ga.q||[]).push(arguments)};a.ga.l=+new Date;a.ga("ns.send","event","AdBlock","Adblocker active","",1,!0);a._gaq=window._gaq?window._gaq:[];a._gaq.push(["ns._trackEvent","AdBlock","Adblocker active","",1,!0]);e=!0}},v=function(){var a=new Image;a.onerror=function(a){d.easylist=1;y(!0)};a.onload=function(a){d.easylist=0;y()};a.src=b+"//static.adziff.com/pcmag/images/zd_footer_logo.png"},r=function(){var a=new Image;a.onerror=function(a){d.easyprivacy=1;y(!0)};a.onload=function(a){d.easyprivacy=
0;y()};a.src=b+"//zdbb.net/n/a.gif"},k=function(){var a=new Image;a.onerror=function(a){d.acceptableads=0;y()};a.onload=function(a){d.acceptableads=1;y()};a.src=b+"//pagead2.googlesyndication.com/activeview?"},y=function(b){null===d.adblock&&null!==b&&(d.adblock=b?1:0);if(null!==d.easylist&&null!==d.easyprivacy&&null!==d.acceptableads){if(d.adblock){if(a.__ZDAB)return;a.__ZDAB=!0;n()}else d.adblock=0,a.__ZDAB=!1;if(!g){for(b=0;b<c.length;b++)try{c[b](d)}catch(e){}g=!0}}},q=function(){try{if(window.frameElement&&
window.frameElement.parentNode)return}catch(b){}l();if(a.__ZDABCQ)for(var f=0;f<a.__ZDABCQ.length;f++)c.push(a.__ZDABCQ[f]);a._sp_&&a._sp_.checkState?a._sp_.checkState(y):document.addEventListener("sp.blocking",y);v();r();k();window.addEventListener("unload",function(){n()})};q();return{callbacks:c,init:q}}(),pbjs=pbjs||{};pbjs.que=pbjs.que||[];
(function(a){function c(d){if(b[d])return b[d].exports;var e=b[d]={exports:{},id:d,loaded:!1};a[d].call(e.exports,e,e.exports,c);e.loaded=!0;return e.exports}var b={};c.m=a;c.c=b;c.p="";return c(0)})([function(a,c,b){b(1);b(9);b(10);b(3);b(7);b(13);b(6);b(14);a.exports=b(5)},function(a,c,b){$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();var d="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){$jscomp.initSymbol();$jscomp.initSymbol();
return a&&"function"===typeof Symbol&&a.constructor===Symbol?"symbol":typeof a},e=b(2),g=b(3),l=b(5),n=b(4),v=b(7),r={};c.bidderRegistry=r;c.callBids=function(a){for(var c=0;c<a.length;c++){var b=a[c];if(b.bidderCode&&r[b.bidderCode]){l.logMessage("CALLING BIDDER ======= "+b.bidderCode);var f=r[b.bidderCode];v.emit(n.EVENTS.BID_REQUESTED,b);f.callBids(b);void 0===g.getExpectedBidsCount(b.bidderCode)&&g.setExpectedBidsCount(b.bidderCode,b.bids.length);var d=(new Date).getTime();g.registerBidRequestTime(b.bidderCode,
d);f.defaultBidderSettings&&g.registerDefaultBidderSetting(b.bidderCode,f.defaultBidderSettings)}else l.logError("Adapter trying to be called which does not exist: "+b.bidderCode,"adaptermanager.callBids")}};c.registerBidAdapter=function(a,b){a&&b?d(a.callBids)===n.objectType_function?r[b]=a:l.logError("Bidder adaptor error for bidder code: "+b+"bidder must implement a callBids() function"):l.logError("bidAdaptor or bidderCode not specified")};c.aliasBidAdapter=function(a,b){var c=r[b];if(("undefined"===
typeof c?"undefined":d(c))===n.objectType_undefined)if(c=r[a],("undefined"===typeof c?"undefined":d(c))===n.objectType_undefined)l.logError('bidderCode "'+a+'" is not an existing bidder.',"adaptermanager.aliasBidAdapter");else try{var f=null;c instanceof e.BaseAdapter?l.logError(a+" bidder does not currently support aliasing.","adaptermanager.aliasBidAdapter"):(f=c.createNew(),f.setBidderCode(b),this.registerBidAdapter(f,b))}catch(w){l.logError(a+" bidder does not currently support aliasing.","adaptermanager.aliasBidAdapter")}else l.logMessage('alias name "'+
b+'" has been already specified.')};a=b(8);c.registerBidAdapter(new a.createNew,"appnexus");b=b(12);c.registerBidAdapter(new b,"rubicon");c.aliasBidAdapter("appnexus","brealtime")},function(a,c){Object.defineProperty(c,"__esModule",{value:!0});var b=function(){function a(b,c){for(var d=0;d<c.length;d++){var n=c[d];n.enumerable=n.enumerable||!1;n.configurable=!0;"value"in n&&(n.writable=!0);Object.defineProperty(b,n.key,n)}}return function(b,c,l){c&&a(b.prototype,c);l&&a(b,l);return b}}();c.BaseAdapter=
function(){function a(b){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");this.code=b}b(a,[{key:"getCode",value:function(){return this.code}},{key:"setCode",value:function(a){this.code=a}},{key:"callBids",value:function(){throw"adapter implementation must override callBids method";}}]);return a}()},function(a,c,b){function d(a){"undefined"===v(A[a])?A[a]=1:A[a]++}function e(a,b,c){b=b[r.JSON_MAPPING.ADSERVER_TARGETING];c.size=c.getSize();k._each(b,function(b){var f=
b.key;b=b.val;if(k.isFn(b))try{a[f]=b(c)}catch(d){k.logError("bidmanager","ERROR",d)}else a[f]=b});return a}function g(a,b){var c;if(k.isArray(a))for(c=0;c<a.length;c++)l(a[c],b);else l(a,b)}function l(a,b){if("function"===typeof a)try{a.apply(pbjs,b)}catch(c){k.logError("Error executing callback function: "+c.message)}}function n(){var a=!0;k._each(A,function(b,c){var f=m[c];if("undefined"===("undefined"===typeof f?"undefined":v(f))||b<f)a=!1});return a}$jscomp.initSymbol();$jscomp.initSymbol();
$jscomp.initSymbolIterator();var v="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){$jscomp.initSymbol();$jscomp.initSymbol();return a&&"function"===typeof Symbol&&a.constructor===Symbol?"symbol":typeof a},r=b(4),k=b(5),y=b(7),q=[],f=[],w=null,h={};c.pbCallbackMap=h;var x={};c.pbBidResponseByPlacement=x;var u={};c._adResponsesByBidderId=u;var A={};c.bidResponseReceivedCount=A;var m={},z=!1,p=!1,B={},J={};c.getPlacementIdByCBIdentifer=function(a){return h[a]};
c.getBidResponseByAdUnit=function(){return x};c.clearAllBidResponses=function(){p=z=!1;for(var a in A)delete A[a];for(a=0;a<pbjs.adUnits.length;a++)for(var b=pbjs.adUnits[a].bids,c=0;c<b.length;c++)A[b[c].bidder]=0;m={};f.called=!1;for(var d in this.pbBidResponseByPlacement)delete this.pbBidResponseByPlacement[d]};c.getTimedOutBidders=function(){return k._map(A,function(a,b){if(0===a)return b})};c.increaseBidResponseReceivedCount=function(a){d(a)};c.setExpectedBidsCount=function(a,b){m[a]=b};c.getExpectedBidsCount=
function(a){return m[a]};c.addBidResponse=function(a,b){var c={};if(b){b.requestTimestamp=J[b.bidderCode];b.responseTimestamp=(new Date).getTime();b.timeToRespond=b.responseTimestamp-b.requestTimestamp;d(b.bidderCode);2===b.getStatusCode()&&(b.cpm=0);y.emit(r.EVENTS.BID_ADJUSTMENT,b);y.emit(r.EVENTS.BID_RESPONSE,a,b);var f=k.getPriceBucketString(b.cpm,b.height,b.width);b.pbLg=f.low;b.pbMg=f.med;b.pbHg=f.high;b.adUnitCode=a;b.bidder=b.bidderCode;f={};b.bidderCode&&0!==b.cpm&&(f=this.getKeyValueTargetingPairs(b.bidderCode,
b),b.adserverTargeting=f);b.adId&&(u[b.adId]=b);a&&x[a]?(c=x[a],c.bids.push(b),c.bidsReceivedCount++):k.logError("Internal error in bidmanager.addBidResponse. Params: "+a+" & "+b)}else c=this.createEmptyBidResponseObj();x[a]=c;this.checkIfAllBidsAreIn(a)};c.createEmptyBidResponseObj=function(){return{bids:[],allBidsAvailable:!1,bidsReceivedCount:0}};c.getKeyValueTargetingPairs=function(a,b){var c={},f=pbjs.bidderSettings||{};a&&b&&f&&f[a]&&f[a][r.JSON_MAPPING.ADSERVER_TARGETING]?(e(c,f[a],b),b.alwaysUseBid=
f[a].alwaysUseBid):B[a]?(e(c,B[a],b),b.alwaysUseBid=B[a].alwaysUseBid):b&&f&&(f[r.JSON_MAPPING.BD_SETTING_STANDARD]||(f[r.JSON_MAPPING.BD_SETTING_STANDARD]={adserverTargeting:[{key:"hb_bidder",val:function(a){return a.bidderCode}},{key:"hb_adid",val:function(a){return a.adId}},{key:"hb_pb",val:function(a){return a.pbMg}},{key:"hb_size",val:function(a){return a.size}}]}),e(c,f[r.JSON_MAPPING.BD_SETTING_STANDARD],b));return c};c.registerDefaultBidderSetting=function(a,b){B[a]=b};c.registerBidRequestTime=
function(a,b){J[a]=b};c.executeCallback=function(){var a=[];if("function"===v(pbjs.registerBidCallbackHandler)&&!p)try{pbjs.registerBidCallbackHandler(),p=!0}catch(b){p=!0,k.logError("Exception trying to execute callback handler registered : "+b.message)}!0!==f.called&&(g(f,a),f.called=!0);if(w){var a=[],c=pbjs.getBidResponses();a.push(c);g(w,a);w=null}};c.allBidsBack=function(){return z};c.setBidderMap=function(a){};c.checkIfAllBidsAreIn=function(a){z=n();for(var b=0;b<pbjs.adUnits.length;b++){var c=
pbjs.adUnits[b];c.code===a&&x[a].bidsReceivedCount===c.bids.length&&g(q,[a])}z&&this.executeCallback()};c.addOneTimeCallback=function(a){w=a};c.addCallback=function(a,b,c){b.id=a;r.CB.TYPE.ALL_BIDS_BACK===c?f.push(b):r.CB.TYPE.AD_UNIT_BIDS_BACK===c&&q.push(b)};y.on(r.EVENTS.BID_ADJUSTMENT,function(a){var b=a.bidderCode,c=a.cpm;if(b&&pbjs.bidderSettings&&pbjs.bidderSettings[b]&&"function"===v(pbjs.bidderSettings[b].bidCpmAdjustment))try{c=pbjs.bidderSettings[b].bidCpmAdjustment.call(null,a.cpm)}catch(f){k.logError("Error during bid adjustment",
"bidmanager.js",f)}0!==c&&(a.cpm=c)})},function(a,c){a.exports={JSON_MAPPING:{PL_CODE:"code",PL_SIZE:"sizes",PL_BIDS:"bids",BD_BIDDER:"bidder",BD_ID:"paramsd",BD_PL_ID:"placementId",ADSERVER_TARGETING:"adserverTargeting",BD_SETTING_STANDARD:"standard"},DEBUG_MODE:"pbjs_debug",STATUS:{GOOD:1,NO_BID:2},CB:{TYPE:{ALL_BIDS_BACK:"allRequestedBidsBack",AD_UNIT_BIDS_BACK:"adUnitBidsBack",BID_WON:"bidWon"}},objectType_function:"function",objectType_undefined:"undefined",objectType_object:"object",objectType_string:"string",
objectType_number:"number",EVENTS:{BID_ADJUSTMENT:"bidAdjustment",BID_TIMEOUT:"bidTimeout",BID_REQUESTED:"bidRequested",BID_RESPONSE:"bidResponse",BID_WON:"bidWon"},EVENT_ID_PATHS:{bidWon:"adUnitCode"}}},function(a,c,b){function d(){return k()+Math.random().toString(16).substr(2)}function e(){return window.console&&window.console.log}$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();var g="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:
function(a){$jscomp.initSymbol();$jscomp.initSymbol();return a&&"function"===typeof Symbol&&a.constructor===Symbol?"symbol":typeof a},l=b(4);a=b(6);var n=!1,v=Object.prototype.toString,r=null;try{r=console.info.bind(window.console)}catch(f){}c.replaceTokenInString=function(a,b,c){this._each(b,function(b,d){b=void 0===b?"":b;var e=c+d.toUpperCase()+c;a=a.replace(new RegExp(e,"g"),b)});return a};var k=function(){var a=0;return function(){a++;return a}}();c.getUniqueIdentifierStr=d;c.getBidIdParamater=
function(a,b){return b&&b[a]?b[a]:""};c.tryAppendQueryString=function(a,b,c){return c?a+(b+"="+encodeURIComponent(c)+"&"):a};c.parseQueryStringParameters=function(a){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=c+"="+encodeURIComponent(a[c])+"&");return b};c.transformAdServerTargetingObj=function(a){var b="";if(!a)return"";for(var c in a)a.hasOwnProperty(c)&&(b+=c+"="+encodeURIComponent(a[c])+"&");return b};c.extend=function(a,b){a=a||{};this._each(b,function(c,d){"object"===g(b[d])?a[d]=this.extend(a[d],
b[d]):a[d]=b[d]});return a};c.parseSizesInput=function(a){var b=[];if("string"===("undefined"===typeof a?"undefined":g(a))){a=a.split(",");var c=/^(\d)+x(\d)+$/i;if(a)for(var d in a){var e;e=a;var q=d;e=e.hasOwnProperty?e.hasOwnProperty(q):"undefined"!==typeof e[q]&&e.constructor.prototype[q]!==e[q];e&&a[d].match(c)&&b.push(a[d])}}else if("object"===("undefined"===typeof a?"undefined":g(a))&&(d=a.length,0<d))if(2===d&&"number"===g(a[0])&&"number"===g(a[1]))b.push(this.parseGPTSingleSizeArray(a));
else for(c=0;c<d;c++)b.push(this.parseGPTSingleSizeArray(a[c]));return b};c.parseGPTSingleSizeArray=function(a){if(this.isArray(a)&&2===a.length&&!isNaN(a[0])&&!isNaN(a[1]))return a[0]+"x"+a[1]};c.getTopWindowUrl=function(){try{return window.top.location.href}catch(a){return window.location.href}};c.logInfo=function(a,b){q()&&e()&&r&&(b&&0!==b.length||(b=""),r("INFO: "+a+(""===b?"":" : params : "),b))};c.logMessage=function(a){q()&&e()&&console.log("MESSAGE: "+a)};c.hasConsoleLogger=e;var y=function(a){return a?
window.console.error?"error":"log":""}(e()),q=function(){if(!1===pbjs.logging&&!1===n){var a=pbjs,b;b=(new RegExp("[\\?&]"+l.DEBUG_MODE+"=([^&#]*)")).exec(window.location.search);b=null===b?"":decodeURIComponent(b[1].replace(/\+/g," "));a.logging="TRUE"===b.toUpperCase();n=!0}return!!pbjs.logging};c.debugTurnedOn=q;c.logError=function(a,b,c){b=b||"ERROR";q()&&e()&&console[y].call(console,b+": "+a,c||"")};c.createInvisibleIframe=function(){var a=document.createElement("iframe");a.id=d();a.height=0;
a.width=0;a.border="0px";a.hspace="0";a.vspace="0";a.marginWidth="0";a.marginHeight="0";a.style.border="0";a.scrolling="no";a.frameBorder="0";a.src="about:blank";a.style.display="none";return a};c.getPriceBucketString=function(a){var b=0,c={low:"",med:"",high:""};try{if(b=parseFloat(a))c.low=5<b?(5).toFixed(2):(Math.floor(2*a)/2).toFixed(2),c.med=20<b?(20).toFixed(2):(Math.floor(10*a)/10).toFixed(2),c.high=20<b?(20).toFixed(2):(Math.floor(100*a)/100).toFixed(2)}catch(d){this.logError("Exception parsing CPM :"+
d.message)}return c};c.hasValidBidRequest=function(a,b,c){function d(a,c){c===b[q]&&(e=!0)}for(var e=!1,q=0;q<b.length;q++)if(e=!1,this._each(a,d),!e)return this.logError("Params are missing for bid request. One of these required paramaters are missing: "+b,c),!1;return!0};c.addEventHandler=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!0):a.attachEvent&&a.attachEvent("on"+b,c)};c.isA=function(a,b){return v.call(a)==="[object "+b+"]"};c.isFn=function(a){return this.isA(a,"Function")};
c.isStr=function(a){return this.isA(a,"String")};c.isArray=function(a){return this.isA(a,"Array")};c.isEmpty=function(a){if(!a)return!0;if(this.isArray(a)||this.isStr(a))return!(0<a.length);for(var b in a)if(hasOwnProperty.call(a,b))return!1;return!0};c._each=function(a,b){if(!this.isEmpty(a)){if(this.isFn(a.forEach))return a.forEach(b,this);var c=0,d=a.length;if(0<d)for(;c<d;c++)b(a[c],c,a);else for(c in a)hasOwnProperty.call(a,c)&&b.call(this,a[c],c)}};c.contains=function(a,b){if(this.isEmpty(a))return!1;
if(this.isFn(a.indexOf))return-1!==a.indexOf(b);for(var c=a.length;c--;)if(a[c]===b)return!0;return!1};a=Array.prototype.indexOf?Array.prototype.indexOf:a.indexOf;c.indexOf=a;c._map=function(a,b){if(this.isEmpty(a))return[];if(this.isFn(a.map))return a.map(b);var c=[];this._each(a,function(d,e){c.push(b(d,e,a))});return c};c.createTrackPixelHtml=function(a){if(!a)return"";a=encodeURI(a);return'<div style="position:absolute;left:0px;top:0px;visibility:hidden;">'+('<img src="'+a+'"></div>')};c.getIframeDocument=
function(a){if(a){var b=void 0;try{b=a.contentWindow?a.contentWindow.document:a.contentDocument.document?a.contentDocument.document:a.contentDocument}catch(c){this.logError("Cannot get iframe document",c)}return b}}},function(a,c){c.indexOf=function(a,c){var e,g;if(null===this)throw new TypeError('"this" is null or not defined');var l=Object(this);e=l.length>>>0;if(0===e)return-1;g=+c||0;Infinity===Math.abs(g)&&(g=0);if(g>=e)return-1;for(g=Math.max(0<=g?g:e-Math.abs(g),0);g<e;){if(g in l&&l[g]===
a)return g;g++}return-1}},function(a,c,b){var d=b(5);c=b(4);var e=Array.prototype.slice,g=Array.prototype.push,l=d._map(c.EVENTS,function(a){return a}),n=c.EVENT_ID_PATHS,v=[];a.exports=function(){function a(c,e){d.logMessage("Emitting event for: "+c);var f=e[0],w=f[n[c]],h=b[c]||{que:[]},l=d._map(h,function(a,b){return b}),u=[];v.push({eventType:c,args:f,id:w});w&&d.contains(l,w)&&g.apply(u,h[w].que);g.apply(u,h.que);d._each(u,function(a){if(a)try{a.apply(null,e)}catch(b){d.logError("Error executing handler:",
"events.js",b)}})}var b={};return{on:function(a,c,e){if(d.contains(l,a)){var g=b[a]||{que:[]};e?(g[e]=g[e]||{que:[]},g[e].que.push(c)):g.que.push(c);b[a]=g}else d.logError("Wrong event name : "+a+" Valid event names :"+l)},emit:function(b){var c=e.call(arguments,1);a(b,c)},off:function(a,c,e){var g=b[a];d.isEmpty(g)||d.isEmpty(g.que)&&d.isEmpty(g[e])||e&&(d.isEmpty(g[e])||d.isEmpty(g[e].que))||(e?d._each(g[e].que,function(a){var b=g[e].que;a===c&&b.splice(d.indexOf.call(b,a),1)}):d._each(g.que,function(a){var b=
g.que;a===c&&b.splice(d.indexOf.call(b,a),1)}),b[a]=g)},get:function(){return b},getEvents:function(){var a=[];d._each(v,function(b){b=d.extend({},b);a.push(b)});return a}}}()},function(a,c,b){var d=b(4),e=b(5),g=b(9),l=b(3),n=b(10),v=b(11),r;r=function(){function a(b,c){var d=e.getBidIdParamater("placementId",b.params),g=e.getBidIdParamater("memberId",b.params),l=e.getBidIdParamater("member",b.params),u=e.getBidIdParamater("invCode",b.params),n=e.getBidIdParamater("query",b.params),m=e.getBidIdParamater("referrer",
b.params),k=e.getBidIdParamater("alt_referrer",b.params),p="http"+("https:"===document.location.protocol?"s://secure.adnxs.com/jpt?":"://ib.adnxs.com/jpt?"),p=e.tryAppendQueryString(p,"callback","pbjs.handleAnCB"),p=e.tryAppendQueryString(p,"callback_uid",c),p=e.tryAppendQueryString(p,"psa","0"),p=e.tryAppendQueryString(p,"id",d);l?p=e.tryAppendQueryString(p,"member_id",l):g&&(p=e.tryAppendQueryString(p,"member_id",g),e.logMessage('appnexus.callBids: "memberId" will be deprecated soon. Please use "member" instead'));
p=e.tryAppendQueryString(p,"code",u);p=e.tryAppendQueryString(p,"code",u);d="";g=e.parseSizesInput(b.sizes);l=g.length;if(0<l&&(d="size="+g[0],1<l)){d+="&promo_sizes=";for(u=1;u<l;u++)d+=g[u]+=",";d&&","===d.charAt(d.length-1)&&(d=d.slice(0,d.length-1))}d&&(p+=d+"&");(n=e.parseQueryStringParameters(n))&&(p+=n);n=e.extend({},b.params);delete n.placementId;delete n.memberId;delete n.invCode;delete n.query;delete n.referrer;delete n.alt_referrer;delete n.member;(n=e.parseQueryStringParameters(n))&&(p+=
n);""===m&&(m=e.getTopWindowUrl());p=e.tryAppendQueryString(p,"referrer",m);p=e.tryAppendQueryString(p,"alt_referrer",k);p.lastIndexOf("&")===p.length-1&&(p=p.substring(0,p.length-1));e.logMessage("jpt request built: "+p);b.startTime=(new Date).getTime();return p}var b=v.createNew("appnexus");b.callBids=function(c){var d=b.getBidderCode();c=c.bids;var n=c.length;l.setExpectedBidsCount(d,n);for(d=0;d<n;d++){var h=c[d],r=e.getUniqueIdentifierStr();g.loadScript(a(h,r));l.pbCallbackMap[r]=h}};pbjs.handleAnCB=
function(a){var b;if(a&&a.callback_uid){var c;c=a.callback_uid;var g="",k=l.getPlacementIdByCBIdentifer(c);k&&(b=k.bidder,g=k.placementCode,k.status=d.STATUS.GOOD);e.logMessage("JSONP callback function called for ad ID: "+c);k=[];if(a.result&&a.result.cpm&&0!==a.result.cpm){c=parseInt(a.result.cpm,10);c/=1E4;var u=a.result.creative_id,k=n.createBid(1);k.creative_id=u;k.bidderCode=b;k.cpm=c;k.adUrl=a.result.ad;k.width=a.result.width;k.height=a.result.height;k.dealId=a.result.deal_id}else e.logMessage("No prebid response from AppNexus for placement code "+
g),k=n.createBid(2),k.bidderCode=b;l.addBidResponse(g,k)}else e.logMessage("No prebid response for placement %%PLACEMENT%%")};return{callBids:b.callBids,setBidderCode:b.setBidderCode,createNew:c.createNew,buildJPTCall:a}};c.createNew=function(){return new r}},function(a,c,b){function d(a,b){var c=document.createElement("script");c.type="text/javascript";c.async=!0;b&&"function"===typeof b&&(c.readyState?c.onreadystatechange=function(){if("loaded"===c.readyState||"complete"===c.readyState)c.onreadystatechange=
null,b()}:c.onload=function(){b()});c.src=a;var d=document.getElementsByTagName("head"),d=d.length?d:document.getElementsByTagName("body");d.length&&(d=d[0],d.insertBefore(c,d.firstChild))}var e=b(5),g={};c.loadScript=function(a,b,c){a?c?g[a]?g[a].loaded?b():g[a].callbacks.push(b):(g[a]={loaded:!1,callbacks:[]},g[a].callbacks.push(b),d(a,function(){g[a].loaded=!0;try{for(var b=0;b<g[a].callbacks.length;b++)g[a].callbacks[b]()}catch(c){e.logError("Error executing callback","adloader.js:loadScript",
c)}})):d(a,b):e.logError("Error attempting to request empty URL","adloader.js:loadScript")};c.trackPixel=function(a){var b=void 0,b=void 0;if(a&&"string"===typeof a)return b=0<a.indexOf("?")?"&":"?",b=a+b+"rnd="+Math.floor(1E7*Math.random()),(new Image).src=b;e.logMessage("Missing or invalid pixelUrl.")}},function(a,c,b){function d(a){var b=e.getUniqueIdentifierStr(),c=a||0;this.bidderCode="";this.height=this.width=0;this.statusMessage=function(){switch(c){case 0:return"Pending";case 1:return"Bid available";
case 2:return"Bid returned empty or error response";case 3:return"Bid timed out"}}();this.adId=b;this.getStatusCode=function(){return c};this.getSize=function(){return this.width+"x"+this.height}}var e=b(5);c.createBid=function(a){return new d(a)}},function(a,c){function b(a){var b=a;return{callBids:function(){},setBidderCode:function(a){b=a},getBidderCode:function(){return b}}}c.createNew=function(a){return new b(a)}},function(a,c,b){var d=b(5),e=b(3),g=b(10),l=b(9);a.exports=function(){function a(b,
c){var d=g.createBid(2);d.bidderCode="rubicon";d.error=c;return d}function b(a,c){return(c.cpm||0)-(a.cpm||0)}function c(a,b){h||(h=1,l.loadScript(f+a.accountId+".js",b))}function k(a){d._each(a,function(a){if(!a.params.sizes){for(var b=d.parseSizesInput(a.sizes),c=[],e=0;e<b.length;e++){var f=w[b[e]];f&&c.push(f)}a.params.sizes=c}})}function y(a){var b=a.params.userId,c=a.params.position,d=a.params.visitor||[],e=a.params.keywords||[],f=a.params.inventory||[];a=window.rubicontag.defineSlot({siteId:a.params.siteId,
zoneId:a.params.zoneId,sizes:a.params.sizes,id:a.placementCode});a.clearTargeting();b&&window.rubicontag.setUserKey(b);c&&a.setPosition(c);for(var g in d)a.addFPV(g,d[g]);for(g in f)a.addFPI(g,f[g]);a.addKW(e);return a}function q(c){d.logMessage("Rubicon Project bidding complete: "+((new Date).getTime()-x));d._each(c,function(c){var f=c.getRawResponses();if(f&&0!==f.length){var h;h=f.sort(b);var f=g.createBid(1),k=h[0],l=k.dimensions;l?(f.bidderCode="rubicon",f.cpm=k.cpm,h=c.getElementId(),(k=w[l.join("x")])?
h='<script type="text/javascript">;(function (w, fe) { w.rubicontag.renderCreative(fe, "'+h+'", "'+k+'"); }(window.parent, (document.body || document.documentElement)));\x3c/script>':(d.logError("fastlane: missing sizeId for size: "+l.join("x")+" could not render creative","rubicon",w),h=""),f.ad=h,f.width=l[0],f.height=l[1]):(d.logError("no dimensions given","rubicon",k),f=a(c,h))}else f=a(c,f);e.addBidResponse(c.getElementId(),f)})}var f=window.location.protocol+"//ads.rubiconproject.com/header/",
w={"728x90":2,"160x600":9,"300x600":10,"300x250":15,"320x50":43,"300x1050":54,"970x250":57},h=0;window.rubicontag=window.rubicontag||{};window.rubicontag.cmd=window.rubicontag.cmd||[];var x=null;return{callBids:function(a){x=(new Date).getTime();k(a.bids);d.isEmpty(a.bids)||(h||c(a.bids[0].params),window.rubicontag.cmd.push(function(){var b=[],c=a.bids,d;for(d in c)b.push(y(c[d]));window.rubicontag.run(function(){q(b)},{slots:b})}))}}}},function(a,c,b){function d(){if(A&&"function"===typeof window[u]){for(var a=
0;a<x.length;a++)x[a].call();x.push=function(a){a.call()};A=!1}k.logMessage("event count sent to GA: "+m)}function e(a){return a?Math.floor(100*a):0}function g(a){a&&a.bidderCode&&x.push(function(){m++;window[u]("send","event","Prebid.js Bids","Requests",a.bidderCode,1,h)});d()}function l(a){a&&a.bidderCode&&x.push(function(){var b=e(a.cpm),c=a.bidderCode;if("undefined"!==typeof a.timeToRespond&&z){m++;var d=a.timeToRespond,f;0<=d&&200>d?f="0-200ms":200<=d&&300>d?f="200-300ms":300<=d&&400>d?f="300-400ms":
400<=d&&500>d?f="400-500ms":500<=d&&600>d?f="500-600ms":600<=d&&800>d?f="600-800ms":800<=d&&1E3>d?f="800-1000ms":1E3<=d&&1200>d?f="1000-1200ms":1200<=d&&1500>d?f="1200-1500ms":1500<=d&&2E3>d?f="1500-2000ms":2E3<=d&&(f="2000ms above");window[u]("send","event","Prebid.js Load Time Distribution",f,c,1,h)}if(0<a.cpm){m+=2;var g,d=a.cpm;0<=d&&.5>d?g="$0-0.5":.5<=d&&1>d?g="$0.5-1":1<=d&&1.5>d?g="$1-1.5":1.5<=d&&2>d?g="$1.5-2":2<=d&&2.5>d?g="$2-2.5":2.5<=d&&3>d?g="$2.5-3":3<=d&&4>d?g="$3-4":4<=d&&6>d?g=
"$4-6":6<=d&&8>d?g="$6-8":8<=d&&(g="$8 above");z&&(m++,window[u]("send","event","Prebid.js CPM Distribution",g,c,1,h));window[u]("send","event","Prebid.js Bids","Bids",c,b,h);window[u]("send","event","Prebid.js Bids","Bid Load Time",c,a.timeToRespond,h)}});d()}function n(a){a&&a.bidder&&x.push(function(){k._each(p,function(b){a.bidder===b&&(m++,window[u]("send","event","Prebid.js Bids","Timeouts",b,a.timeToRespond,h))})});d()}function v(a){var b=e(a.cpm);x.push(function(){m++;window[u]("send","event",
"Prebid.js Bids","Wins",a.bidderCode,b,h)});d()}var r=b(7),k=b(5);a=b(4);var y=a.EVENTS.BID_REQUESTED,q=a.EVENTS.BID_TIMEOUT,f=a.EVENTS.BID_RESPONSE,w=a.EVENTS.BID_WON,h={nonInteraction:!0},x=[],u=null,A=!0,m=0,z=!1,p=[];c.enableAnalytics=function(a){u="undefined"!==typeof a.global?a.global:"ga";"undefined"!==typeof a.enableDistribution&&(z=a.enableDistribution);var b=null;a=r.getEvents();k._each(a,function(a){var c=a.args;a&&(a.eventType===y?(b=c[0],g(b)):a.eventType===f?(b=c[1],l(b)):a.eventType===
q?p=c[0]:a.eventType===w&&(b=c[0],v(b)))});r.on(y,function(a){g(a)});r.on(f,function(a,b){l(b);n(b)});r.on(q,function(a){p=a});r.on(w,function(a){v(a)})}},function(a,c,b){function d(a,b){var c=0,c="undefined"===("undefined"===typeof a?"undefined":q(a))||null===a?f.bidderTimeout:a;if(f.adUnits&&0!==f.adUnits.length){setTimeout(x.executeCallback,c);if(b&&h.isArray(b))for(c=0;c<b.length;c++)for(var d=0;d<f.adUnits.length;d++)f.adUnits[d].code===b[c]&&D.push(f.adUnits[d]);else D=f.adUnits;for(c=0;c<D.length;c++){for(var d=
D[c][w.JSON_MAPPING.PL_CODE],e=D[c][w.JSON_MAPPING.PL_CODE],k=D[c][w.JSON_MAPPING.PL_SIZE],m=D[c][w.JSON_MAPPING.PL_BIDS],l=0;l<m.length;l++){var n=m[l];n.placementCode=e;n.sizes=k;var p=m[l][w.JSON_MAPPING.BD_BIDDER],r=H[p];"undefined"===("undefined"===typeof r?"undefined":q(r))?(r={bidderCode:p,bids:[]},r.bids.push(n),H[p]=r):r.bids.push(n)}x.addBidResponse(d)}for(c=0;c<O.length;c++)O[c].loadPreBid();x.setBidderMap(H);g()}else h.logMessage("No adUnits configured. No bids requested.")}function e(){if(!M){M=
!0;var a=x.getTimedOutBidders();p.emit(J,a)}}function g(a){var b=h._map(H,function(a){return a});"function"===("undefined"===typeof a?"undefined":q(a))&&b.sort(a);u.callBids(b)}function l(a){var b={};a&&0!==a.length&&(a.sort(function(a,b){return b.cpm-a.cpm}),b=a[0]);return b.bid}function n(a,b){var c=y(b);L[a]?h.extend(L[a],c):L[a]=c;h._each(L[a],function(a,c){b.setTargeting(c,"")});for(var d in c)if(c.hasOwnProperty(d))try{h.logMessage("Attempting to set key value for slot: "+b.getSlotElementId()+
" key: "+d+" value: "+encodeURIComponent(c[d])),b.setTargeting(d,c[d])}catch(e){h.logMessage("Problem setting key value pairs in slot: "+e.message)}}function v(a){var b={};return a?b=x.pbBidResponseByPlacement[a]:x.pbBidResponseByPlacement}function r(a){var b=[],c="",d=[],e={};if(a&&a[0]&&a[0].adUnitCode){c=a[0]&&a[0].adUnitCode;E[c]={};for(var f=0;f<a.length;f++){var g=a[f],e={};g&&(e=JSON.stringify(g),e=JSON.parse(e),delete e.pbLg,delete e.pbMg,delete e.pbHg);g.alwaysUseBid&&e.adserverTargeting?
E[e.adUnitCode]=h.extend(E[e.adUnitCode],e.adserverTargeting):g.cpm&&0<g.cpm&&d.push({cpm:g.cpm,bid:g});b.push(e)}}c&&0!==d.length&&(a=l(d).adserverTargeting,E[c]=h.extend(E[c],a));return b}function k(){x.clearAllBidResponses();H={};D=[];E={};M=!1}function y(a){var b=null;a&&((b=f.getAdserverTargetingForAdUnitCode(a.getSlotElementId()))||(b=f.getAdserverTargetingForAdUnitCode(a.getAdUnitPath())));return b}$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();var q="function"===typeof Symbol&&
"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){$jscomp.initSymbol();$jscomp.initSymbol();return a&&"function"===typeof Symbol&&a.constructor===Symbol?"symbol":typeof a};window.pbjs=window.pbjs||{};window.pbjs.que=window.pbjs.que||[];var f=window.pbjs,w=b(4),h=b(5),x=b(3),u=b(1),A=b(10),m=b(9),z=b(13),p=b(7),B=w.EVENTS.BID_WON,J=w.EVENTS.BID_TIMEOUT,O=[],D=[],H={},E={},L={},M=!1,N={bidWon:function(a){var b=h._map(D,function(a){return a.code});if(h.contains(b,a))return!0;
h.logError('The "'+a+'" placement is not defined.')}};f.bidderTimeout=f.bidderTimeout||3E3;f.logging=f.logging||!1;f.libLoaded=!0;h.logInfo("Prebid.js v0.7.0 loaded");f.adUnits=f.adUnits||[];f.que.push=function(a){if("function"===("undefined"===typeof a?"undefined":q(a)))try{a.call()}catch(b){h.logError("Error processing command :"+b.message)}else h.logError("Commands written into pbjs.que.push must wrapped in a function")};f.getAdserverTargetingForAdUnitCodeStr=function(a){h.logInfo("Invoking pbjs.getAdserverTargetingForAdUnitCodeStr",
arguments);if(a){var b=f.getAdserverTargetingForAdUnitCode(a);return h.transformAdServerTargetingObj(b)}h.logMessage("Need to call getAdserverTargetingForAdUnitCodeStr with adunitCode")};f.getAdserverTargetingForAdUnitCode=function(a){h.logInfo("Invoking pbjs.getAdserverTargetingForAdUnitCode",arguments);f.getBidResponses(a);return a?E[a]:E};f.getAdserverTargeting=function(){h.logInfo("Invoking pbjs.getAdserverTargeting",arguments);return f.getAdserverTargetingForAdUnitCode()};f.getBidResponses=function(a){h.logInfo("Invoking pbjs.getBidResponses",
arguments);var b={},c=[],d={};if(a)b=v(a),c=[],b&&b.bids&&(c=r(b.bids)),d={bids:c};else{var b=v(),e;for(e in b)b.hasOwnProperty(e)&&(b&&b[e]&&b[e].bids&&(c=r(b[e].bids)),d[e]={bids:c})}return d};f.getBidResponsesForAdUnitCode=function(a){h.logInfo("Invoking pbjs.getBidResponsesForAdUnitCode",arguments);return f.getBidResponses(a)};f.setTargetingForAdUnitsGPTAsync=function(a){h.logInfo("Invoking pbjs.setTargetingForAdUnitsGPTAsync",arguments);if(window.googletag&&h.isFn(window.googletag.pubads)&&h.isFn(window.googletag.pubads().getSlots)){e();
var b=a;"string"===("undefined"===typeof a?"undefined":q(a))?b=[a]:"object"===("undefined"===typeof a?"undefined":q(a))&&(b=a);var c=0,d;if(b)for(c=0;c<b.length;c++){var f=b[c];d=window.googletag.pubads().getSlots();for(var g=0;g<d.length;g++)if(d[g].getSlotElementId()===f||d[g].getAdUnitPath()===f)v(f),n(f,d[g])}else for(d=window.googletag.pubads().getSlots(),c=0;c<d.length;c++)(b=d[c].getSlotElementId())&&n(b,d[c])}else h.logError("window.googletag is not defined on the page")};f.setTargetingForGPTAsync=
function(a){h.logInfo("Invoking pbjs.setTargetingForGPTAsync",arguments);f.setTargetingForAdUnitsGPTAsync(a)};f.allBidsAvailable=function(){h.logInfo("Invoking pbjs.allBidsAvailable",arguments);return x.allBidsBack()};f.renderAd=function(a,b){h.logInfo("Invoking pbjs.renderAd",arguments);h.logMessage("Calling renderAd with adId :"+b);if(a&&b)try{var c=x._adResponsesByBidderId[b];if(c){p.emit(B,c);var d=c.height,e=c.width,f=c.adUrl,g=c.ad;if(g){if(a.write(g),a.close(),a.defaultView&&a.defaultView.frameElement){a.defaultView.frameElement.width=
e;a.defaultView.frameElement.height=d;try{a.defaultView.parent.frameElement&&(a.defaultView.parent.frameElement.width=e,a.defaultView.parent.frameElement.height=d),a.defaultView.frameElement.parentNode.parentNode._prebidded=b}catch(k){}}}else if(f){a.write('<IFRAME SRC="'+f+'" FRAMEBORDER="0" SCROLLING="no" MARGINHEIGHT="0" MARGINWIDTH="0" TOPMARGIN="0" LEFTMARGIN="0" ALLOWTRANSPARENCY="true" WIDTH="'+e+'" HEIGHT="'+d+'"></IFRAME>');a.close();a.defaultView&&a.defaultView.frameElement&&(a.defaultView.frameElement.width=
e,a.defaultView.frameElement.height=d);try{a.defaultView.parent.frameElement&&(a.defaultView.parent.frameElement.width=e,a.defaultView.parent.frameElement.height=d),a.defaultView.frameElement.parentNode.parentNode._prebidded=b}catch(k){}}else h.logError("Error trying to write ad. No ad for bid response id: "+b)}else h.logError("Error trying to write ad. Cannot find ad by given id : "+b)}catch(k){h.logError("Error trying to write ad Id :"+b+" to the page:"+k.message)}else h.logError("Error trying to write ad Id :"+
b+" to the page. Missing document or adId")};f.requestBidsForAdUnit=function(a){k();d(a)};f.requestBidsForAdUnits=function(a){if(a&&a.constructor===Array){k();var b=f.adUnits.slice(0);f.adUnits=a;d();f.adUnits=b}else h.logError("requestBidsForAdUnits must pass an array of adUnits")};f.removeAdUnit=function(a){h.logInfo("Invoking pbjs.removeAdUnit",arguments);if(a)for(var b=0;b<f.adUnits.length;b++)f.adUnits[b].code===a&&f.adUnits.splice(b,1)};f.requestBids=function(a){h.logInfo("Invoking pbjs.requestBids",
arguments);if(a){var b=a.adUnitCodes,c=a.adUnits,e=a.timeout,g=a.bidsBackHandler,m=f.adUnits.slice(0);"function"===("undefined"===typeof g?"undefined":q(g))&&x.addOneTimeCallback(g);b&&h.isArray(b)?(k(),d(e,b)):c&&h.isArray(c)?(k(),f.adUnits=c,d(e)):(b=e,k(),d(b));f.adUnits=m}else k(),d(void 0)};f.addAdUnits=function(a){h.logInfo("Invoking pbjs.addAdUnits",arguments);h.isArray(a)?f.adUnits.push.apply(f.adUnits,a):"object"===("undefined"===typeof a?"undefined":q(a))&&f.adUnits.push(a)};f.onEvent=function(a,
b,c){h.logInfo("Invoking pbjs.onEvent",arguments);if(h.isFn(b))if(c&&!N[a].call(null,c))h.logError('The id provided is not valid for event "'+a+'" and no handler was set.');else p.on(a,b,c);else h.logError('The event handler provided is not a function and was not set on event "'+a+'".')};f.offEvent=function(a,b,c){h.logInfo("Invoking pbjs.offEvent",arguments);c&&!N[a].call(null,c)||p.off(a,b,c)};f.addCallback=function(a,b){h.logInfo("Invoking pbjs.addCallback",arguments);var c=null;if(!a||!b||"function"!==
("undefined"===typeof b?"undefined":q(b)))return h.logError("error registering callback. Check method signature"),c;c=h.getUniqueIdentifierStr;x.addCallback(c,b,a);return c};f.removeCallback=function(){return null};f.registerBidAdapter=function(a,b){h.logInfo("Invoking pbjs.registerBidAdapter",arguments);try{u.registerBidAdapter(a(),b)}catch(c){h.logError("Error registering bidder adapter : "+c.message)}};f.bidsAvailableForAdapter=function(a){h.logInfo("Invoking pbjs.bidsAvailableForAdapter",arguments);
for(var b=H[a].bids,c=0;c<b.length;c++){var d=b[c].placementCode,e=x.pbBidResponseByPlacement[d],f=A.createBid(1);f.bidderCode=a;f.adUnitCode=d;f.bidder=a;e.bids.push(f);e.bidsReceivedCount++;x.pbBidResponseByPlacement[d]=e}x.increaseBidResponseReceivedCount(a)};f.createBid=function(a){h.logInfo("Invoking pbjs.createBid",arguments);return A.createBid(a)};f.addBidResponse=function(a,b){h.logInfo("Invoking pbjs.addBidResponse",arguments);x.addBidResponse(a,b)};f.loadScript=function(a,b,c){h.logInfo("Invoking pbjs.loadScript",
arguments);m.loadScript(a,b,c)};f.enableAnalytics=function(a){h.logInfo("Invoking pbjs.enableAnalytics",arguments);if(!a)h.logError("pbjs.enableAnalytics should be called with option {}","prebid.js");else if("ga"===a.provider)try{z.enableAnalytics("undefined"===typeof a.options?{}:a.options)}catch(b){h.logError("Error calling GA: ","prebid.js",b)}else if("other_provider"===a.provider)return null};f.sendTimeoutEvent=function(){h.logInfo("Invoking pbjs.sendTimeoutEvent",arguments);e()};f.aliasBidder=
function(a,b){h.logInfo("Invoking pbjs.aliasBidder",arguments);a&&b?u.aliasBidAdapter(a,b):h.logError("bidderCode and alias must be passed as arguments","pbjs.aliasBidder")};(function(){for(var a=0;a<f.que.length;a++)if("undefined"===q(f.que[a].called))try{f.que[a].call(),f.que[a].called=!0}catch(b){h.logError("Error processing command :","prebid.js",b)}})()}]);
var NSGPT=NSGPT||function(){var a=window,c={},b={prebidding:{rubicon:!0,appnexus:{"default":{placementId:6343305},homepage:{placementId:6343484},general:{placementId:6343480}}},adchannel:"",responsive:!0,gpttimeout:600,zdbburl:"//ns.zdbb.net/nsgpt.jsonp",libraries:["//native.sharethrough.com/assets/tag.js"],forceReflow:!1,adpath:"/4585/ns.macrumors/",oop:[],autostart:!0,adrecovery:!1,zdbeaconurl:"//track.netshelter.net/async/js/sites/macrumors.com-async.js",atfthreshold:700,gptsync:!1,maxads:!1},
d={leaderboard:{size:[728,90],pos:"atf",collapse:!1,refreshonviewable:30,sizemap:{"750x180":[728,90],"0x0":[300,250]}},billboard:{size:[[728,90],[970,250],[970,180],[970,90],[997,123]],pos:"atf",collapse:!0,refreshonviewable:30,sizemap:{"997x250":[[728,90],[997,123],[970,250],[970,180],[970,90]],"970x250":[[728,90],[970,250],[970,180],[970,90]],"700x100":[728,90],"0x0":[[320,50],[300,250]]}},bb:{size:[[970,250],[970,180]],pos:"atf",collapse:!0,refreshonviewable:30,sizemap:{"997x250":[[970,250],[970,
180]],"970x250":[[970,250],[970,180]],"700x100":[728,90],"0x0":[[320,50],[300,250]]}},rectangle:{size:[300,250],collapse:!1,sizemap:null,refreshonviewable:30},largerectangle:{size:[[336,280],[300,250]],collapse:!1,sizemap:null,refreshonviewable:30},halfpage:{size:[[300,250],[300,600]],collapse:!1,sizemap:null,refreshonviewable:30},portrait:{size:[[300,600],[300,1050],[300,250]],collapse:!1,sizemap:null,refreshonviewable:30},skyscraper:{size:[[120,600],[160,600]],collapse:!1,sizemap:null,refreshonviewable:30},
footer:{size:[[970,90],[728,90],[997,123],[970,180]],pos:"btf",collapse:!1,refreshonviewable:30,sizemap:{"970x125":[[970,90],[728,90],[997,123]],"700x100":[[728,90]],"0x0":[[320,50],[300,250]]}},"native":{size:[1,1],collapse:!0,sizemap:null,refreshonviewable:!1}},e=!1,g=[],l=b.adpath&&-1!=b.adpath.indexOf("/4585/zd.")?{cmn:"zd"}:{},n="https:"==a.location.protocol?"https:":"http:",v=window!=window.top&&window.frameElement&&window.inDapIF?!0:!1;try{!v&&window!=window.top&&window.frameElement&&window.frameElement.parentNode&&
(v=!0)}catch(ja){}var r=!1,k=null,y=0,q=0,f={},w=!1,h=function(){return"xxxxxxxxxxxyxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})},x=function(b){for(var c=1;10>c;c++){var d=b+"-"+c;if(!a.document.getElementById(d))return d}},u=function(a){return a?a.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""):""},A=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},m=function(a,b,c){if(e&&"undefined"!==typeof console&&console.log)try{b?
console.log("[NSGPT]["+(b.id?b.id:b)+"]: "+a):console.log("[NSGPT]: "+a),c&&console.log(c)}catch(d){}},z=function(b){b&&setTimeout(function(){try{var c=b.style.display;b.style.display="none";b.style.display=c;a.dispatchEvent(new Event("resize"))}catch(d){}},2E3)},p=function(b,c){if(!a.googletag||!a.googletag.apiReady||b)if(!a.document.getElementById("ns-bts-g")||b){var d=a.document.createElement("script");d.type="text/javascript";d.async="true";d.id="ns-bts-g";d.src=n+"//www.googletagservices.com/tag/js/gpt.js";
d.onerror=function(){a.document.getElementById("ns-bts-g1")||(d.id="ns-bts-g1");NSGPT.loadGPT()};var e=a.document.getElementsByTagName("script")[0];e.parentNode.insertBefore(d,e);"undefined"!==typeof pbjs&&(pbjs.initAdserverSet=!0)}},B=function(c,d,e){c||(c=a);if(b.zdbeaconurl&&!c.document.getElementById("ns-bts-zdt"))if(!c.document||!c.document.body)setTimeout(B,50);else if(!c.document.querySelector||!c.document.querySelector("script[src*='track.netshelter.net']")){var f=document.createElement("script");
f.type="text/javascript";f.async="true";f.id="ns-bts-zdt";d=n+b.zdbeaconurl;f.src=e&&c._sp_&&c._sp_.getSafeUri?c._sp_.getSafeUri(d):d;f.onerror=function(){c.document.getElementById("ns-bts-zdt1")||(f.id="ns-bts-zdt1");NSGPT.loadZDT()};try{c.document.body.appendChild(f)}catch(g){setTimeout(B,50)}}},J=function(d,e){if(!c||!c.zdid||d){if((d||e)&&a.document.getElementById("ns-bts-zdbb")){var t=a.document.getElementById("ns-bts-zdbb");t.id="ns-bts-zdbb-old";t.parentNode.removeChild(t)}if(v&&parent.NSGPT&&
parent.NSGPT.zdbbData&&parent.NSGPT.zdbbData.zdid)c=parent.NSGPT.zdbbData;else if(!a.document.getElementById("ns-bts-zdbb")){t=document.createElement("script");t.type="text/javascript";t.async="true";t.id="ns-bts-zdbb";var f=n+b.zdbburl+"?u="+encodeURIComponent(v?a.parent.location.href:a.location.href);t.src=e&&window._sp_&&window._sp_.getSafeUri?window._sp_.getSafeUri(f):f;t.onerror=function(){a.document.getElementById("ns-bts-zdbb1")||(t.id="ns-bts-zdbb1");NSGPT.loadZDBB()};f=a.document.getElementsByTagName("script")[0];
f.parentNode.insertBefore(t,f)}}},O=function(){J();b.autostart&&p();b.adrecovery&&L();if(b.libraries)for(var c=0;c<b.libraries.length;c++)D(b.libraries[c]);b.prebidding&&Z();if(b.autostart&&!(0<y)){a.googletag=a.googletag||{};a.googletag.cmd=a.googletag.cmd||[];a.googletag.cmd.push(function(){V()});b.gpttimeout&&!b.prebidding&&a.googletag.cmd.push(function(){setTimeout(G,b.gpttimeout)});y=1;c=a.document&&a.document.readyState?a.document.readyState:null;if("complete"===c){if(b.prebidding){setTimeout(G,
500);return}return G()}"interactive"===c?b.prebidding?setTimeout(G,500):G():c&&"loading"!==c||(a.jQuery?a.jQuery(G):a.document.addEventListener&&a.document.addEventListener("DOMContentLoaded",G,!1));if(a.addEventListener)a.addEventListener("load",G,!1);else{var d=a.onload;a.onload=function(){try{G()}catch(a){}d&&d()}}}},D=function(b,c){if(b){var d="nsgpt-ldr-"+b.replace(/\W+/g," ");if(!(a.document.getElementById(d)||a.document&&a.document.querySelector&&a.document.querySelector('[src*="'+b+'"]'))){var e=
a.document.createElement("script");e.type="text/javascript";e.async="true";e.id=d;-1==b.indexOf("://")&&(b=n+b);e.src=b;d=a.document.getElementsByTagName("script")[0];d.parentNode.insertBefore(e,d)}}},H=function(){try{for(var b=document.getElementsByTagName("script"),c=b.length,d=0;d<c;d++)b[d]&&b[d].src&&-1!=b[d].src.indexOf("partner.googleadservices.com/gpt/pubads_impl")&&(b[d].onload=null,b[d].onerror=null,b[d].parentNode.removeChild(b[d]))}catch(e){m("GPT pubads unload warning - "+e)}a.googletag&&
(a.googletag.pubads&&(a.googletag.pubads().disableInitialLoad(),a.googletag.pubads().clear(),a.googletag.pubads().clearCategoryExclusions(),a.googletag.pubads().clearTagForChildDirectedTreatment()),a.googletag.impl&&(a.googletag.impl=null),a.googletag.pubads&&(a.googletag.pubads=null),a.googletag.defineSlot=null,a.googletag.defineOutOfPageSlot=null,a.googletag.enableServices=null,a.google_persistent_state&&(a.google_persistent_state=null));a.googletag=null;a.googletag={};a.googletag.cmd=[];c=I();
g=[];for(d=0;d<c.length;d++)if(b=c[d])m("Resetting adslot",b),!b._gptSlot&&b.parentNode&&b.parentNode._gptSlot&&(b=b.parentNode),b._gptSlot&&(b._gptSlot=null),b._nsgptWatchdog&&(clearTimeout(b._nsgptWatchdog),b._nsgptWatchdog=null),b._refreshOnViewableTimeout&&(clearTimeout(b._refreshOnViewableTimeout),b._refreshOnViewableTimeout=null),b._refreshOnRenderedTimeout&&(clearTimeout(b._refreshOnRenderedTimeout),b._refreshOnRenderedTimeout=null),b._refreshOnViewable&&(b._refreshOnViewable=null,b._refreshOnRendered=
null);for(var f=document.getElementsByTagName("iframe"),c=f.length,d=0;d<c;d++)(b=f[d])&&b.id&&0==b.id.indexOf("google_ads_iframe_")&&(0==b.parentNode.id.indexOf("google_ads_iframe_")&&(b=b.parentNode),b.parentNode.removeChild(b));f=document.getElementsByTagName("iframe");c=f.length;for(d=0;d<c;d++)(b=f[d])&&b.id&&0==b.id.indexOf("google_ads_iframe_")&&(0==b.parentNode.id.indexOf("google_ads_iframe_")&&(b=b.parentNode),b.parentNode.removeChild(b))},E=function(){if(b.adrecovery&&b.adrecovery.indexOf&&
-1==b.adrecovery.indexOf("//")&&!a._sp_){a.sp_cid="kpwbBOFeVRnEVFP";var c=a.document.createElement("script");c.type="text/javascript";c.async="async";c.id="ns-bts-sp";c.src=n+b.adrecovery;c.onerror=function(){a.document.getElementById("ns-bts-sp1")||(c.id="ns-bts-sp1");NSGPT.bootstrap()};var d=a.document.getElementsByTagName("script")[0];d.parentNode.insertBefore(c,d)}},L=function(){E();a&&a.document&&a.document.addEventListener&&a.document.addEventListener("sp.blocking",M);a._sp_&&a._sp_.checkState&&
a._sp_.checkState(function(a){a&&M()})},M=function(c){b.prebidding=!1;w=!0;1<q||(q=1,J(!1,!0),a.googletag&&a.googletag.apiReady&&a.googletag.enableServices(),q=2,N())},N=function(){if(!(2<q)){1<y&&(y=1);if(b.adchannel&&"homepage"!=b.adchannel&&"general"!=b.adchannel||!a.googletag||!a.googletag.apiReady)b.adchannel||(b.adchannel="homepagedoor");else for(var c=a.googletag.pubads().getSlots(),d=0;d<c.length;d++)if(c[d]){var e=c[d].getAdUnitPath();if(-1!=e.indexOf(b.adpath))try{if(b.adchannel=e.split("/")[e.split("/").length-
1].split("_")[0],b.adchannel)break}catch(f){}c[d].getTargeting("template")&&(l.template=c[d].getTargeting("template"))}H();a._sp_.dfp.loadGPT();q=3;setTimeout(function(){a.googletag.cmd.push(function(){window.NSGPT.setupAdslots();a.googletag.pubads().enableAsyncRendering();a.googletag.pubads().enableSingleRequest();a.googletag.pubads().setCentering(!0);a.googletag.enableServices()});a.googletag.cmd.push(R)},10);return!0}},R=function(){3>q?N():5<q||(a.googletag&&a.googletag.pubadsReady&&c&&c.zdid?
(window.NSGPT.renderAds(),q+=1):(a.googletag&&a.googletag.apiReady&&a.googletag.enableServices(),setTimeout(R,30)))},Y=function(b){try{m("Prebidder Responses",null,b);var c=a.location.hostname,d;for(d in b)if(b.hasOwnProperty(d)){var e=function ha(a){return a?(a^16*Math.random()>>a/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,ha)}(),f=b[d]&&b[d].bids?b[d].bids.length:0;f||m("No bids found for "+d);for(var g=0;g<f;g++)try{var h=b[d].bids[g],k="NA",l=h.bidderCode?h.bidderCode:
"",p=h.cpm?h.cpm:"",q=h.adId?h.adId:"",r=h.adUnitCode?h.adUnitCode:"",u=h.timeToRespond?h.timeToRespond:"",x=h.statusMessage?h.statusMessage:"",y=0;0!=h.cpm&&(y=h.adserverTargeting.hb_pb,k=h.size);(new Image).src=n+"//zdbb.net/l/EBd3N5GSEeWA3CIAC7Ppng?bidder="+l+"&provider=prebid&site="+c+"&cpm="+p+"&bsid="+e+"&bid="+y+"&adid="+q+"&adunit="+r+"&size="+k+"&ttr="+u+"&status="+encodeURIComponent(x)}catch(w){m("prebidder ZDBB error: "+w)}}}catch(v){m("prebidder error: "+v)}},S=function(a,c){if(!b.prebidding)return!1;
var d=[],e=[];a||(a=I());for(var g=0;g<a.length;g++){var h=a[g];if(h&&!h._prebidding){if(!h.id){var k=P(h);if(!k)continue;h.id=x("nsgpt-"+k)}if(-1==h.id.indexOf("-oop")&&-1==h.id.indexOf("-native"))if("undefined"!==typeof f[h.id])h._prebidding=!0;else{P(h);k=aa(h);c=[];var m=b.adchannel||"general",l;for(l in b.prebidding){var n=m,p=b.prebidding[l];"appnexus"==l?("undefined"===typeof b.prebidding[l][n]&&(n="default"),p=b.prebidding[l][n]):"rubicon"==l&&((n=h._gptPos?h._gptPos:ba(h))||(n="atf"),p={accountId:"11576",
siteId:"88252",zoneId:"416734",keywords:"macrumors.com",inventory:{site:"macrumors.com",pos:n,adunit:b.adchannel}});c.push({bidder:l,params:p})}d.push({sizes:k,code:h.id,bids:c});f[h.id]=!0;h._prebidding=!0;e.push(h)}}}pbjs.addAdUnits(d);return e},Z=function(a){if(!b.prebidding)return!1;v&&(window.top.pbjs||(window.top.pbjs={}),window.top.pbjs.renderAd&&!window.top.pbjs._renderAd&&(window.top.pbjs._renderAd=window.top.pbjs.renderAd),window.top.pbjs.renderAd=function(a,b){m("Rendering prebidded creative: "+
b);var c=a.defaultView.parent,d=c.pbjs;!c.rubicontag&&window.rubicontag&&(c.rubicontag=window.rubicontag);try{c.rubicontag&&(window.top.rubicontag=c.rubicontag)}catch(e){}try{return d&&d._renderAd?d._renderAd(a,b):d&&d.renderAd?d.renderAd(a,b):window.top._renderAd(a,b)}catch(e){m("Prebidded creative render error: "+b,a),m(e)}});pbjs.bidderSettings={standard:{alwaysUseBid:!1,adserverTargeting:[{key:"hb_bidder",val:function(a){return a.bidderCode}},{key:"hb_adid",val:function(a){return a.adId}},{key:"hb_pb",
val:function(a){return 200<a.cpm?(10*Math.floor(Math.min(parseInt(a.cpm),500)/10)).toFixed(2):40<a.cpm?Math.floor(a.cpm).toFixed(2):30<a.cpm?(Math.floor(10*a.cpm)/10).toFixed(2):a.cpm.toFixed(2)}},{key:"hb_size",val:function(a){return a.size}},{key:"hb_cpm",val:function(a){return a.cpm}}]}};pbjs.que.push(function(){var b=S(a);b&&b.length&&pbjs.requestBids({timeout:800,bidsBackHandler:function(a){Y(a);v&&ca()}})})},ga=function(a){a&&a.id&&a._gptSlot&&pbjs.que.push(function(){a._prebidding||S([a]);
pbjs.requestBids({timeout:800,adUnitCodes:[a.id],bidsBackHandler:function(b){Y(b);pbjs.setTargetingForGPTAsync([a.id]);Q([a],null,!0)}})})},K=function(a,b,c){var e=a.dataset&&"undefined"!==typeof a.dataset[b]?a.dataset[b]:a.getAttribute("data-"+b);if(null===e||"null"===e||"undefined"===e)if(c)try{var f=P(a),e=d[f][b];"undefined"===typeof e&&(e=null);return e}catch(g){return null}else return null;e&&e.toLowerCase&&"true"===e.toLowerCase()?e=!0:e&&e.toLowerCase&&"false"===e.toLowerCase()?e=!1:e&&e.indexOf&&
(-1!=e.indexOf("{")||-1!=e.indexOf("["))&&(e="undefined"!==typeof JSON?JSON.parse(e):eval("("+e+")"));return e},P=function(a){if(a._nsSlotName)return a._nsSlotName;var b=a.dataset&&"undefined"!==typeof a.dataset.ns&&a.dataset.ns?a.dataset.ns:a.getAttribute("data-ns");if(!b)return m("Missing NS param",a),"";b=u(b).toLowerCase();if("mediumrectangle"==b||"mrec"==b||"mpu"==b)b="rectangle";"adsense"==b&&(b="largerectangle");"hpu"==b&&(b="halfpage");"outofpage"==b&&(b="oop");"sky"==b&&(b="skyscraper");
"sharethrough"==b&&(b="native");"lb"==b&&(b="leaderboard");return a._nsSlotName=b},T=function(a){var c=a?K(a,"channel"):b.adchannel;null===c&&(c=b.adchannel);c||(c="");b.adpath&&0===b.adpath.indexOf("/4585/")||(b.adpath="/4585/");"/"!=b.adpath.substr(b.adpath.length-1)&&(b.adpath+="/");if(a&&-1!=b.adpath.indexOf("/4585/zd.")){var d=a.id;a.getAttribute&&a.getAttribute("data-pos")?c=c+"_"+a.getAttribute("data-pos").toUpperCase():-1==d.indexOf("Top")&&-1==d.indexOf("ad401-")&&-1==d.indexOf("ad403-")||
-1!=c.indexOf("_ATF")?-1==d.indexOf("Bottom")&&-1==d.indexOf("ad414-")&&-1==d.indexOf("ad415-")||-1!=c.indexOf("_BTF")?-1!=d.indexOf("Content")&&-1==c.indexOf("_ATF2")?(c+="_ATF2",a.setAttribute("data-pos","atf")):-1!=d.indexOf("Native")&&-1==c.indexOf("_native")&&(c+="_native"):(c+="_BTF",a.setAttribute("data-pos","btf")):(c+="_ATF",a.setAttribute("data-pos","atf"))}return b.adpath+c},aa=function(a){var b=K(a,"size",!0);a=[];if("string"===typeof b){for(var b=-1!=b.indexOf(",")?b.split(","):b.split(";"),
c=0;c<b.length;c++){var d=b[c].split("x");a.push([parseInt(d[0]),parseInt(d[1])])}if(1==a.length)return a[0]}else b&&(a=b);return a},I=function(){var a=[];if(document.querySelectorAll){var b=document.querySelectorAll("div[data-ns]");if(!b||!b.length)return a;for(var c=0;c<b.length;c++)a.push(b[c])}else if(window.jQuery)a=window.jQuery("div[data-ns]").get();else for(b=document.getElementsByTagName("div"),c=0;c<b.length;c++)b[c].getAttribute("data-ns")&&a.push(b[c]);return a.indexOf||a.length?a:[]},
U=function(){try{return"undefined"!==typeof top.document.hidden?top.document.hidden.toString():top.document.hasFocus()?"false":"true"}catch(b){return"undefined"!==typeof a.document.hidden?a.document.hidden.toString():a.document.hasFocus()?"false":"true"}},ba=function(a){var c=K(a,"pos",!0);if("string"===typeof c&&c)return c;a=a.getBoundingClientRect();var c=document.body,d=document.documentElement;a=Math.round(a.top+(window.pageYOffset||d.scrollTop||c.scrollTop)-(d.clientTop||c.clientTop||0));try{return a<
b.atfthreshold||a<screen.height/2?"atf":"btf"}catch(e){return null}},W=function(a,b,c){!b&&a._gptSlot&&(b=a._gptSlot);var e=P(a);try{if(e&&d[e]&&d[e].targeting)for(var f in d[e].targeting)d[e].targeting[f]&&(b=b.setTargeting(f,d[e].targeting[f]))}catch(g){}if(e=K(a,"targeting",!1))for(f in e)e[f]&&(b=b.setTargeting(f,e[f]));if(e=K(a,"sharethrough",!1))b=b.setTargeting("sharethrough","true"),b=b.setTargeting("strnativekey",e),D("//native.sharethrough.com/assets/tag.js");if(c)for(f in c)c[f]&&(b=b.setTargeting(f,
c[f]));b=b.setTargeting("OOF",U());if(a&&-1==a.id.indexOf("nsgpt-oop-"))try{var h=a._gptPos?a._gptPos:ba(a);"string"===typeof h&&h&&(a._gptPos=h,a.dataset&&(a.dataset.pos=h),a.setAttribute("data-pos",h),b=b.setTargeting("ppos",h.toLowerCase()).setTargeting("pos",h.toLowerCase()))}catch(g){m(g,a)}return b},V=function(f,h){a.googletag.pubadsReady&&5>y&&m("WARNING: AdSlot setup started after gpt enableServices() invoked. Please reviese your non-netshelter GPT tags");if(2>y){if(!q&&b.oop)for(var t=0;t<
b.oop.length;t++){var k=b.oop[t]?b.oop[t]:t+1,F="nsgpt-oop-"+k;if(!document.getElementById(F)){var C=a.document.createElement("div");C.id=F;C.className="nsgpt-oop";C.style.position="absolute";C.style.left="0px";C.style.bottom="0px";C.dataset&&(C.dataset.ns="oop");C.setAttribute("data-ns","oop");a.document.body.appendChild(C);var n=a.googletag.defineOutOfPageSlot(T(),F).addService(googletag.pubads()),n=W(C,n,{OOP_type:k});C._gptSlot=n;g.push(C._gptSlot);m("Setup OOP adslot "+F,C)}}m("Setup GPT callbacks");
googletag.pubads().addEventListener("slotRenderEnded",ia);googletag.pubads().addEventListener("impressionViewable",da);y=2}if(3>y){a.googletag.pubads().enableAsyncRendering();a.googletag.pubads().enableSingleRequest();a.googletag.pubads().setCentering(!0);e&&googletag.pubads().setTargeting("debug","true");for(var p in c)null!==c[p]&&a.googletag.pubads().setTargeting(p,c[p]);a.location.search&&-1!=a.location.search.indexOf("special")&&(t=a.location.search.match(/(\?|&)special=([^&]*)/),a.googletag.pubads().setTargeting("special",
t?t[2]:""));if(l)for(p in l)null!==l[p]&&a.googletag.pubads().setTargeting(p,l[p]);y=3}if(!h){if(4<y||a.googletag.pubadsReady)return;if(a.document.readyState&&"loading"==a.document.readyState&&!r)return m("Waiting for DOM or timeout before setting up slots"),!1;if(!c||!c.zdid)return m("Waiting for ZDBB data before setting up slots"),!1}f||(f=I());m("Start page scan & adslot setup",null,f);for(p=0;p<f.length;p++)if((t=f[p])&&!t._gptSlot&&(k=P(t)))if(t.id||(t.id=x("nsgpt-"+k)),F="undefined"!==typeof d[k]?
d[k]:null){C=a.googletag.defineSlot(T(t),aa(t),t.id);try{if(b.responsive){var u;var w=K(t,"sizemap",!0);if(w){var v=a.googletag.sizeMapping(),n=void 0;for(n in w)var A=n.toLowerCase().split("x"),v=v.addSize([parseInt(A[0]),parseInt(A[1])],w[n]);u=v?v.build():null}else u=null;u&&(C=C.defineSizeMapping(u))}}catch(z){m(z,t)}try{var D=K(t,"collapse",!0);null!==D&&(C=C.setCollapseEmptyDiv(D))}catch(z){m(z,t)}try{b.prebidding&&!t._prebidding&&S([t])}catch(z){m(z,t)}W(t,C,{rfr:"false"});t._refreshOnRendered=
null;t._refreshOnViewable=null;try{var B="undefined"!==typeof F.refresh?F.refresh:null;F&&t._gptPos&&"atf"==t._gptPos&&"undefined"!==typeof F.refreshatf&&(B=F.refreshatf);B&&"string"===typeof B&&(B=parseInt(B));B&&(t._refreshOnRendered=1E3*B)}catch(z){m(z,t)}try{var E=K(t,"refreshonviewable",!0);E&&parseInt(E)&&(t._refreshOnViewable=1E3*parseInt(E))}catch(z){m(z,t)}t._gptSlot=C.addService(googletag.pubads());m("Setup adslot "+k+" - RefreshOnViewable: "+t._refreshOnViewable+" - Refresh On Rendered: "+
t._refreshOnRendered,t);g.push(t._gptSlot)}else m("Unkown config: "+k)},X=function(d){if(a.document.readyState&&"loading"==a.document.readyState&&!r)m("Waiting for DOM or timeout before rendering");else if(r||c&&c.zdid)if(r||!b.prebidding||"undefined"===typeof pbjs||pbjs.libLoaded&&pbjs.allBidsAvailable()){b.prebidding&&"undefined"!==typeof pbjs&&pbjs.libLoaded&&!A(f)&&5>y&&pbjs.setTargetingForGPTAsync();try{V(null,!0)}catch(e){return m("slotsetup error: "+e),!1}if(!a.googletag.pubadsReady)try{a.googletag.pubads().enableAsyncRendering(),
a.googletag.pubads().enableSingleRequest(),a.googletag.pubads().setCentering(!0),a.googletag.enableServices()}catch(e){m("Warning while init rendering - "+e)}if(!d||!d.length)d=I();else if(d.id||d.parentNode)d=[d];for(var g=0;g<d.length;g++){var h=d[g];if(h&&!h._gptRendered)if(!h._gptSlot&&h.parentNode&&h.parentNode._gptSlot&&(h=h.parentNode),h._gptSlot){h._prebidded=!1;var k=-1!=h.id.indexOf("nsgpt-oop-")?!0:!1;window.getComputedStyle(h);if(!q&&!k&&a.getComputedStyle){var l=a.getComputedStyle(h);
if("none"===l.display||"hidden"===l.visibility){m("Render: skipping invisible element",h);continue}}q?m("Rendering adrecovered slot",h):m("Rendering adslot",h);try{a.googletag.display(h.id)}catch(e){m("GPT error while rendering: "+e,h);continue}h._gptRendered=!0;q||k||h._nsgptWatchdog||(h._nsgptWatchdog=setTimeout(function(){m("NSGPT Watchdog forces a refresh for stale ad",h);NSGPT.refreshAds([h])},45E3));a.google_DisableInitialLoad&&a.googletag.pubads().refresh([h._gptSlot])}else q||m("Render: missing gptslot in "+
h.id)}y=5}else setTimeout(X,200);else m("Waiting for ZDBB data before rendering")},G=function(b){w||(b=a.document&&a.document.readyState?a.document.readyState:"",4<y&&"complete"==b||(m("Invoke DisplayAds: "+b),r=!0,a.googletag.cmd.push(function(){X()})))},Q=function(c,d,e){if(a.googletag.pubadsReady){if(!c)c=I();else if(c.id||c.parentNode)c=[c];d||(d=a.__ZDDMP&&a.__ZDDMP.NewCorrelator?__ZDDMP.NewCorrelator():h());for(var f=[],g=0;g<c.length;g++){var k=c[g];if(k&&(!k._gptSlot&&k.parentNode&&k.parentNode._gptSlot&&
(k=k.parentNode),k._gptSlot)){if(b.prebidding&&!e)return ga(k);var l=k._gptSlot;l.clearTargeting();l=W(k,l,{zc:d,rfr:"true"});k._nsgptRendered=null;k._nsgptViewable=null;k._refreshOnViewableTimeout&&(clearTimeout(k._refreshOnViewableTimeout),k._refreshOnViewableTimeout=null);k._refreshOnRenderedTimeout&&(clearTimeout(k._refreshOnRenderedTimeout),k._refreshOnRenderedTimeout=null);k._nsgptWatchdog&&(clearTimeout(k._nsgptWatchdog),k._nsgptWatchdog=null);q||(k._nsgptWatchdog=setTimeout(function(){m("NSGPT Watchdog force a refresh for stale ad",
k);NSGPT.refreshAds([k])},45E3));f.push(l);m("Issue refresh command",k)}}f&&a.googletag.pubads().refresh(f)}},ea=function(a){if(!a)a=I();else if(a.id||a.parentNode||a.frameElement)a=[a];for(var b=0;b<a.length;b++){var c=a[b];if(c){!c._gptSlot&&c.parentNode&&c.parentNode._gptSlot&&(c=c.parentNode);if(!c._gptSlot&&c.frameElement)try{c=c.frameElement.parentNode.parentNode}catch(d){}c._gptSlot&&(c._refreshOnViewable=null,c._refreshOnRendered=null,c._refreshOnViewableTimeout&&(clearTimeout(c._refreshOnViewableTimeout),
c._refreshOnViewableTimeout=null),c._refreshOnRenderedTimeout&&(clearTimeout(c._refreshOnRenderedTimeout),c._refreshOnRenderedTimeout=null),c._nsgptWatchdog&&(clearTimeout(c._nsgptWatchdog),c._nsgptWatchdog=null),m("Refresh stopped",c))}}},da=function(b){var c=a.document.getElementById(b.slot.getSlotElementId());c&&!c._gptSlot&&c.nextSibling&&c.nextSibling._gptSlot&&(c=c.nextSibling);if(c&&c._gptSlot&&(c._nsgptViewable=Math.floor((new Date).getTime()),c._nsgptRendered||(c._nsgptRendered=c.nsgptViewable),
c._refreshOnViewable||c._refreshOnViewableOverride)){b=c._refreshOnViewableOverride?c._refreshOnViewableOverride:c._refreshOnViewable;var d=Math.floor(c._nsgptViewable-c._nsgptRendered);d>b?(m("Slot viewable after "+b+"ms threshold - refreshing immediately",c),Q([c])):(d=Math.floor(b-d),c._refreshOnViewableTimeout=setTimeout(function(){NSGPT.refreshAds([c])},d),m("Slot viewable, but "+b+"ms threashold not hit yet - schedule a refresh in "+d+"ms",c))}},ia=function(c){var d=a.document.getElementById(c.slot.getSlotElementId());
d&&!d._gptSlot&&d.nextSibling&&d.nextSibling._gptSlot&&(d=d.nextSibling);if(d&&d._gptSlot){d._nsgptRendered=Math.floor((new Date).getTime());d._nsgptViewable=null;d._nsgptWatchdog&&(clearTimeout(d._nsgptWatchdog),d._nsgptWatchdog=null);if(c&&c.isEmpty)m("Slot Rendered - EMPTY",d);else try{m("Slot Rendered, Creative: "+c.creativeId+" LineItem:"+c.lineItemId+" size:"+c.size,d)}catch(e){m("Slot Rendered - error",d)}if(d._refreshOnRendered){var f=c.isEmpty?2E3:d._refreshOnRendered;d._refreshOnRenderedTimeout=
setTimeout(function(){NSGPT.refreshAds([d])},f);m("Slot refresh timeout at "+f+"ms",d)}if(!c||!c.isEmpty)if(b.forceReflow&&(z(d),setTimeout(function(){z(d)},1E3)),v&&window.frameElement&&c.size&&!d._prebidded)try{window.frameElement.width=c.size[0],window.frameElement.height=c.size[1],window.frameElement.frameElement&&(window.frameElement.frameElement.width=c.size[0],window.frameElement.frameElement.height=c.size[1])}catch(e){}}},fa=function(d,f,g,h){if(a!=a.parent){k||(k=a.document.getElementById("nsgpt"));
d=k.src;try{if(B(a.parent),a.parent.NSGPT&&a.parent.NSGPT.config&&a.parent.NSGPT.config.adchannel&&(b.adchannel=parent.NSGPT.config.adchannel),d&&!a.parent.NSGPT){var l=parent.document.createElement("script");l.type="text/javascript";l.async="true";l.id="nsgpt";l.dataset&&(l.dataset.prebidding="false");l.setAttribute("data-prebidding","false");var n=a.document.getElementsByTagName("head")[0];n.appendChild(l)}}catch(p){}}try{b.adchannel||(b.adchannel=a.parent.location.pathname&&"/"==a.parent.location.pathname?
"homepage":"general",m("init: adchannel autodetected: "+b.adchannel))}catch(p){b.adchannel||(b.adchannel="general")}b.autostart=!1;b.oop=!1;!parent.location.search||-1==parent.location.search.indexOf("nsgptdebug")&&-1==parent.location.search.indexOf("googfc")||(e=1,a.pbjs&&(a.pbjs.logging=!0));-1!=a.location.href.indexOf("phonearena.com")&&H();c&&c.zdid||(l=a.document.createElement("script"),l.type="text/javascript",l.async=!1,l.src=b.zdbburl+"?u="+encodeURIComponent(a.parent.location.href),n=a.document.getElementsByTagName("head")[0],
n.appendChild(l));I()?(a.googletag=a.googletag||{},a.googletag.cmd=a.googletag.cmd||[],b.prebidding?Z():ca()):m("No Adunit Found in adserved iframe "+window.name+" - please check your data-ns div")},ca=function(){r=!0;a.googletag=a.googletag||{};a.googletag.cmd=a.googletag.cmd||[];a.googletag.cmd.push(function(){window.NSGPT.setupAdslots()});a.googletag.cmd.push(function(){window.NSGPT.renderAds()});p()};return{adSlots:g,isIframe:v,zdbbData:c,config:b,init:function(c){k||(k=a.document.getElementById("nsgpt"));
!k&&a.document.querySelector&&(k=document.querySelector('[src*="cdn.nsstatic.net/ns/"]'));if(k){for(var d=["ns","channel"],f=0;f<d.length;f++){var g=d[f],h=k.dataset&&"undefined"!==typeof k.dataset[g]?k.dataset[g]:k.getAttribute("data-"+g);if(h){b.adchannel=u(h);m("init: adchannel override: "+l);break}}h=k.dataset&&"undefined"!==typeof k.dataset.responsive?k.dataset.responsive:k.getAttribute("data-responsive");null!==h&&(b.responsive="true"==u(h).toLowerCase()?!0:!1);h=k.dataset&&"undefined"!==typeof k.dataset.autostart?
k.dataset.autostart:k.getAttribute("data-autostart");null!==h&&(b.autostart="true"==u(h).toLowerCase()?!0:!1);h=k.dataset&&"undefined"!==typeof k.dataset.prebidding?k.dataset.prebidding:k.getAttribute("data-prebidding");null!==h&&(b.prebidding="true"==u(h).toLowerCase()?!0:!1);h=k.dataset&&"undefined"!==typeof k.dataset.oop?k.dataset.oop:k.getAttribute("data-oop");if(null!==h){var l=u(h).toLowerCase();m("init: OOP config override: "+l);b.oop="false"==l||"0"==l||""==l?[]:l.split(",")}}if(c&&!c.target){for(g in c)b[g]=
c[g];c.w&&c.w.top&&(a=c.w)}if(v)return fa();!b.adchannel&&a.location&&(b.adchannel=a.location.pathname&&"/"==a.location.pathname?"homepage":"general",m("init: adchannel autodetected: "+b.adchannel));!a.location.search||-1==a.location.search.indexOf("nsgptdebug")&&-1==a.location.search.indexOf("googfc")||(e=1,a.pbjs&&(a.pbjs.logging=!0));B();O()},bootstrap:O,forceReflow:z,loadZDBB:J,initZDBB:function(d,e){for(var f in d)c[f]=d[f];if(e)for(f in e)b[f]=e[f];a.googletag=a.googletag||{};a.googletag.cmd=
a.googletag.cmd||[];a.googletag.cmd.push(function(){for(var b in c)null!==c[b]&&a.googletag.pubads().setTargeting(b,c[b])});b.autostart&&a.googletag.cmd.push(function(){window.NSGPT.renderAds()})},loadZDT:B,startSP:N,renderSP:R,getAdSlots:I,setupAdslots:V,renderAds:X,displayAds:G,refreshAds:Q,stopRefresh:ea,updateRefresh:function(a,b,c){if(!a)a=I();else if(a.id||a.parentNode)a=[a];if(!b&&!c)return ea(a);for(var d=0;d<a.length;d++){var e=a[d];!e._gptSlot&&e.parentNode._gptSlot&&(e=e.parentNode);if(b){e._refreshOnViewableTimeout&&
(clearTimeout(e._refreshOnViewableTimeout),e._refreshOnViewableTimeout=null);if(e._nsgptViewable){var f=Math.floor((new Date).getTime())-e._nsgptViewable;f<b?Q([e]):e._refreshOnViewableTimeout=setTimeout(function(){NSGPT.refreshAds([e])},Math.floor(b-f))}else e._refreshOnViewableOverride=b;m("New RefreshOnViewable ("+b+") set",e)}c&&(e._refreshOnRenderedTimeout&&(clearTimeout(e._refreshOnRenderedTimeout),e._refreshOnRenderedTimeout=null),e._refreshOnRenderedTimeout=setTimeout(function(){NSGPT.refreshAds([e])},
1E3*c),m("New RefreshOnViewable ("+c+") set",e))}},onViewable:da,onLoaded:function(a){},detectOOF:U,adserve:fa,passback:function(e,f,h,g){c&&c.zdid||document.write('<script type="text/javascript" src="'+b.zdbburl+"?u="+encodeURIComponent(a.parent.location.href)+'">\x3c/script>');var k=T(),l=d[e];e=JSON.stringify(l.size);var n=['.setTargeting("OOF", '+JSON.stringify(U())+")",'.setTargeting("rfr", "false")'];h&&(n.push('.setTargeting("pos", "'+h+'")'),n.push('.setTargeting("ppos", "'+h+'")'));f=f?'.setClickUrl("'+
f+'")':"";for(var m in c)null!==c[m]&&n.push('.setTargeting("'+m+'", '+JSON.stringify(c[m])+")");a.location.search&&-1!=a.location.search.indexOf("special")&&(h=a.location.search.match(/(\?|&)special=([^&]*)/),n.push('.setTargeting("special", "'+(h?h[2]:"")+'")'));if(l.targeting)for(m in l.targeting)null!==l.targeting[m]&&n.push('.setTargeting("'+m+'", '+JSON.stringify(l.targeting[m])+")");if(g)for(m in g)null!==g[m]&&n.push('.setTargeting("'+m+'", '+JSON.stringify(g[m])+")");l.sizemap&&a.document&&
a.document.documentElement&&a.document.documentElement.clientWidth&&(g=document.documentElement.clientWidth,1E3>g&&(e=700<g?JSON.stringify([728,90]):JSON.stringify([[300,250],[320,50]])));f='<center><script src="//www.googletagservices.com/tag/js/gpt.js">googletag.pubads().definePassback("'+k+'", '+e+")"+n.join("")+f+".display();\x3c/script></center>";document.write(f);return!0}}}();"undefined"!==typeof window._NSGPT?NSGPT.init(window._NSGPT):NSGPT.init();
