(function ensightenInit(){var ensightenOptions = {client: "vzw", clientId: 476, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/vzw/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/vzw/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Wed Apr 06 00:45:32 GMT 2016", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(g){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=g.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:g.interval||100,erLoc:g.errorLocation||c.nexus+"/error/e.gif",scLoc:g.serverComponentLocation||c.nexus+"/"+g.client+"/serverComponent.php",sjPath:g.staticJavascriptPath||c.nexus+"/"+g.client+"/code/",alLoc:g.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:g.publishPath,isPublic:g.isPublic,client:g.client,clientId:g.clientId,enableTagAuditBeacon:g.enableTagAuditBeacon,scUseCacheBuster:g.scUseCacheBuster,beaconSamplingSeedValue:g.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),f;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(f=0;f<h.length;f++)if(h[f].src===a&&h[f].readyState&&/loaded|complete/.test(h[f].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;"object"===typeof d&&d.PageID&&(e=d.PageID,delete d.PageID);if("object"===typeof d)for(f in d){f=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,f.length?e.length-f.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";e=e.slice(0,-1)+
f;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,d){var c=
document.getElementsByTagName("script"),h;d=c[0];for(h=0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(f){window[ensightenOptions.ns].reportException(f)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=
this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};
b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});
else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,
l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var f=[];if(!c.checkForInvalidDependencies(e,l,d,h)){f.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});f.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:f,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,f=b.dataDefinitionIds.length,g=0;g<f;g++)if(b.dataDefinitionIds[g]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var d=b.dataDefinitions[e];d||(d=new b.DataDefinition(e,a),b.dataDefinitions[e]=d);d.startRegistrationTime||(d.startRegistration(),d.registrationFn(),d.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,d=a.length;b<d;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=
a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var q=function(){var a=[],b=!1,d=!1;return{add:function(c){b&&!d?c():"function"==typeof c&&(a[a.length]=c)},exec:function(){d=!0;do{var c=a;a=[];b=!0;for(var g=0;g<c.length;g++)try{c[g].call(window)}catch(f){window[ensightenOptions.ns].reportException(f)}}while(0<a.length);d=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,f=0;f<c.ruleList.length;++f)d=c.ruleList[f],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(g.client)+"/"+encodeURIComponent(g.publishPath)+
"/TagAuditBeacon.rnc?cid="+encodeURIComponent(g.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var g=window.performance;if(g){var g=g.timing||{},m="",n=g.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(g.navigationStart),b;for(b in c)void 0!==g[b]?(p=g[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";g=ensightenOptions.staticJavascriptPath||
"";m=g.indexOf(".com/");n=g.indexOf("/code/");g=g.substring(m+4,n)+"/perf.rnc";g+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+g)}}});
		Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(window.location.pathname=="/landingpages/droid/"||window.location.pathname=="/stores/"||window.location.pathname=="/landingpages/verizon-plan/"){var proj_id="3663580715";var cust_tags_obj={};cust_tags_obj[""]="";var local_keys=Object.keys(cust_tags_obj);window["optimizely"]=window["optimizely"]||[];if(local_keys[0]!=="")if(local_keys.length==1)window["optimizely"].push(["customTag",
local_keys[0],cust_tags_obj[local_keys[0]]]);else window["optimizely"].push(["customTag",cust_tags_obj]);document.write('\x3cscript type\x3d"text/javascript" src\x3d"//cdn.optimizely.com/js/'+proj_id+'.js"\x3e\x3c/script\x3e')}},1084772,348775);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(typeof vzwDL!="undefined"){var platform=vzwDL.page.platform;var condition=vzwDL.page.condition;var pageType=vzwDL.page.pageType;var section2=vzwDL.page.section2;Bootstrapper.getExtraParams=function(){var a={"platform":platform,"condition":condition,"pageType":pageType,"section2":section2};return a}}},971997,[510339],296960,[164233]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=
path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId-1;i>0;i--)if(!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);
var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};window._log=function(m){window._enslog=
window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p&&p=="act"){if(~v.indexOf("$$$"))console.log(v)}else if(p&&p=="cloak"){if(~v.indexOf("*** Cloak"))console.log(v)}else if(p)console.log(m)}};Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=
b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},
i={hidden:[],cloaks:[],EDLutils:!0,initialized:!1,invisibilityCloak:!1,disabled:!!~window.location.search.indexOf("ensTools\x3ddisable"),cloakDisabled:(true||!!~window.location.search.indexOf("ensCloak\x3ddisable"))&&!~window.location.search.indexOf("ensCloak\x3denable"),forceSyncCloak:!!~window.location.search.indexOf("ensCloak\x3d")&&!!~window.location.search.indexOf("!resync"),content:{initialized:!1,map:{},list:"",target:function(o){if(typeof o=="string"&&~o.indexOf("##")&&~o.indexOf("@@"))this.store(o);
else{if(o instanceof Array){var c="";for(var i=0,l=o.length;i<l;i++)if(o[i].u)c+="##"+o[i].u+"@@"+(o[i].x||"")}else if(o.u)o="##"+o.u+"@@"+(o.x||"");this.store(o)}},utils:function(a,n,o){if(Bootstrapper.data)try{if(a=="get")return Bootstrapper.data.getEngine("store").utils.get(n);else if(a=="set")return Bootstrapper.data.getEngine("store").utils.set(n,o)}catch(e){Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL utils not available")}else{Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL not available")}},
store:function(o){if(!Bootstrapper.MVT.content.initialized)this.list=o;else{if(this.list=="")this.list=o;this.utils("set","_ensCloak",o)}_log("*** Cloak:Storage updated")},load:function(d){var cl;if(d==1)cl=this.list;else cl=this.utils("get","_ensCloak");if(!d){_log("GLOBAL: "+this.list);_log("STORED: "+cl)}if(typeof cl=="string"&&cl!=""&&~cl.indexOf("##")){cl=cl.split("##");for(var i=0,l=cl.length;i<l;i++)if(~cl[i].indexOf("@@")){var u=cl[i].split("@@")[0],x=cl[i].split("@@")[1]||"";if(d=="list"){_log("URL: "+
u);_log("XPATH: "+x)}this.add({"u":u,"x":x})}_log("*** Cloak:Storage loaded")}else _log("*** Cloak:Storage empty")},add:function(o){if(o.u){if(~window.location.href.indexOf(o.u))if(o.x&&o.x!=""){if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}}else Bootstrapper.MVT.invisibilityCloak=true}else if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}},init:function(){if(!Bootstrapper.MVT.cloakDisabled){var sync=this.utils("get","_ensCloakSync")||"",time=
(new Date).getTime(),fetch=true;if(Bootstrapper.MVT.EDLutils){if(~sync!=""&&!isNaN(sync))if(time-sync>18E5)sync=time;else fetch=false;else sync=time;if(fetch)this.utils("set","_ensCloakSync",sync)}else fetch=false;if(fetch||Bootstrapper.MVT.forceSyncCloak){if(Bootstrapper.scDataObj)Bootstrapper.scDataObj["ensCloak"]="sync";if(this.list=="")Bootstrapper.MVT.invisibilityCloak=true;_log("*** Cloak:Syncing")}this.load(1);this.load(2)}var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,
m:m[i].x,t:"map"});if(Bootstrapper.MVT.invisibilityCloak&&!Bootstrapper.MVT.disabled&&!Bootstrapper.MVT.cloakDisabled)Bootstrapper.MVT.cover()}},addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){Bootstrapper.MVT.content.initialized=!0;Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");Bootstrapper.MVT.initialized=
!0;_log(h.tests.slice());if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},push:function(o){if(Bootstrapper.MVT.disabled)return;if(typeof o=="object"){_log("*** MVT:push");_log(o);if(typeof this.setDone=="undefined"){this.setDone=1;Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.done()});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.done()},500)})}if(o.x){o.cloak=this.cloak(o,1);if(o.t&&this.content.map[o.x])if(o.t=="map")this.content.map[o.x].cloak=
o.cloak;else if(this.content.map[o.x].cloak)Bootstrapper.MVT.delCSS(this.content.map[o.x].cloak)}if(this.initialized&&o.x){_log("MVT:content");_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);this.hidden.push(o)}}},injectCSS:function(x,e){var d=document,s=d.createElement("style");if(e)s.className=
"_ensCSS";if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);s.styleSheet.cssText=x}else{s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},delCSS:function(s,f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},cover:function(){_log("*** Cloak:Cover");this.invisibilityCloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");
Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("Uncover - complete")});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - loaded")},500)});setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - timeout")},7E3)},uncover:function(l){if(this.invisibilityCloak)if(this.delCSS(this.invisibilityCloak)){this.invisibilityCloak=!1;_log("*** Cloak:"+l)}},cloak:function(o,t){var s=false,x=o.toString();if(typeof o=="object"&&o.x)x=o.x;
if(~x.indexOf("/HTML/"))x=x.substr(1).replace(/\//g," ").replace(/\[.*\]$/g,"");s=Bootstrapper.MVT.injectCSS(x+"{visibility:hidden !important}",t);if(t)this.cloaks.push(s);return s},show:function(a,b){if(b&&b.cloak)this.delCSS(b.cloak);else if(a){a.style.display=a.style.oldDisplay||"block";a.style.visibility="visible"}},done:function(){var a=this.hidden,c=this.cloaks,s=document.getElementsByTagName("style");for(i=0;i<h.length;i++)this.show(h[i]);this.hidden=[];for(i=0;i<c.length;i++)this.delCSS(c[i]);
this.cloaks=[];for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i]);_log("*** MVT:done")},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},25);else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found")}},traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=
c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);b=f}else{a="/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),25);return}else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found");
return}}}d?this.swap(b,c[0]):h.split(c,b)}};return i}();Bootstrapper.bindOnGetServerComponent(function(){Bootstrapper.MVT.init()});Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone=="undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!=
"map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+b.m);Bootstrapper.MVT.show(a,b)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p=="replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=
a.className+" ensContent";d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p=="element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p=="after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,
a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a,b)}});Bootstrapper.dataManager=function(){var _private={data:{},add:function(o){if(typeof o=="object"&&o.id){o.get=function(e){return Bootstrapper.dataManager.getDataElement(this.id,
e)};this.data[o.id]=o}},getObj:function(i){if(i)return _private.data[i];return _private.data},getDataElement:function(i,e){if(typeof this.data[i]=="undefined")return"";var dataObj=this.data[i].data,retVal;if(typeof dataObj=="object"){if(typeof dataObj[e]=="undefined")return"";dataObj=dataObj[e];if(typeof dataObj.get=="string"){var d=eval(dataObj.get);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod==
"function")retVal=dataObj.mod.call(d,d);else retVal=d}else if(typeof dataObj.get=="function"){var d=dataObj.get.call(this.data[i]);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}return retVal}},getDataLayer:function(i){var retObj={};var dataObj=this.data[i].data;for(key in dataObj)try{retObj[key]=this.getDataElement(i,
key)}catch(e){retObj[key]=null}return retObj},getAllData:function(){var data=this.data,retObj={_d:{}};for(var key in data){retObj._d[key]={};var d=this.getDataLayer(key);for(var k in d){retObj[k]=d[k];retObj._d[key][k]=d[k]}}return retObj},getData:function(i){if(i)return this.getDataLayer(i);else return this.getAllData()},addDataElement:function(layerId,name,o){if(typeof this.data[layerId]=="object"&&typeof name=="string"&&typeof o=="object"){var d=this.data[layerId];d.data[name]=o}}},_public={push:function(dl){_private.add(dl)},
getObj:function(i){return _private.getObj(i)},getData:function(i){return _private.getData(i)},getDataElement:function(i,e){return _private.getDataElement(i,e)},addDataElement:function(layerId,name,o){return _private.addDataElement(layerId,name,o)}};return _public}();Bootstrapper.eventManager=function(){var _private={events:{},pushTrack:function(name,fn){if(typeof name!="string")return false;this.events[name]=this.events[name]||[];if(typeof fn=="function")this.events[name].push(fn);return true},callTrack:function(name){if(typeof name!=
"string")return false;var l=_private.events[name];if(typeof l=="object"&&l.length)for(var i=0;i<l.length;i++)l[i].call(this)},bind:function(layer,name,fn){var node=Bootstrapper.dataManager.getDataElement(layer,name),event=name.split("#")[1],name=name.split("#")[0],bound=typeof this.events[name]!="undefined"?true:false;if(typeof node.nodeName!="undefined"){this.pushTrack(name,fn);if(!bound)if((event=="onelementvisible"||event=="onelementexists")&&typeof Bootstrapper.propertyWatcher!="undefined"){Bootstrapper.eventManager.watch=
Bootstrapper.eventManager.watch||{};if(~event.indexOf("vis")){Bootstrapper.eventManager.watch[name]=Bootstrapper.propertyWatcher.create(function(){return node},["style","display"]);Bootstrapper.eventManager.watch[name].change=function(p,o,n){if(n!="none")Bootstrapper.eventManager.track(name,this)}}else{Bootstrapper.eventManager.watch[name]=Bootstrapper.propertyWatcher.create(function(){return node},["style","display"]);Bootstrapper.eventManager.watch[name].change=function(p,o,n){if(o=="undefined")Bootstrapper.eventManager.track(name,
this)}}}else Bootstrapper.unobtrusiveAddEvent(node,event,function(){Bootstrapper.eventManager.track(name,this)})}else if(typeof node=="object"&&typeof node.length!="undefined"){this.pushTrack(name,fn);if(!bound)for(i=0,l=node.length;i<l;i++)Bootstrapper.unobtrusiveAddEvent(node[i],event,function(){Bootstrapper.eventManager.track(name,this)})}},debug:function(name,ref){if(~window.location.search.indexOf("ensightenDebug"))console.log("::eventManager - Name:"+name+" ::eventManager - Scope:"+ref)}},_public=
{bindTracker:function(layer,name,fn){return _private.bind(layer,name,fn)},getEvent:function(name){return _private.events[name]},getAll:function(){return _private.events},track:function(name,ref){var $this=ref||window;_private.debug(name,$this);return _private.callTrack.call($this,name)}};return _public}();Bootstrapper.dataManager.map=function(){var _private={gD:{},mD:function(g){var e=window.document.getElementsByTagName("META")||[];for(var m=0,l=e.length;m<l;m++){var n=e[m].name||e[m].getAttribute("property")||
"";if(n==g)return e[m].content}},gP:function(p){var s;return(s=(new RegExp("\x26"+p+"\x3d([^\x26]*)")).exec(window.location.search.replace(/^\?/,"\x26")))?s[0].split("\x3d")[1]:""},gC:function(c){var v;return(v=(new RegExp("^"+c+"\x3d.*|;\\s*"+c+"\x3d.*")).exec(window.document.cookie))?v[0].split("\x3d")[1].split(";")[0]:""},gT:function(g){try{return this.mD(g)||this.gC(g)||this.gP(g)||window[g]||""}catch(e){return""}},dF:function(n,d){this.gD={};for(i in d){var val=typeof d[i]=="string"?this.gT(d[i]):
d[i]();if(~window.location.href.indexOf("ensightenDebug"))console.log(i+": "+val);this.gD[i]={name:i,get:'(function(){return("'+val+'")})()'}}Bootstrapper.dataManager.push({name:n,id:n,data:this.gD})}},_public={define:function(n,d){_private.dF(n,d)},get:function(g){return _private.gT(g)}};return _public}();window.$data=function(n,d){try{return Bootstrapper.dataManager.getDataElement(n,d)}catch(e){return""}};window.$getData=function(d){return Bootstrapper.dataManager.map.get(d)};Bootstrapper.dataManager.dataImport=
function(O,N,T){var DM=Bootstrapper.dataManager;if(typeof DM.getObj()[N]=="undefined")DM.push({name:N,id:N,data:{}});for(i in O)if(T!="simple"&&typeof O[i]=="object"){DM.dataImport(O[i],T=="flattened"?N:i,T);console.log(T)}else if(typeof O[i]!="object"||O[i]==null)try{eval('Bootstrapper.dataManager.addDataElement(N,i,{name:i,get:function(){try{return "'+O[i]+"\"}catch(e){return'error'}}})")}catch(e){}};Bootstrapper.targetingExtension=function(){var o=ensightenOptions,DL=typeof Bootstrapper.dataManager!=
"undefined"?Bootstrapper.dataManager.getData():false;if(DL)delete DL["_d"];if(~document.cookie.indexOf("VTP:enabled")){if(!DL)DL={};DL["ensightenVT"]=1}if(typeof Bootstrapper.getExtraParams!="undefined"){var p=Bootstrapper.getExtraParams();if(typeof p=="object"){if(!DL)DL={};for(i in p)DL[i]=p[i]}}Bootstrapper.insertScript("//"+(typeof ensightenOptions.serverComponentLocation!="undefined"?ensightenOptions.serverComponentLocation:o.nexus+"/"+o.client+"/serverComponent.php"),false,DL)};if(typeof Bootstrapper._getServerComponent!=
"undefined")Bootstrapper._getServerComponent=Bootstrapper.targetingExtension;else Bootstrapper.getServerComponent=Bootstrapper.targetingExtension;Bootstrapper.propertyWatcher=function(f){var g={watchers:[]},p={};g.options=f||{};g.options.interval=g.options.interval||50;g.Watcher=function(c,d){var e={};e.propertyFn=c;e.lastValue=undefined;e.options=d;e.change=function(a,b){};return e};g.doChecks=function(){for(var i=0;i<g.watchers.length;i++){var w=g.watchers[i],p=w.propertyFn?w.propertyFn():null;
if(w.lastValue!=p){w.change(w.lastValue,p);w.lastValue=p}}g.resetTimer()};g.resetTimer=function(){window.setTimeout(function(){g.doChecks()},g.options.interval)};g.addWatcher=function(a,b){var w=g.Watcher(a,b);g.watchers.push(w);return w};p={create:g.addWatcher};g.doChecks();return p}();Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["MVT"]=this.deploymentId;Bootstrapper.dataManager.pushObject=function(obj,id,name){Bootstrapper.dataManager.push({name:name||id,id:id,data:{}});
for(var k in obj)if(obj[k]&&typeof obj[k]!=="function")Bootstrapper.dataManager.addDataElement(id,k,{name:k,get:function(o,key){return function(){return o[key]}}(obj,k)})};Bootstrapper.ajaxListener=function(){var listeners={},listener=function(a,b){var detected=[],selector=a||function(){},attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n=="object")if(typeof n.length!="undefined"){n=Array.prototype.slice.call(n,0);for(var i=
n.length-1;i>=0;i--)for(var j=0;j<detected.length;j++)if(n[i]==detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==detected[i])return;detected.push(n);attach.call(n,n)}}}},_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},500);return _public}()},510339,164233);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;creditVariable=function(){if(jQuery(".metrics-data").length>0){creditCode="";if(jQuery(".metrics-data").data("creditReasonCode")!=undefined&&jQuery(".metrics-data").data("creditReasonCode")!="undefined")if(jQuery(".metrics-data").data("creditReasonCode").length>0)creditCode+="ReasonCode:"+jQuery(".metrics-data").data("creditReasonCode").substring(0,2)+"|";if(jQuery(".metrics-data").data("creditServiceClass")!=
undefined&&jQuery(".metrics-data").data("creditServiceClass")!="undefined")if(jQuery(".metrics-data").data("creditServiceClass").length>0)creditCode+="ServiceClass:"+jQuery(".metrics-data").data("creditServiceClass")+"|";if(jQuery(".metrics-data").data("creditClassCode")!=undefined&&jQuery(".metrics-data").data("creditClassCode")!="undefined")if(jQuery(".metrics-data").data("creditClassCode").length>0)creditCode+="ClassCode:"+jQuery(".metrics-data").data("creditClassCode")+"|";if(jQuery(".metrics-data").data("downPayment")!=
undefined&&jQuery(".metrics-data").data("downPayment")!="undefined"&&jQuery(".metrics-data").data("downPayment")!=0)if(jQuery(".metrics-data").data("downPayment").length>0)creditCode+="DownPayment:"+jQuery(".metrics-data").data("downPayment")+"|";if(jQuery(".metrics-data").data("dppEligibility")!=undefined&&jQuery(".metrics-data").data("dppEligibility")!="undefined")if(jQuery(".metrics-data").data("dppEligibility").length>0)creditCode+="DPPEligibility:"+jQuery(".metrics-data").data("dppEligibility")+
"|";if(jQuery(".metrics-data").data("creditApprovalStatus")!=undefined&&jQuery(".metrics-data").data("creditApprovalStatus")!="undefined")if(jQuery(".metrics-data").data("creditApprovalStatus").length>0)creditCode+="ApprovalStatus:"+jQuery(".metrics-data").data("creditApprovalStatus")+"|";s.prop30=creditCode=creditCode.substring(0,creditCode.length-1)}}},1253555,370505);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();