(function(){var f=!0,j=!1,k;
function l(a){function b(){e||(e=f,d?c.h.ra=f:c.fa(a))}var c=this,d=j,e=j;c.Ka=a.useFlashFallback===j?j:!c.i;c.D=a.statBaseURL;c.N=a.guid||a.GUID;c.J=a.confID;c.n=a.viewableConversion;c.X=a.api&&!(a.api.bridge===a.api.fallbackAPI||a.api._BRIDGE===a.api.fallbackAPI);c.Fa={viewable:"202",undetectable:"270",rendered:"271"};c.Ga=function(c){return a.replaceMacros(c)};c.ja=c.n?a.viewableImpressionURL:"";c.width=parseInt(a.width,10);c.height=parseInt(a.height,10);c.b=242500<=c.width*c.height?0.6*a.viewableImpressionThreshold:
a.viewableImpressionThreshold;c.s=0;c.Qa=j;c.R=a.viewableImpressionTime;c.w=a.customDefinition;c.t=0;c.ka=j;c.Z=j;c.A=/iP(ad|od|hone)/.test(navigator.userAgent);c.i=c.A||/safari/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&!/android/i.test(navigator.userAgent)&&!/edge/i.test(navigator.userAgent)&&!/phantomjs/i.test(navigator.userAgent);c.target=c.c?window.document.getElementById(a.adId):window.parent.document.getElementById(a.adId)||window.frameElement;c.r=c.O=c.visibility.u;
c.K=0;c.P=(new Date).getTime();c.q=(new Date).getTime();c.d=0;c.e=0;c.m=0;c.Ia=a.secure;c.renderedImpression=a.firedRenderedImpression||j;c.viewableImpression=j;c.undetectableImpression=j;c.ia=0;c.a={visible:0,C:0,hidden:0,F:0};c.I=f;c.dispatchEvent=function(c,b){a.dispatchEvent(c,b)};c.A&&this.ha(window,"scroll",function(){l.prototype.ga=Date.now()});if(a.fver&&a.minflashversion)this.$=!!a.fver();else{var h=j;this.H||"undefined"!=typeof navigator.plugins["Shockwave Flash"]&&(h=!!parseFloat(navigator.plugins["Shockwave Flash"].description.substring(15)));
this.$=h}"no"!==a.pageVisible&&!c.i&&c.j("rendered");c.c&&(window.$sf&&window.$sf.ext?c.f=c.Ha:"undefined"!==typeof window.mozInnerScreenY?(c.ta=c.f,c.f=c.va):8<=document.documentMode?c.f=c.Da:c.$&&!c.U&&c.Ka&&!document.documentMode&&!c.i?(c.L={},c.ba=0,d=f,c.h={ra:j},c.l=[],c.k=[],c.aa={id:"99",left:"-10000",top:"-1"},window.ftPagefoldFlashListener=function(b){b=b.split("-");c.za(b[0],parseInt(b[1],10),a)},c.f=c.Aa,c.ua()):(c.g(this.event.qa),c.n&&(c.j("undetectable"),("no"!==a.pageVisible||!c.i)&&
c.j("rendered")),a.addEventListener("visibilitychange",function(a){"no"!==a&&!c.i&&c.j("rendered")}),c.dispatchEvent("advisibility",j)));c.undetectableImpression||(a.addEventListener("adonpage",b),a.addEventListener("backup",b))}function m(a){var b="";this.D=a.statBaseURL;this.N=a.guid;this.J=a.confID;this.U=/fox/i.test(navigator.appVersion);b=this.c?window.document.referrer:window.parent.document.location;b=escape(String(b).substr(0,200));this.g("314",b)}
function r(){this.J=this.N=this.D="";this.Ea=window!=top;this.c=j;if(this.Ea)try{window.parent.document.getElementsByTagName("head")[0].appendChild(window.parent.document.createElement("script"))}catch(a){this.c=f}this.U=/fox/.test(navigator.userAgent);this.H=/MSIE/.test(navigator.userAgent);this.i=/Safari/.test(navigator.userAgent)&&!/Chrome/.test(navigator.userAgent)}l.prototype=new r;k=l.prototype;
k.event={pa:"301",oa:"302",T:"303",na:"304",la:"305",ma:"306",S:"307",qa:"308",Pa:"310",Oa:"311",Na:"312"};k.visibility={o:2,v:1,u:0};k.ga=0;k.V=[50,175,300,600,1200,3E3];
k.fa=function(a){var b=this;b.target=b.target||(b.c?document.getElementById(a.adId):window.parent.document.getElementById(a.adId)||window.frameElement);var c=this.f(),d=this.event.na;1===c&&!b.w?d=this.event.pa:0<c&&(d=this.event.oa);this.g(d);this.r=this.O=this.da(c);!a.api||"loading"!==a.api.getState()?this.W(a):a.api.addEventListener("ready",function(){b.W(a)})};
k.Q=function(){var a=this,b=(new Date).getTime(),c=b-this.P-this.d,d=b-this.q-this.e,e=this.f(),h=this.da(e);a.A&&250<d&&(b-this.ga<d?e=Math.min(this.ia,e):(this.s=0,a.d+=Math.max(0,b-this.q),a.e+=Math.max(0,b-this.q),c=b-this.P-this.d,d=b-this.q-this.e));a.I&&a.target.parentNode&&(this.dispatchEvent("advisibility",100*e),this.undetectableImpression?this.a.F+=d:1==e?this.a.visible+=d:0<e?this.a.C+=d:this.a.hidden+=d,this.w&&(h===this.visibility.o?this.t+=d:this.t<this.R&&(this.t=0),!this.ka&&this.t>=
this.R&&(this.O===this.visibility.v?this.g(this.event.T):this.g(this.event.S),this.ka=f)),h>this.r&&this.Ja(h),this.K<this.V.length&&this.p(c)>=this.V[this.K]&&(this.ya(),this.P=b,this.d=0,this.K++),a.n&&(!this.La&&this.ja)&&(this.s=e>=this.b?this.s+d:0,this.s>=this.R&&(window.Sa=f,this.j("viewable"))),this.q=b,this.e=0,this.ia=e);a.target.parentNode&&((!a.X||a.X&&(a.n&&!a.La||!a.n&&!a.Z))&&a.I)&&setTimeout(function(){a.Q()},100)};k.B=function(a){return"yes"===a||"no"!==a&&(this.c||this.A)};
k.W=function(a){var b=this;b.m=b.B(a.pageVisible)?0:(new Date).getTime();b.B(a.pageVisible)&&b.Q();a.addEventListener("visibilitychange",function(a){b.B(a)?(b.d+=b.m?(new Date).getTime()-b.m:0,b.e+=b.m?(new Date).getTime()-b.m:0):(b.m=(new Date).getTime(),b.s=0);b.I=b.B(a);"no"!==a&&!b.i&&b.j("rendered");b.Q()})};
k.ya=function(){var a=[this.p(this.a.visible)];a.push(this.p(this.a.C));a.push(this.p(this.a.hidden));a.push(this.p(this.a.F));this.g("310",a.join("x"));this.a.visible=0;this.a.C=0;this.a.hidden=0;this.a.F=0;this.Z=f};k.j=function(a){!this[a+"Impression"]&&this.n&&((new Image).src=this.Ga(this.ja.replace(";271;",";"+this.Fa[a]+";")),this[a+"Impression"]=f,"undetectable"===a&&(this.viewableImpressionFired=f))};
k.Ja=function(a){var b;this.r===this.visibility.u?a===this.visibility.v?b=this.event.la:a===this.visibility.o&&(b=this.event.ma):this.r===this.visibility.v&&(a===this.visibility.o&&!this.w)&&(b=this.event.T,this.O===this.visibility.u&&(b=this.event.S));this.r=a;"undefined"!==typeof b&&this.g(b)};k.f=function(){var a=this.Ba();return this.Y(a,this.ea())};k.va=function(){var a=this.wa(),b=this.xa();return Math.min(this.ta(),this.Y(a,b))};k.Ha=function(){return window.$sf.ext.inViewPercentage()/100};
k.ca=function(a,b,c){a=(a=/swf/i.test(a.id)&&/ftin/i.test(a.parentNode.id)&&a.parentNode.style.clip.replace(/^.*\(|px|\)/g,""))?a.split(" "):[0,b,c,0];return{top:parseInt(a[0],10),left:parseInt(a[3],10),right:parseInt(a[1],10),bottom:parseInt(a[2],10)}};k.z=function(a){var b=a.getBoundingClientRect(),c={};(a=this.ca(a,b.right-b.left,b.bottom-b.top))?(c.top=b.top+a.top,c.left=b.left+a.left,c.right=a.right-a.left+c.left,c.bottom=a.bottom-a.top+c.top):c=b;return c};
k.Ba=function(){var a=this.z(this.target),b=this.c?window.document.body.getBoundingClientRect():window.parent.document.body.getBoundingClientRect(),c=this.ea(),d=c.scrollLeft&&window.getComputedStyle&&b.left-(parseInt(window.parent.getComputedStyle(window.parent.document.body).marginLeft,10)||0)||0,b=c.scrollTop&&window.getComputedStyle&&b.top-(parseInt(window.parent.getComputedStyle(window.parent.document.body).marginTop,10)||0)||0;return window.attachEvent?{x:a.left+c.scrollLeft,y:a.top+c.scrollTop,
width:a.right-a.left,height:a.bottom-a.top}:{x:a.left-d,y:a.top-b,width:a.right-a.left,height:a.bottom-a.top}};
k.ea=function(){var a={scrollLeft:0,scrollTop:0,height:0,width:0},b=!this.c?window.parent:window;b.innerWidth?(a.width=b.innerWidth,a.height=b.innerHeight,a.scrollLeft=b.pageXOffset,a.scrollTop=b.pageYOffset):b.document.documentElement&&b.document.documentElement.clientHeight?(a.width=b.document.documentElement.clientWidth,a.height=b.document.documentElement.clientHeight,a.scrollLeft=b.document.documentElement.scrollLeft,a.scrollTop=b.document.documentElement.scrollTop):b.document.body&&(a.width=
b.document.body.clientWidth,a.height=b.document.body.clientHeight,a.scrollLeft=b.document.body.scrollLeft,a.scrollTop=b.document.body.scrollTop);return a};k.Y=function(a,b){var c=b.scrollLeft,d=b.scrollLeft+b.width,e=b.scrollTop,h=b.scrollTop+b.height,g=a.x,i=a.x+a.width,n=a.y,p=a.y+a.height,t=(i-g)*(p-n),s=0,q;a:switch(f){case e>p:case c>i:case d<g:case h<n:q=f;break a;default:q=j}q||(c=Math.max(c,g),d=Math.min(d,i),e=Math.max(e,n),h=Math.min(h,p),s=(d-c)*(h-e));return Math.floor(100*(s/t))/100};
k.da=function(a){var b=this.visibility.u;this.w&&a>=this.b?b=this.visibility.o:1===a?b=this.visibility.o:0<a&&(b=this.visibility.v);return b};k.wa=function(){var a=this.z(this.target);return{x:window.mozInnerScreenX+a.left,y:window.mozInnerScreenY+a.top,width:a.right-a.left,height:a.bottom-a.top}};k.xa=function(){return{scrollLeft:window.screenX,scrollTop:window.screenY+98,height:window.outerHeight-71,width:window.outerWidth}};
k.Da=function(){function a(a,b){var c=0;return c=1>b?0:b<a?0.1:b<d?e:1}var b=0,c=this.M(f);this.z(this.target);var d=0.5===this.b?9:12,e=this.b,h;for(h in c)b+=document.elementFromPoint(c[h].left,c[h].top)?1:0;return 0.5===e?a(5,b):0.5<e?a(8,b):0.39<e?a(6,b):a(4,b)};k.Aa=function(){function a(a,b){var c=0;return c=1>b?0:b<a?0.1:b<d?e:1}var b=0,c=0,d=0.5===this.b?9:12,e=this.b,h;for(h in this.L)b+=this.L[h]<0.8*this.ba?1:0;c=0.5===e?a(5,b):0.5<e?a(8,b):0.39<e?a(6,b):a(4,b);this.sa();return c};
k.sa=function(){for(var a=this.l,b=this.M(),c=b.length;c--;)if(b[c].top!==a[c].top||b[c].left!==a[c].left)this.k[c].style.top=b[c].top+"px",this.k[c].style.left=b[c].left+"px";this.l=b};k.za=function(a,b,c){var d=0;"99"===a?this.ba=b:this.L[a]=b;this.h[a]=f;for(var e in this.h)this.h[e]||d++;if(0===d){if(this.k[0])a=this.k;else{a=document.querySelectorAll(".ftFlashPixel");for(b=a.length;b--;)a[b].id.replace("id","");a=void 0}this.k=a;this.fa(c);this.h.Ra=j}};
k.M=function(a){for(var b=this.z(this.target),c=this.ca(this.target,b.right-b.left,b.bottom-b.top),d=c.left,c=c.top,e=b.right-b.left,h=b.bottom-b.top,g=[],i=Math.sqrt(this.b),g=[Math.round(e*(1-i)),Math.round(e*(1-this.b)),Math.round(e*this.b),Math.round(e*i)],i=[Math.round(h*(1-i)),Math.round(h*(1-this.b)),Math.round(h*this.b),Math.round(h*i)],g=0.5===this.b?[{id:"0",left:0,top:i[0]},{id:"1",left:0,top:i[3]},{id:"2",left:g[0],top:0},{id:"3",left:g[0],top:h-1},{id:"4",left:e/2,top:h/2},{id:"5",left:g[3],
top:0},{id:"6",left:g[3],top:h-1},{id:"7",left:e-1,top:i[0]},{id:"8",left:e-1,top:i[3]}]:[{id:"0",left:0,top:i[0]},{id:"1",left:0,top:i[3]},{id:"2",left:g[0],top:0},{id:"3",left:g[0],top:h-1},{id:"4",left:g[1],top:i[1]},{id:"5",left:g[1],top:i[2]},{id:"6",left:g[2],top:i[1]},{id:"7",left:g[2],top:i[2]},{id:"8",left:g[3],top:0},{id:"9",left:g[3],top:h-1},{id:"10",left:e-1,top:i[0]},{id:"11",left:e-1,top:i[3]}],e=g.length;e--;)a?(g[e].left+=b.left,g[e].top+=b.top):(g[e].left+=d,g[e].top+=c);return g};
k.ua=function(){function a(a){var b,d="position: absolute; top: "+a.top+"px;",i=this.Ca(a.id),d=d+(" width: "+this.G.width+"px;"),d=d+(" height: "+this.G.height+"px;"),d=d+(" left : "+a.left+"px; z-index: -1;");this.H?(b=c.replace("@STYLE@",d).replace("@FLASH@",i).replace("@ID@",a.id),this.target.parentNode.insertAdjacentHTML("beforeend",b)):(b=document.createElement("div"),b.style.cssText=d,b.innerHTML=i,this.target.parentNode.appendChild(b),this.k[a.id]=b)}function b(){a.call(d,d.aa);d.h[d.aa.id]=
j;for(var b=0,c=d.l.length;b<c;b++)d.h[d.l[b].id]=j,a.call(d,d.l[b])}var c='<div id="id@ID@" class="ftFlashPixel" style="@STYLE@">@FLASH@</div>',d=this;this.target.getBoundingClientRect();this.l=this.M();document.body?b():this.ha(document,"readystatechange",function(){document.body&&b()})};
k.Ca=function(a){var b=this.G(),c=b.name+a,d;d="<OBJECT "+(this.H?'classid = "clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'data="'+b.path+'" type="application/x-shockwave-flash"');d=d+(' ID="'+c+'" name="'+c+'"')+(' width="'+b.width+'" height="'+b.height+'" style="float:left;">');d+='<PARAM NAME=movie VALUE="'+b.path+'"/>';d+='<PARAM NAME=FlashVars VALUE="identifier='+a+'"/>';d+='<PARAM NAME=quality VALUE="autohigh"/>';d+='<PARAM NAME=wmode VALUE="'+b.Ma+'"/>';d+='<PARAM NAME="allowScriptAccess" value="always"/>';
d+='<PARAM NAME="allowFullScreen" value="true"/>';return d+="</OBJECT>"};k.G=function(){return{path:(this.Ia?"https":"http")+"://cdn.flashtalking.com/pageFold/pagefold.swf",name:"ftPF",width:1,height:2,Ma:"transparent"}};k.p=function(a){return Math.max(0,Math.ceil(a/100))};m.prototype=new r;r.prototype.g=function(a,b){var c=[""+this.D+this.J];c.push(a);c.push("0");c.push(this.N);c.push(this.random());b&&c.push(b);this.D&&((new Image).src=c.join("-"))};
r.prototype.random=function(a){return Math.floor(Math.random()*(a||1E9))};r.prototype.ha=function(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener(b,c,j)};window.ftPageFold_v4=function(a){a.breakingOut!==f&&(new l(a),a.campaignID&&27400>parseInt(a.campaignID,10)&&new m(a))};}());
